### ISSUE TITLE
SYS_FUNC_REBOOT - just kills PiJuice.service

### ISSUE THREAD

**Issue by rohtua** [PiSupply/PiJuice#102]
When setting a button to run the SYS_FUNC_REBOOT function all that seems to be happening is it kills the PiJuice.service. Clicking apply in the settings window displays the following error:
![screen shot 2018-04-25 at 17 49 55](https://user-images.githubusercontent.com/36799326/39260371-2c82205c-48b1-11e8-834a-bc2624a8bf54.png)

Checking the status of PiJuice.service shows:

`pijuice.service - PiJuice status service
   Loaded: loaded (/lib/systemd/system/pijuice.service; disabled; vendor preset:
   Active: inactive (dead)`

Then when I run `sudo service pijuice restart` it restarts the pijuice service and performs the reboot but until I restart the service nothing happens to turn the Pi on or off.. Is there a way to force the service to reboot after a crash? 

Also I've been trying to run user functions but they don't seem to work for me, I've tried typing the command I'm after direct into the user_func box and tried point to a .sh file but nothing happens when I press the button.

**Comment by rohtua** [comment]
I've got it working, all I needed to do was run sudo systemctl enable pijuice that seems to have sorted the issue with SYS_FUNC_REBOOT

**Comment by tvoverbeek** [comment]
Closing issue
