### ISSUE TITLE
Problems with PiJuice overheating

### ISSUE THREAD

**Issue by sebastianpiccoli** [PiSupply/PiJuice#1025]
Hi,

We have a Raspberry Pi3B+ 1GB RAM and a PiJuice HAT. The battery seems to constantly overheat to 42/43°C even when there is little processor usage (around 7%).

We tried to set a custom battery profile using pijuice_cli and pijuice_gui but the changes don't get saved and get back to default when we reboot the device.

We upgraded the firmware to the latest (v 1.6) but in the newer version the problem persists and we have another issue: the temperature shown is 24°C even when the battery is still around 42°C (this measured using the J2 pinouts).

So we have basically 3 issues:
- Overheating of the battery
- Battery profile changes not saved
- Wrong temperature reading on pijuice 1.6.

Kind regards,
Sebastian.

**Comment by tvoverbeek** [comment]
Are we talking about the PiJuice HAT or the PiJuice Zero?
Only the Zero has a J2 battery connector. No way to measure the battery temperature directly,
unless you process the NTC measurement yourself.
How do you know profile changes are not saved?
You can only save the custom profile and that is stored in non-volatie memory.
This survives reboot since the custom profile is stored in non-volatile memory.
Did you press the Apply button in the GUI after defining the custom profile.
Also if you want to see the contents of the custom profile after selecting it you have to press the Refresh button.

**Comment by sebastianpiccoli** [comment]
This is a PiJuice HAT, picture attached:
![image](https://github.com/PiSupply/PiJuice/assets/150055510/dc1791e0-e409-4031-9b5b-32f79a2151a5)

This is what we mean by J2 (image taken from [here](https://learn.pi-supply.com/make/pijuice-quick-start-guide-faq/)):
![image](https://github.com/PiSupply/PiJuice/assets/150055510/98375d51-d6e4-4c56-a22d-b4c5ffbc2a3c)

Yes, of course we pressed appy in the GUI (and in the PiJuice Settings on graphic mode, since this issue is happening on both). When we reboot we see the default profile loaded, even when we have saved this:
![image](https://github.com/PiSupply/PiJuice/assets/150055510/d341b678-a160-4cc4-bd5b-f068af677e1d)

Kind regards,
Sebastian.

**Comment by sebastianpiccoli** [comment]
Any updates regarding this?

Regards,
Sebastian.

**Comment by tvoverbeek** [comment]
For me changing the battery profile works, also over reboots.

Starting with the default BP7X battery profile:
<img width="514" alt="Screenshot 2024-02-01 at 20 30 29" src="https://github.com/PiSupply/PiJuice/assets/1197294/da86b878-7af0-4926-86b3-33498f0191a0">

Changing a few parameters: Warm and hot temperature and selecting Custom:
<img width="512" alt="Screenshot 2024-02-01 at 20 36 13" src="https://github.com/PiSupply/PiJuice/assets/1197294/8325350a-f0fa-4a99-8631-fc23cf9d8fa1">

Scrollling down and select Apply Settings:
<img width="513" alt="Screenshot 2024-02-01 at 20 36 50" src="https://github.com/PiSupply/PiJuice/assets/1197294/ff83bb42-8dd0-4b6e-8acd-a79d188e0314">

Confirmation screen:
<img width="512" alt="Screenshot 2024-02-01 at 20 37 15" src="https://github.com/PiSupply/PiJuice/assets/1197294/b3591b2a-746f-4a33-9c8a-1f3b04d897d8">

Then reselecting Battery Profile:
<img width="508" alt="Screenshot 2024-02-01 at 20 38 36" src="https://github.com/PiSupply/PiJuice/assets/1197294/52b87333-9fb3-4bae-93c9-25fc57a4d9ee">

Profile name is now Custom.

Restarting pijuice_cli still shows battery profile Custom (with the changed BP7X values).
Same after reboot.
Same after shutting down, removing the HAT, remounting the HAT and booting.

So I do not understand why your custom profile is not saved.

**Comment by sebastianpiccoli** [comment]
We change the profile to custom, apply it. We exit pijuice_cli and run it again. Everything works fine and we see the custom profile being set:
![1](https://github.com/PiSupply/PiJuice/assets/150055510/e4338b32-eff5-44c2-a08a-4929a9cbc676)

When we reboot it, the profile has been set to default again:
![2](https://github.com/PiSupply/PiJuice/assets/150055510/fb31e1c1-8024-4160-b2e2-459ed6b355c0)

One thing worth mentioning is that we cannot run pijuice_cli as root, it errors out when we go to "Battery profile". We can set the values only running pijuice_cli with user pi:
![3](https://github.com/PiSupply/PiJuice/assets/150055510/95ffc7e6-d657-4c7e-b92a-26dafe513105)

**Comment by sebastianpiccoli** [comment]
Hi,

We have finally found the root of our problem. We found a script called "wakeup" which was resetting the battery profile on startup. We can now close this issue. Thanks for your support.

Sebastian.
