### ISSUE TITLE
Lost Bracket

### ISSUE THREAD

**Issue by smartpandapl** [PiSupply/PiJuice#1037]
hi everyone,

I lost my mounting brackets for the PiJuice. These transparent plastic parts, screws and spacers. I have no idea how to get them without buying a whole PiJuice. Does someone has a 3d model of them? I want to make a mini nas with the Rpbi4B so I really need them.

best regards,
tymek

**Comment by shawaj** [comment]
https://github.com/PiSupply/PiJuice/tree/master/Hardware/3D/Surround

Or email sales@pi-supply.com as we probably have spares
