### ISSUE TITLE
Failed to execute command "/usr/bin/pijuice_gui"

### ISSUE THREAD

**Issue by BigDogsDad** [PiSupply/PiJuice#1050]
On Pi Desktop Clicking Preferences- PiJuice setting- Throws Error that states, "Failed to execute child process "/user/bin/pijuice_gui" (No such file or directory) Currently Running Pi4 with Raspbian GNU/Linux 12 (bookworm). Any help would be appreciated. Thank you.

**Comment by tvoverbeek** [comment]
Are you running 32-bit version of bookworm?
If so see Issue #1000.
64-bit version of bookworm should work.
Problem is on 32-bit bookworm the linux kernel is 64-bit which upsets the 32-bit/64-bit detection in the pijuice-base and pijuice-gui installation.

**Comment by BigDogsDad** [comment]
It looks like I'm 64 but when I ran another command it shows 32 so I'm guessing 32.
![aarch64](https://github.com/PiSupply/PiJuice/assets/155214605/4082216e-9a73-4fdc-a010-cadc3c529844)

**Comment by BigDogsDad** [comment]
I saw in your issue #1000 that you had that fellow run the ls -l 
![ls -l](https://github.com/PiSupply/PiJuice/assets/155214605/7d9f7abe-9912-488f-a5ec-62254ca3a3ee)
/user/bin/pijuice* command and this is what I got for that

**Comment by BigDogsDad** [comment]
Lastly I also tried running sudo rm and sudo ln. The good news is that I no longer get the error when I click on the PiJuice seettings. Then bad news is that nothing happens at that point. No error,  no preference choices, nothing.

![sudo rm and ln](https://github.com/PiSupply/PiJuice/assets/155214605/478cc769-457d-4dc9-848e-453a35ad6005)

**Comment by tvoverbeek** [comment]
This is on a pi 3b+ or pi4 running 32-bit bookwormd?
On 32-bit bookworm the linux kernel is 64-bit, but tuns 32-bit applications
`uname -a` will show aarch64 (= kernel is 64-bit).
If you are using wayland (the default in bookworm) see issue #1051 for a solution.

**Comment by BigDogsDad** [comment]
To confirm I'm running a Pi4. And it seems Wayland was the way forward. I now see the GUI and am able to explore all the options. Thank you VERY much for the assistance und Ich wünsche dir ein frohes neues Jahr.

**Comment by tvoverbeek** [comment]
Glad it works for you now. Closing the issue.
