### ISSUE TITLE
Software not opening.

### ISSUE THREAD

**Issue by Samu0535** [PiSupply/PiJuice#1051]
hello everyone, i am unable to open the PiJuice-settings software, after it is installed.
![20231231_13h00m07s_grim](https://github.com/PiSupply/PiJuice/assets/155301826/44a2ca00-1af2-4439-8eee-fa6bb8a24000)

can i get some advice? Thanks in advance!

**Comment by tvoverbeek** [comment]
Which OS version?
If this is Raspberrt Pi OS bookworm running Wayland then the pijuice gui does not work.
It is written with Tk as graphical toolkit. Tk is not supported under Wayland, hence app does not open.
In that case open raspi-config in a terminal (`sudo raspi-config`), 
Select Advanced Options -> Wayland -> X11 Openbox Window Manager with X11 backend.
Reboot to make it effective. Then it should work.

**Comment by Samu0535** [comment]
thank you for your reply.
going to raspi-config, and applying the setting worked!!
I hope you have a wonderful day!
