### ISSUE TITLE
PiJuice Zero Led and PiJuice battery connector references

### ISSUE THREAD

**Issue by hugokernel** [PiSupply/PiJuice#1060]
The D1 led on the PiJuice Zero was ripped off :( after I took it out of the bag, one of its contacts seems destroyed, I'd like to order a new one and replace it, can you give me its reference?

Also, can you tell me the part number of the BP7X battery connector on the PiJuice?

Thank you.

**Comment by tvoverbeek** [comment]
Found this (no guarantee if it is the right part no)

D1 Led "Lite-On LTST-S310F2KT" available at e.g. Mouser
BP7X batttery connector: "AVX 00-9155-004-742-006"

**Comment by hugokernel** [comment]
@tvoverbeek Hi, can I ask you about the reference of the PiJuice Zero battery connector, do you know his reference ?

**Comment by hugokernel** [comment]
Thanks for the reply.

I hadn't found the reference in the documentation :pray:
