### ISSUE TITLE
Lost my plastic battery clips

### ISSUE THREAD

**Issue by philicibine** [PiSupply/PiJuice#1092]
I have lost my plastic battery clips.  I am wondering if there is an .stl file available anywhere so I can 3d print some replacements?  Would be very grateful if there is as I have long lost these and looked everywhere!

**Comment by shawaj** [comment]
@philicibine here you go https://github.com/PiSupply/PiJuice/tree/master/Hardware/3D/Surround

**Comment by philicibine** [comment]
Thanks
