### ISSUE TITLE
apt-get repo address?

### ISSUE THREAD

**Issue by winstonford** [PiSupply/PiJuice#112]
what is the apt-get repo address for pijuice-base?

**Comment by tvoverbeek** [comment]
The pijuice packages are in the raspberry pi specific repo: http://archive.raspberrypi.org/debian/
which should be in /etc/apt/sources.list.d/raspi.list

**Comment by winstonford** [comment]
On my pimusicbox, which is based on debian wheezy, the repo is not found.  On my pis running debian 8 jesse and 9 stretch, apt-get does find and instal pijuice-base.

**Comment by tvoverbeek** [comment]
wheezy is too old.
For jessie and stretch do `sudo apt-get update` first before trying to install pijuice-base.

**Comment by jimklimov** [comment]
...And bullseye is too new ;(

http://archive.raspberrypi.org/debian/dists/bullseye/main/binary-arm64/Packages lacks pijuice* packages, while http://archive.raspberrypi.org/debian/dists/buster/main/binary-arm64/Packages has them.

(Sorry for the bump, thanks for the URL)

**Comment by tvoverbeek** [comment]
If you want to run the packages on 64-bit use multi-arch.
```
sudo dpkg add-architecture armhf
sudo apt-get update
sudo apt-get install libc6:armhf
```
This will install the 32-bit run time libraries, so the 32-bit executables will work on a 64-bit OS.
Note: the older buster 64-bit raspberry pi os already included multi-arch, the bullseye version does not.

**Comment by karsten-aichholz** [comment]
> If you want to run the packages on 64-bit use multi-arch.
> 
> ```
> sudo dpkg add-architecture armhf
> sudo apt-get update
> sudo apt-get install libc6:armhf
> ```
> 
> This will install the 32-bit run time libraries, so the 32-bit executables will work on a 64-bit OS. Note: the older buster 64-bit raspberry pi os already included multi-arch, the bullseye version does not.

I believe this should read:
`sudo dpkg --add-architecture armhf`

**Comment by tvoverbeek** [comment]
@karsten-aichholz Yes, you are right, my bad.
