### ISSUE TITLE
Documentation is hopelessly inadequate.

### ISSUE THREAD

**Issue by KeithSloan** [PiSupply/PiJuice#114]
I feel I am missing a source or sources of information. The user guide does not tell me what I need to know. Like what is the pogo pin for? Where does it go?

Need to fully understand the implications of plugging supply into pi versus into pijuice.

Explanation of output from GUI and what some of the terms mean.

**Comment by KeithSloan** [comment]
PIjuice GUI settings

What does system switch off | 500ma | 2100ma mean?
My GPIO input toggles between PRESENT, WEAK and BAD what is that all about?
What does -ve current on GPIO mean?

**Comment by shawaj** [comment]
Have you read the hardware readme on GitHub?

https://github.com/PiSupply/PiJuice/blob/master/Hardware/README.md

**Comment by KeithSloan** [comment]
Have scan read and rescanned just now. But do not see where it answers any of the questions

**Comment by shawaj** [comment]
It answers most if not all of your questions on the various GitHub readmes

**Comment by Madko** [comment]
And what does "System power switch" mean ? (off|500mA|2100mA)

**Comment by ChristopherRush** [comment]
This is with regards to the VSYS output on header P3. It is documented under https://github.com/PiSupply/PiJuice/blob/master/Hardware/README.md

**Comment by mwrich4** [comment]
I keep allowing the arrogance of this group to amaze me.  

Instead of posting an answer for others to find, we get the SAME "I'm always right" replies that have plagued the communications of this project.

**Comment by shawaj** [comment]
@mwrich4 - is there something you need help with at all?

**Comment by mwrich4** [comment]
I mentioned the inadequate documentation before you started shipping and before you tore down the website.  I think the current state of things illustrates the issues.  (off topic:  Pie-Hole ?!   REALLY ??)

**Comment by shawaj** [comment]
@mwrich4 - I asked before...is there something you need help with at all? Because you are saying the documentation is inadequate but you aren't actually saying what you need help with at all?

And for the record, the vast majority of the 2400+ people who 3500+ units that we've shipped to have absolutely no issue whatsoever with either the documentation or the product itself. I think our customer service and our assistance here speaks for itself so I won't say anything more than that.

**Comment by shawaj** [comment]
@tvoverbeek @KeithSloan agreed, someone else mentioned on another thread having tool tips next to each item with a bit of explanation of what it is/does. Think this is a really good idea and we are progressing it but it'll take some time. Thanks for the suggestion though

**Comment by Madko** [comment]
How do we set event triggers using the CLI ? I can find tips in the documentation but only with the GUI.

**Comment by shawaj** [comment]
@Madko please start a new issue rather than hijacking this one. It'll be easier for everyone now and in the future to have the answer in a dedicated issue

**Comment by Madko** [comment]
Ok I will start a new issue but I was not hijacking this one (I almost started it), it's still about inadequate documentation. And since you were asking if someone needed help. But Ok no big deal :)

**Comment by shawaj** [comment]
@Madko didn't mean hijacking in a bad way it's just easier to have everyone's individual issues separately so we can keep track of things better. Thanks very much! 😊

**Comment by klint-k** [comment]
Pogo??? #10

**Comment by shawaj** [comment]
FYI the maker zone links should be back up now

**Comment by ChristopherRush** [comment]
I believe everything is now adequately documented, if you do not agree then reopen.
