### ISSUE TITLE
Pi Juice dont charge. Batocera

### ISSUE THREAD

**Issue by toralora** [PiSupply/PiJuice#117]
Hi 
Ive got a problem  i wanna make a portable Console with Batocera and bought Pijuice.  but it doesnt charge and ive read that  Batocera/Recalbox are not able to  add other Programs. Is there a option to use both?

**Comment by tvoverbeek** [comment]
Suggest you first install Raspbian (maybe on a separate SD card) and install the pijuice packages.
Check the configuration and make sure the 'Charging Enabled' check box is selected on the General tab in the PiJuice HAT Configuration. Configure other parameters of the PiJuice as you need it.
When satisfied install Batocera (or switch SD cards).

**Comment by shawaj** [comment]
Also - have you made sure to remove the plastic battery tab between the battery and battery contacts?

**Comment by toralora** [comment]
the plastic tab ^^  that was never the Problem.  ive Tried  with Raspbian  and with  onetime Remove the Battery completly it worked. thx
