### ISSUE TITLE
Translucent battery mounting clip on PiJuice blocks HATs

### ISSUE THREAD

**Issue by claremacrae** [PiSupply/PiJuice#119]
This picture shows how the plastic clip that holds the supplied BP7X battery in place on my PiJuice is preventing HATs from being used.

![pijuice hat won t fit](https://user-images.githubusercontent.com/4840096/40083447-13edc268-588c-11e8-80da-fb0d502eec91.JPG)

I've tested this with the following, and they all have the same problem, and the Pi does not detect any of them:

* Displayotron
* Explorer HAT Pro
* Sense HAT gets a bit closer, but not enough - gets power, to show rainbow pattern, but the pattern does not disappear - the behaviour is as described in https://github.com/RPi-Distro/python-sense-hat/issues/70

An Explorer PHAT does work, though.

I presume I'm going to have to trim back the plastic clip, but I wanted first to know how others had solved this problem, or if there us something unusual about the plastic clip on my PiJuice?

**Comment by ChristopherRush** [comment]
I've had no issues with any of the HATs I've tried. Have you tried to
loosen the screw a bit? This might give the plastic a bit of leeway.

**Comment by ChristopherRush** [comment]
Here is how one of my HATs fit

![20180516_104959](https://user-images.githubusercontent.com/1878314/40110600-4a4e9b90-58f8-11e8-8c3a-786db00ab55e.jpg)

It doesn't sit all the way down because of the solder blobs, but it does make good contact. I would also say that your header looks much shorter, therefore will not sit flush with the PiJuice board. I'm assuming all these boards mentioned above still work?

**Comment by shawaj** [comment]
We have spares of the battery surrounds if your one can't be moved into position @claremacrae but as Chris has said you should be able to move it

**Comment by claremacrae** [comment]
So I think part of the issue may be that some HATs have much greater depth of plastic than others around the GPIO pins. Where a HAT has very shallow black plastic around the GPIO, it’s possible that circuitry on the underside of the HAT can clash against the bits and pieces on the top of the PiJuice.

@ChristopherRush what HAT is in your photo?

Ah - I see I have just stated exactly what you said, @ChristopherRush - thanks.

So it may be that I need to get some kind of male-to-female HAT extended, to allow the HAT to sit something like 1cm higher away from the PiJuice and then it will all work...

**Comment by claremacrae** [comment]
I’ll do some more experiments tomorrow....

**Comment by shawaj** [comment]
Yes we are actually selling some headers like that on our shop for that very reason.

Guess we need to make a note about that on here somewhere

Any testing you can do for clashes would be fantastic. We should maybe start a list here

**Comment by claremacrae** [comment]
Thanks @shawaj - is this the product you mentioned?

https://uk.pi-supply.com/products/40-pin-female-stacking-header

**Comment by shawaj** [comment]
You beat me to linking you. Yes that's it. I think we have some different height ones too but those work great

**Comment by shawaj** [comment]
@claremacrae do you mind if I use your picture above to explain this on the readme?

**Comment by claremacrae** [comment]
@shawaj Yes, no problem using the pic - thanks for asking.

**Comment by claremacrae** [comment]
I guess the thing is that once someone uses one of those stacking headers, they will then have a different problem that any stand-offs that they had previously used with the HAT will now not be high enough?

So then they’d either need to be really careful to not bend/break the PHAT or pins on the Pi, or source extra stand-offs.

 So I think that using PiJuice with (some) HATs is looking a bit challenging right now?

**Comment by claremacrae** [comment]
I ordered and just received “Adafruit Black Nylon Screw and Stand-off Set – M2.5 Thread” - the cost is all adding up though, and you have to know these things exist in the first place....

**Comment by claremacrae** [comment]
OK, I think I may be wrong on this one.

The script I was using to detect if the HAT was connecting no longer works - so it's possible - or probable - that some of these HATs were connected after all...

I've logged the problem with my script here: https://github.com/claremacrae/raspi_hat_data/issues/1

**Comment by shawaj** [comment]
Thanks. We will get a note about this added to the documentation

**Comment by shawaj** [comment]
@ChristopherRush can you document anything here that isn't already and then close?

**Comment by ChristopherRush** [comment]
Potential solution here - https://github.com/PiSupply/PiJuice/issues/119#issuecomment-389632660
