### ISSUE TITLE
Broken battery retaining clips

### ISSUE THREAD

**Issue by jdotbdot** [PiSupply/PiJuice#129]
Both of the smaller clear plastic retaining clips have broken on my PiJuice.
I don't think I've been rough with it.
Is this a common problem?

**Comment by shawaj** [comment]
*for sale

**Comment by jdotbdot** [comment]
I'll probably use Sugru!

**Comment by shawaj** [comment]
Yeah Sugru is great for this kind of thing :-)

**Comment by ilyastrodubtsev** [comment]
@jdotbdot tell us, please, could you make a clips using Surgu.

**Comment by jdotbdot** [comment]
I'm sure you can, I'm waiting for fresh supplies from China so I haven't done it yet.
