### ISSUE TITLE
MSDS BP7X.pdf weight field

### ISSUE THREAD

**Issue by rgw16** [PiSupply/PiJuice#13]
The weight specified in the Material Safety Data Sheet is given as 35kg.

One Amazon advertisement gives the weight as 36g, 3 orders of magnitude smaller.

This certificate may need to be re-issued.

**Comment by shawaj** [comment]
Thanks for the spot!

**Comment by klint-k** [comment]
What the heck? Do the battery's have a micro black hole?

**Comment by shawaj** [comment]
@klint-k yeah you nailed it. It is new battery tech :-P

**Comment by shawaj** [comment]
Fixed this now and also added some more documentation
