### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by klint-k** [PiSupply/PiJuice#130]
When is the pin-out going to be updated?

Check the main PiJuice Quick Start Guide and FAQ for a detailed assembly guide
Website down for maintenance!
We are in the process of launching a new and upgraded version of our website. Please bear with us during this process.
The website should be back up and running on Wednesday.

Our PiJuice Battery Discharge Time Calculator
404 Not Found

A lot of picture guides and tutorials are going up on our Maker Zone
Website down for maintenance!
We are in the process of launching a new and upgraded version of our website. Please bear with us during this process.
The website should be back up and running on Wednesday.

We will soon have the pinouts available at Raspberry Pi Pinout
404 - Oh dear!
Sorry, we couldn't find what you are looking for!

Use the pinout on the left to explore the pins and functions of the Raspberry Pi GPIO.

Or, use the menu above to discover new boards and learn about interfaces.

**Comment by ChristopherRush** [comment]
#116 Closing this as it is duplicated
