### ISSUE TITLE
Sample pijuice_config.JSON

### ISSUE THREAD

**Issue by jdotbdot** [PiSupply/PiJuice#131]
possibly a dumb question because I'm not very familiar with JSON.

Is there any reason why in the sample config file at 
https://github.com/PiSupply/PiJuice/blob/master/Software/README.md,
under "user_functions", USER_FUNC8 is listed before USER_FUNC1?

Does the line `"enabled":true,` between `"min_charge":{...}`, and `"wakeup_on_charge":{...}` indicate some missing function(s)?

If I edit the config file by hand, how do I get the PiJuice to recognise the changes?

**Comment by tvoverbeek** [comment]
@jdotbdot If you do not want to reboot then you have to send the SIGHUP signal to the pijuice service (pijuice_sys.py).
Example in a bash shell:
Find the process id (pid) of the pijuice_sys.py process and send the signal:
```
pi@rpi-stretch-full:~ $ ps ax | grep pijuice_sys | grep -v grep
  372 ?        Ss     0:12 /usr/bin/python /usr/bin/pijuice_sys.py
pi@rpi-stretch-full:~ $ sudo kill -SIGHUP 372
pi@rpi-stretch-full:~ $ 
```
Note, you need `sudo` because the pijuice service is started under the root user.
When pijuice_sys.py receives the signal, it will reload the json file.

**Comment by shawaj** [comment]
@ChristopherRush would you mind documenting this somewhere?

**Comment by ChristopherRush** [comment]
Do we know the answer to the below query? @tvoverbeek @shawaj 

Does the line `"enabled":true,` between `"min_charge":{...},` and `"wakeup_on_charge":{...}` indicate some missing function(s)?

**Comment by ChristopherRush** [comment]
I would assume it has something to do with system task enabled?

**Comment by tvoverbeek** [comment]
Yes, **sudo systemctl restart pijuice** works too.
But when sending the SIGHUP signal to pijuice_sys the service is **not** restarted, but the signal is caught and treated directly by pijuice_sys.
Similar to many unix/linux utilities to force them to reread their configuration file.

**Comment by ChristopherRush** [comment]
Documented
