### ISSUE TITLE
Different battery

### ISSUE THREAD

**Issue by bvicic** [PiSupply/PiJuice#132]
Hi there! I was thinking to buy the PiJuice for my RaspberryShake seismic station that I want to put in some remote place. As it is written, I can change the battery with a bigger, 10.000mAH battery. Can I use even more than 10.000? Also, is there some battery like that that anyone tested with pijuice? 

thanks

**Comment by shawaj** [comment]
You can use any single cell lipo or lithium ion battery

**Comment by ChristopherRush** [comment]
I have tested a 12A lipo battery with the PiJuice and it works great.

**Comment by bvicic** [comment]
thanks!
