### ISSUE TITLE
Graphical interface too large on little screens

### ISSUE THREAD

**Issue by sakura-lain** [PiSupply/PiJuice#133]
Hi again,

The graphical interface used to manage the PiJuice is too large on my 5" touch screen, it doesn't automatically adapt to the size of the screen and it seems impossible in that case to scroll down or reduce the window. Is there something I missed ?

Thanks again.

**Comment by ChristopherRush** [comment]
Minimum window size is 400x400, try using the pijuice_cli.py from the terminal.

**Comment by shawaj** [comment]
What's the resolution of the display?

**Comment by tvoverbeek** [comment]
@ChristopherRush Note the size of the HAT configuration window is 640x480

**Comment by ChristopherRush** [comment]
@tvoverbeek Yes I had seen that in the code and also `root.minsize(400, 400)`

**Comment by ChristopherRush** [comment]
@shawaj 
![20180525_160943](https://user-images.githubusercontent.com/1878314/40551949-3d559ab6-6036-11e8-8e5e-00912057e5b6.jpg)

**Comment by tvoverbeek** [comment]
Just checked on a small terminal. Thanks to python-urwid it works fine.
If there are more entries than fit on the screen you get a scroll bar and you can scroll up/down with the arrow keys.
Also when mouse is supported in terminal, mouse works too.

**Comment by tvoverbeek** [comment]
From https://www.raspberrypi.org/documentation/hardware/display/troubleshooting.md:
```
Some windows are cut off at the bottom of the screen so I can't use them

If some windows in X are cut off at the side/bottom of the screen, this is unfortunately a side-effect of developers assuming a minimum screen resolution of 1024x768 pixels.

You can usually reveal hidden buttons and fields by;

right clicking on the edge or top of the window,
picking "move"
using the up arrow key to nudge the window up off the top of the screen
If you don't have a mouse, see the right click fix below.
```
Does that help?

**Comment by ChristopherRush** [comment]
Solution is to use the CLI like this - https://github.com/PiSupply/PiJuice/issues/133#issuecomment-392089245 or refer to this comment - https://github.com/PiSupply/PiJuice/issues/133#issuecomment-460639369
