### ISSUE TITLE
Pins tend to twist when removing a female header

### ISSUE THREAD

**Issue by sakura-lain** [PiSupply/PiJuice#134]
Hi,

I noticed it's necessary to remove the battery or to beware when removing a female header from the PiJuice, because otherwise, male pins at the extremities tend to twist at the height of the battery and the plastic parts holding it. Maybe could you add a warning on the notice about this, or is it something to improve for a next version ?

Thanx.

**Comment by shawaj** [comment]
I've not seen this happening in our testing. You have to kind of "wiggle" it off like with any header though

**Comment by ChristopherRush** [comment]
As @shawaj suggested, you have to wiggle it off carefully. No other instances of this and as such nothing to document.
