### ISSUE TITLE
Sample wakeup/sleep script

### ISSUE THREAD

**Issue by sensemonster** [PiSupply/PiJuice#135]
Just been testing the script provided by @tvoverbeek and it all works apart from a couple of messages
at start.  Any pointers on how to investigate this please?

hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --debug option to see the details of our search for an access method.

**Comment by tvoverbeek** [comment]
Since you changed the PiJuice id eeprom address to 52 (to use the sense hat) the emulated ds1339 hardware clock is not automatically recognized at boot.
In this case add the following line to your /boot/config.txt:
```
dtoverlay=i2c-rtc,ds1339=1
```
and reboot.
After reboot in the output from `lsmod` you should see the rtc-ds1307 module listed.
Also `sudo hwclock --debug` should output lots of info:
```
pi@rpi-stretch-full:~ $ sudo hwclock --debug
hwclock from util-linux 2.29.2
Using the /dev interface to the clock.
Last drift adjustment done at 1521576744 seconds after 1969
Last calibration done at 1521576744 seconds after 1969
Hardware clock is on UTC time
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
/dev/rtc does not have interrupt functions. Waiting in loop for time from /dev/rtc to change
...got clock tick
Time read from Hardware Clock: 2018/05/25 13:36:40
Hw clock time : 2018/05/25 13:36:40 = 1527255400 seconds since 1969
Time since last adjustment is 5678656 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2018-05-25 15:36:39.090176+0200
pi@rpi-stretch-full:~ $
```

**Comment by sensemonster** [comment]
Aha! thanks very much Ton - I will give that a try

**Comment by sensemonster** [comment]
Yep, looking good:

xx@rpij:~ $ sudo hwclock --debug
hwclock from util-linux 2.29.2
Using the /dev interface to the clock.
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
/dev/rtc does not have interrupt functions. Waiting in loop for time from /dev/rtc to change
...got clock tick
Time read from Hardware Clock: 2018/05/25 14:17:11
Hw clock time : 2018/05/25 14:17:11 = 1527257831 seconds since 1969
Time since last adjustment is 1527257831 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2018-05-25 15:17:10.835534+0100

**Comment by shawaj** [comment]
Going to reopen this issue because I think we should document it

**Comment by sensemonster** [comment]
OK - I also plan to test with the Pi Zero form factor Enviro pHat.

**Comment by sensemonster** [comment]
Hmm, interestingly if you apply power via the rPi microUSB socket then the hwclock problem returns.  If you reboot with the power through PiJuice USB then all OK again.

**Comment by shawaj** [comment]
That sounds like it could be a bug

**Comment by sensemonster** [comment]
I wonder if anyone  else can reproduce it

**Comment by tvoverbeek** [comment]
Yes, reproduced it.
But ony when starting with both Pi and PiJuice off.
When you then apply power to the RPi it takes time before the PiJuice firmware has started and the RTC emulation is working. In the meantime the RPi has already processed the device-tree. Hence no RTC.
If you then do 'sudo reboot' it works, because the PiJuice remains powered and the firmware is up and running when the Pi boots again.

**Comment by sensemonster** [comment]
Aha! so, perhaps worth documenting this.  I am also "suspicious" of CPU temperature readings when connected through the PiJuice...... the first call to int(float(getCPUtemperature())) may be returning an incorrect value so that my attempt at calibrating some sort of near-enough actual external ambient temperature.  Then again I am polluting this thread so perhaps when I can narrow the problem a little more i will open a new issue.

**Comment by sensemonster** [comment]
Nothing further to report from me on this thread.  The CPU temp reading issue I imagined was simply down to my attempts at arithmetic being far too ambitious 8-)
