### ISSUE TITLE
Deep Sleep consumes ~140-150mA?

### ISSUE THREAD

**Issue by aixsyd** [PiSupply/PiJuice#138]
I have a PiJuice set on a wakeup timer, and I have a USB volt meter in between a big battery and the PiJuice. Its reading a near constant 140-150mA power draw. Is this normal? Seems to somewhat defeat the purpose of a deep sleep if its taking up that much juice just keeping the PiJuice battery topped off.

Is there a way to program when the PiJuice battery starts actually taking in a charge from a power source during a deep sleep? Lets say, wait until 50% battery, then start charging? Seems like it would to be a much more efficient use of external battery power than just a slow, constant trickle, no?

**Comment by ChristopherRush** [comment]
There are certain conditions that have to occur for the PiJuice to enter "deep sleep" mode. Mains power has to be removed and PiJuice must be running on the battery. PiJuice must have 5V GPIO power removed from the Raspberry PI. Deep sleep power consumption is <50mA.
