### ISSUE TITLE
Flexibile Addressing Update

### ISSUE THREAD

**Issue by mmilann** [PiSupply/PiJuice#140]
Currently PiJuice address in GUI and System task sources is hard-coded to default 0x14. If HAT address is changed from HAT configuration window PiJuice becomes non-responsive to software and only way to recover is to reset configuration by button press. In future update there should be kind of saving currently configured address (when it is changed from HAT configuration window) into config file, for example there can be two json entries:
address1:0x14
address2:0x68
Additionally there can be resolve function in case those entries in json are for some reason corrupted. Some kind of charge level / status polling in range of I2C addresses similar to i2cdetect, success will be response with correct checksum, triggered with button press next to address change entry in HAT configuration window.

**Comment by shawaj** [comment]
Sounds like a good idea for sure

**Comment by shawaj** [comment]
Closed and moved to #580 :-)
