### ISSUE TITLE
getting battery charge level (python)

### ISSUE THREAD

**Issue by sensemonster** [PiSupply/PiJuice#145]
Folks, I can't find any exposed functions for me to get this value. 

Please point me in the right direction.

**Comment by tvoverbeek** [comment]
See software README (https://github.com/PiSupply/PiJuice/tree/master/Software) 'I2C Command API' section (way down), 'PiJuiceStatus functions': `pijuice.status.GetChargeLevel()`

**Comment by sensemonster** [comment]
many thanks
