### ISSUE TITLE
Installing the Python API into a python 3 virtualenv

### ISSUE THREAD

**Issue by cmsimike** [PiSupply/PiJuice#148]
Hi,

I have already setup my system for PiJuice, and it works like a charm! I would like to install the Python API (https://github.com/PiSupply/PiJuice/blob/master/Software/README.md#i2c-command-api) into different Python 3 virtualenvs to try to avoid calling into the global python2. Is that possible?

**Comment by tvoverbeek** [comment]
The API is in the module pijuice.py (https://github.com/PiSupply/PiJuice/blob/master/Software/Source/pijuice.py) which in the standard install is in `/usr/lib/python2.7/dist-packages/pijuice.py`.
As far as I know the code should run unchanged under python 3 (caveat: have not checked this recently).
Just copy it to where your virtual environment expects dist-packages to be.

However the system service still needs to be running and for the desktop (tray app and gui app) they need to be in their non virtual environment places.

Using your own code which only uses the low level API should work in a virtual environment (provided the pijuice.py code is python 3 compatible).

**Comment by cmsimike** [comment]
Thank you!
