### ISSUE TITLE
Auto off instead of auto on?

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#15]
As raised here - http://www.recantha.co.uk/blog/?p=17790

The PiJuice automatically powers the Pi on as soon as you attach it to the Pi. Perhaps have this configurable in the software instead but have it defaulting to off as this is probably a safer way of it working

**Comment by francesco-vannini** [comment]
This is sorted with firmware V1.1_2018_01_15 and release 1.1 of the software
