### ISSUE TITLE
USB Micro power Input: WEAK - what defines "weak"?

### ISSUE THREAD

**Issue by aixsyd** [PiSupply/PiJuice#150]
Ive had some issues where the pijuice declares an input as weak, and sometimes does a constant reboot if the pijuice battery doesn't have enough juice.

I measured this cable and the draw from battery, and I get 4.85v with a battery that has a very high capacity (45,000mah) while only drawing ~400mA. 

I'm just wondering what the exact, programmed thresholds are to declare a given input as 'weak'.

**Comment by tvoverbeek** [comment]
Just for clarification, 45000mAh battery -> you are charging the PiJuice battery with an external power pack. Something like this https://www.sunjack.com/products/sunjack-laptop-battery-charger ?
4.85V seems a bit low, compared to the expected 5.0 V of the power bank.

**Comment by aixsyd** [comment]
Yes exactly. It goes down to 4.8 when connected to a solar panel, and back up to ~4.9 when not. From what I understand the lowest voltage a Pi will accept is ~4.6?

**Comment by tvoverbeek** [comment]
Still confused. How are things connected?
Power bank output to Pijuice USB input or RPi input?
PiJuice battery present or not?
How is the solar array connected?
If you are trying to charge the powerbank by the PiJuice with solar panel input,
this is not going to work very well.
The PiJuice charge circuitry only supports single cell LiIon/LiPo batteries.
All these high capacity powerbanks are multi-cell.

**Comment by shawaj** [comment]
@ChristopherRush @mmilann do we have a definition of what defines weak by any chance?

**Comment by aixsyd** [comment]
And does the PiJuice take any actions based on WEAK?

**Comment by tvoverbeek** [comment]
When power source is reported as WEAK, it means the Dynamic Power Management loop is active in the charge controller.
From the hardware README:
```
Another USB Micro power input feature is Dynamic Power Management Loop (DPM). This feature limits voltage drop at power input to configured minimum. If power source is weak and cannot supply enough current to fully charge battery plus provide loading demand than PiJuice will limit current draw to level that will prevent voltage to fall below preset DPM preventing power source crashing. This is excellent feature for non-reliable sources like energy harvesting and solar panels.
```
For the gory details see the datasheet for the chip BQ24160RGET:
https://github.com/PiSupply/PiJuice/tree/master/Hardware/BQ24160RGET.pdf
