### ISSUE TITLE
run pin on  Pi3 b+

### ISSUE THREAD

**Issue by blanchloup22** [PiSupply/PiJuice#158]
the run pin has been moves down due to the location of the new PoE added. The new location of the run pin is directly under the TC2030-IDC 6-Pin on the PJuice. I know this is not an issue that can be fixed on existing boards with out a small soldering of wires to the 2 places. Just a heads up in case it has not been noted yet.

**Comment by shawaj** [comment]
Thanks! We've actually already redesigned the board and battery surround to accommodate this change.

However we already had a bunch of boards in production so it won't be bring introduced until a future production run.

Thanks for posting this though

**Comment by blanchloup22** [comment]
Awesome! I figured this was actually the case but I wanted to say something
because I didn't see anything one it right off
