### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by KeithSloan** [PiSupply/PiJuice#16]
Have had a look at the user guide but it seems very short of info. Like I assume that I plug my power supply into the Pi-Juice rather than my Pi, but cannot see where it tells me what to do. I assume I don't have to do anything to get the system to switch to the pi-juice if there is a power failure but again I could not find this in the docs.   I give the basic documentation one star as it seems to be missing the basics and jumping into projects

**Comment by shawaj** [comment]
@KeithSloan all this stuff is a work in progress. But will be done before we ship for sure.... @francesco-vannini is working super hard on all this as we speak.

To answer your specific questions:
- You can plug into either microUSB 
- auto load-balances to keep pi powered so it stays up in power failure
