### ISSUE TITLE
Powering board in order to deploy/debug STM32 firmware only

### ISSUE THREAD

**Issue by maiorfi** [PiSupply/PiJuice#161]
Hi.

I purchased a PiJuice in order to do some lab on STM32+RPi solutions, so I got a TagConnect cable (that, by the way, is inexplicably expensive!) in order to flash/debug my STM32 custom firmware.

What is the correct way to power board without connecting it neither to RPi, nor to battery cell?

Thanks!

**Comment by ChristopherRush** [comment]
I would imagine via the on-board USB connector?

**Comment by shawaj** [comment]
Yes, or you can do it through the 5v/GND rail on the GPIO header on the top. Or a variety of other ways such as the 2 pin voltage input. Or through the 6pin header
