### ISSUE TITLE
Schematics please!

### ISSUE THREAD

**Issue by maiorfi** [PiSupply/PiJuice#165]
I know this has already been discussed before, but having schematics available would be absolutely useful in order to take advantage of all board capabilities.

After all, if it schematics isn't available due to intellectual property reasons, I think that most value resides on firmware (distributed as binary only) rather than on schematics.

Thanks.

**Comment by shawaj** [comment]
We will get this sorted shortly

**Comment by shawaj** [comment]
https://github.com/PiSupply/PiJuice/blob/master/Documentation/PiJuice_Schematic.PDF
