### ISSUE TITLE
Pijuice_cli: Changing I2C address of PiJuice and PiJuice RTC does not work

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#167]
Found this when checking issue #166.
The code for changing the I2C addresses when selecting 'Apply Changes' is commented out and contains bugs.
Will submit a PR to fix this.

**Comment by shawaj** [comment]
See also my latest comment on #166

**Comment by tvoverbeek** [comment]
Fixed for pijuice-cli in commit https://github.com/PiSupply/PiJuice/commit/c3a3e2bea459f19f78ac136426661b5d954b7ba0
