### ISSUE TITLE
Unusually high current when in battery mode

### ISSUE THREAD

**Issue by Reefkeeper** [PiSupply/PiJuice#172]
When I watch the PiJuice-CLI -> HAT status the GPIO power input seems rather high.
It says current is always higher than 1.5 A, sometimes up to 2.2 A
My Raspberry Pi 3B+ has a load of below 5 %. If I start "htop" this is the heaviest load.
Any ideas?
![pijuice-high-current](https://user-images.githubusercontent.com/18089056/42815784-b3524f82-89c8-11e8-8580-dd102d2e820c.png)

**Comment by ChristopherRush** [comment]
What sort of power supply are you using, is it regulated?

**Comment by tvoverbeek** [comment]
Looking at your status display, you are running on battery only, no power connected to either RPi or PiJuice.
I can easily get this amount of current on a 3B+ when running Chromium and displaying a dynamic website (many moving ads, etc.).

**Comment by Reefkeeper** [comment]
@ChristoperRush:The power supply is regulated (for Raspberry Pi) 5.1 V @ 2.5 A.  It has been used for months for other RPis without problems, so I suppose this is not the culprit.
@tvoverbeek: You're right, when the power is connected to the RPi the current drops to 0.4 - 0.8 A which is reasonable. 
One thought was that the current with 3.7 V (battery mode) must be higher than with the 5 V power supply, but this would only count 1.35 times higher. Still puzzling.

**Comment by Reefkeeper** [comment]
When built into the small PiJuice case the battery gets very hot (cannot keep fingers on the surface).
