### ISSUE TITLE
Communication-error

### ISSUE THREAD

**Issue by kf4jbz** [PiSupply/PiJuice#175]
Have 2 pijuices. First one worked out of the box. Updated firmware worked ok. Removed pijuice from pi for height testing of standoff’s and stacking headers to mount in smarti pi case. Removed all power sources before testing. Reinstalled pijuice got communication-error in GUI Battery, GPIO, fault.  Second pijuice same GUI communication-errors out of the box. Using same pi2. Tried reboot, software/firmware update, and reinstalls, updates, upgrades, boot loader.

**Comment by tvoverbeek** [comment]
Are you sure you mounted the PiJuice correctly on the 40-pin RPi header? I myself have a few times misplaced the PiJuice (one pin off, or even missing a complete row) which obviously resulted in communication errors (=no I2C communication). Does `i2cdetect -y 1` report the two addresses of the PiJuice (0x14 and the RTC at 0x68)?

**Comment by kf4jbz** [comment]
I am sure that both PiJuice#1 and #2 is mounted correctly.  Tried i2cdetect -y 1. Will try to send a screen shot and copy of emails from Chris at PiSupply.
Thanks

**Comment by kf4jbz** [comment]
Should I try another rpi2?  Any idea where the communication_error is coming from? i.e.,between the pijuice and the rpi, between software and pijuice, or other? The pijuice  green/blue/red leds are working.

**Comment by kf4jbz** [comment]
Screen shots 4 Communication_error
![img_0106](https://user-images.githubusercontent.com/41591947/43156536-493f649c-8f2f-11e8-9487-b382f9246fd3.jpg)
![img_0108](https://user-images.githubusercontent.com/41591947/43156543-4d3bdda0-8f2f-11e8-9ffa-c78721289279.jpg)
![img_0109](https://user-images.githubusercontent.com/41591947/43156549-51e75e10-8f2f-11e8-95a3-000ff3a81c19.jpg)
![img_0115](https://user-images.githubusercontent.com/41591947/43156553-57665cec-8f2f-11e8-8bc7-d42bb881b4a9.jpg)

**Comment by tvoverbeek** [comment]
Since i2cdetect does not show anything there is obviously no I2C communication between the RPi and the PiJuice. PiJuice software is not involved with i2cdetect.
Here is what to expect from `i2cdetect -y 1` with the PiJuice mounted:
```
pi@rpi-stretch-full:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                   
```
Have you checked if I2C is enabled after you reinstalled Raspbian?
If I remember correctly I2C is not enabled on a fresh (re)install.
On the desktop: Preferences->Raspberry Pi Configuration->Interfaces

**Comment by kf4jbz** [comment]
Changed the interface tab I2C to enable, checked I2C again no change no 14 or 68, checked pijuice settings same problem-communication_error.  Any other changes to try?

**Comment by shawaj** [comment]
Have you rebooted after turning i2c on?

**Comment by kf4jbz** [comment]
New problem-rebooted after turning on I2C-get the rpi welcome, systems-host named.service in lower left corner and a blinking cursor. Does not complete boot up.

**Comment by kf4jbz** [comment]
Third try worked system booted. Yes rebooted after changing I2C to enable and no change to i2cdetect -y 1 no 14 or 68

**Comment by kf4jbz** [comment]
And yes clicked ok before reboot

**Comment by tvoverbeek** [comment]
Starts to smell like a corrupt SD card and/or a bad power supply.
I am out of suggestions now.

**Comment by kf4jbz** [comment]
Have 2 SD cards (16 GB Adafruit NOOBS and 8 GB Mike Richards Ham Radio NOOBS card from UK) Been trying everything suggested with one card at a time and getting same result. Process of elimination leaves the pi2. Other than the pijuice comms issue everything works. Running mains 5V 2.5 amp, rpi2, WiFi, bluetooth, 7 inch touch screen.

**Comment by kf4jbz** [comment]
Thanks for your help tvoverbeek

**Comment by kf4jbz** [comment]
Got another rpi2, pijuice now works. Chris at Pisupply close my ticket. The international shipping USA to UK cost more than second rpi2 at Amazon. Don’t know what is wrong with first rpi2, but everything on it works except with the the pijuice.

**Comment by ChristopherRush** [comment]
@kf4jbz If you open a Github issue then your support ticket will get closed.

**Comment by kf4jbz** [comment]
Questions 
From the pijuice hat config battery menu-would you recommend a battery temp sensor hat compatible with pijuice hat?
Pogo pin-function?

**Comment by shawaj** [comment]
@kf4jbz - pogo pin is to restart pi when power plugged into the pi micro USB

There is already a temp sensor in the battery and on the board

**Comment by lbabaly** [comment]
Hello,

I had the very same issue, and in the end I had switch to another raspberrypi 3 B+.
Which RPI version did you have this issue?
