### ISSUE TITLE
Set RTC of PiJuice with Raspberry Pi3 

### ISSUE THREAD

**Issue by rossirm** [PiSupply/PiJuice#182]
Hi, there!
Can anyone describe me step by step (as to a dummy) how to make Raspberry set its time from the RTC of my PiJuice independently of an Internet connection. I use my Raspberry with PiJuice and SenseHat, which wanted to change the address of (EEPROM or I2C) to 0×52 from 0×50 in PiJuice software.
Thanks in advance!

**Comment by rossirm** [comment]
The issue is resolved.
https://thepihut.com/blogs/raspberry-pi-tutorials/17209332-adding-a-real-time-clock-to-your-raspberry-pi

**Comment by rossirm** [comment]
I saw that, too, thanks anyway!

**Comment by tvoverbeek** [comment]
@rossim There is an alternative way to the method outlined in the PiHut reference.
Since you changed the PiJuice address to 0x52 the RTC driver is not loaded automatically.
You can add the following line to /boot/config.txt : `dtoverlay=i2c-rtc,ds1339=1`
This will load the device module automatically at boot (but with alarm function disabled)

**Comment by rossirm** [comment]
Yes, I tried lt but there was no success maybe because of the fact that my alarm is enabled. Thanks anyway. I will keep it in mind.

**Comment by haryseldon2** [comment]
Hi,
I am interested in a step by step guide (for dummies) to make Raspberry set its time from the PiJuice RTC.
With rossirm link I don't have enough to make it work. It seems in that guide there many unnecessary steps for the specific case of PiJuice, but I'm not sure.
How did you make it work?
Thanks in advance

**Comment by tvoverbeek** [comment]
@haryseldon2 
Assuming your PiJuice has its ID-EEPROM address at 0x50. This will ensure the linux rtc module is loaded automatically at boot.

Case 1: Your Pi is connected to the internet via ethernet or wifi:
  Nothing to do. At boot the system time is set from the internet and copied to the RTC.

Case 2: Your Pi has no internet connection (which I assume is your use case).
  First make sure the RTC has the correct time:
  You can check with `sudo hwclock -r`.
  if not correct, first set the correct time on the Pi  (if needed).
  Copy the time to the RTC `sudo hwclock -w`.
  Now as long as the PiJuice has power (either from the battery or external) the RTC will keep the time.
  At boot copy the RTC time to the PI with `sudo hwclock -s` e.g. by adding this command to /etc/rc.local

**Comment by ChristopherRush** [comment]
As documented here - https://github.com/PiSupply/PiJuice/tree/master/Software#pijuice-rtc

**Comment by haryseldon2** [comment]
Thank you very much @tvoverbeek !
That's the perfect guide I needed.

**Comment by rossirm** [comment]
@tvoverbeek, may I ask you something about my set RTC time according to the PiHut reference. I followed the grneral steps from the link and added the new device with given commands there, but when I see your suggestion fro resolving my issue, I wonder if my naming of the device like ds1307 is wrong because of the fact that the PiJuice RTC device has name of ds1339.
It is important for me to know whether the naming is fatal, because I describe this work in official documentation here in Bulgaria! I will wait for your advices!
Thanks in advance!

**Comment by rossirm** [comment]
@tvoverbeek, may I ask you something about my set RTC time according to the PiHut reference. I followed the general steps from the link and added the new device with given commands there, but when I see your suggestion for resolving my issue, I wonder if my naming of the device like ds1307 is wrong because of the fact that the PiJuice RTC device has name of ds1339.
It is important for me to know whether the naming is fatal, because I describe this work in official documentation here in Bulgaria! I will wait for your advices!
Thanks in advance!

**Comment by tvoverbeek** [comment]
@rossim The difference between the ds1307 and ds1339 is that the ds1339 has an alarm function (used for waking up the host) while the ds1307 does not. The clock function itself is identical on both.
The ds1339 alarm function in the linux driver interferes with the direct programming of the PiJuice alarm function (e.g. repeated wakeup). In that case it is useful to force the use of the ds1307 driver so the RTC clock is updated from the system time automatically, especially when connected to the internet (At boot the system time is then set from the internet and copied to the RTC)

**Comment by rossirm** [comment]
Thanks!
Then why do we use this row dtoverlay=i2c-rtc,ds1339=1 in config.txt file instead of dtoverlay=i2c-rtc,ds1307=1 
Will it work so?
