### ISSUE TITLE
PiJuice alternate power supply

### ISSUE THREAD

**Issue by kf4jbz** [PiSupply/PiJuice#192]
Using PiJuice with supplied Motorola BP7X battery  Off grid use with HAM radio.  BP7X is powering RPi 2 and 7 inch touch screen.
Not enough battery life to run RPi and touchscreen for more than a few minutes.  Found alternate 5v power supply PiPower module at tindie.geppettlelectronics.com.  Issue- Is it safe to attach the Pi Power after removing the PiJuice battery to the GPIO header on top of the PiJuice without destroying the PiJuice hat?
Also removing the PiJuice hat over and over has led to communication errors  with RPi 2.

**Comment by shawaj** [comment]
Do you have a link to the product you are talking about?

**Comment by tvoverbeek** [comment]
@shawaj  See https://www.tindie.com/products/nsayer/pi-power/ and http://www.geppettoelectronics.com/2014/07/pi-power-user-guide.html for documentation.
including schematic.

**Comment by tvoverbeek** [comment]
@kf4jbz Should work, provided there is no mechanical interferece with the PiJuice.
It is equivalent to having USB power connected to the RPi. The PiPower feeds the 5V to the GPIO pins.
Although with the PiPower connected I do not see the need to use the PiJuice.

**Comment by ChristopherRush** [comment]
We now stock much larger batteries, which you can find here - https://uk.pi-supply.com/search?type=product&q=pijuice+battery
