### ISSUE TITLE
PiJuice on Kali Linux 

### ISSUE THREAD

**Issue by netvader** [PiSupply/PiJuice#194]
It´s is possible to run PiJuice on RaspberryPi with Kali Linux Image?
Unfortunately the pijuice package does not exist on their repository and the manuall installation doesn't work either.

**Comment by tvoverbeek** [comment]
@netvader Should be possible. Start with the source code and make sure you have all the python modules (and python itself) build or installed on Kali Linux.

**Comment by ChristopherRush** [comment]
We are not going to officially support this so if you require further help then reopen.
