### ISSUE TITLE
Communication error

### ISSUE THREAD

**Issue by Unfit242** [PiSupply/PiJuice#198]
Hi,

This is killing me, i can't figure it out... GUI only tells me communication error. Pijuice_cli.py starts but gives me crashes at status and LED while General only tells me device is not connected. It's connected to a raspberry pi 3b+ running raspbian.

I have't used the pogo yet, is that the issue?

If i run i2cdetect -y 1 it's blank except for horisontal row: 1, vertical row 40 which has a value of 41.

It's running and working - i'm having a wee bit of a trouble shutting it off... ;) but no gui, no 14/68 value.

**Comment by Reefkeeper** [comment]
Have experienced the same problem. Seems that you need to flash/reload the firmware.
See here and scroll down:
https://github.com/PiSupply/PiJuice/issues/105#issuecomment-404136488

**Comment by ChristopherRush** [comment]
Resolution here - #105
