### ISSUE TITLE
No dir  /home/pi/PiJuice

### ISSUE THREAD

**Issue by Pannekoek22** [PiSupply/PiJuice#200]
Dears, I have fresh Raspbian + pijuice-gui and want to use the Wakeup alarm for repeatable booting. Then I should use wakeup_enable.py script as mentioned in 'PiJuice Software README.md' but I do not find directory '/home/pi/PiJuice' on my Pi, so also no script: '/home/pi/PiJuice/Software/Test/wakeup_enable.py'. My question is how to get those data on my Pi: do I need to create the dir-tree and do I have to copy the script? I should expect that installing pijuice-gui should do this for me.

**Comment by Pannekoek22** [comment]
Yes, this did fix the issue, thanks.

**Comment by tvoverbeek** [comment]
@Pannekoek22 Ok to close this issue?

**Comment by Pannekoek22** [comment]
Ja, you can close the issue.

Germ.
________________________________
Van: Ton van Overbeek <notifications@github.com>
Verzonden: maandag 27 augustus 2018 19:05
Aan: PiSupply/PiJuice
CC: Pannekoek22; Mention
Onderwerp: Re: [PiSupply/PiJuice] No dir /home/pi/PiJuice (#200)


@Pannekoek22<https://github.com/Pannekoek22> Ok to close this issue?
