### ISSUE TITLE
minutes period documentation missing

### ISSUE THREAD

**Issue by fovea1959** [PiSupply/PiJuice#211]
I cannot find any documentation on precisely what "minutes_period" in a wakeup alarm means, vs "minutes". Can the documention be updated to explain this?

Is minutes_period for scheduling recurring wakeups, not always at the same # of minutes past the hour?

**Comment by tvoverbeek** [comment]
Minutes-period is for recurring wakeups. E.g. when set at 5 it will wakeup at 0, 5, 10, 15, ..., 55  past the hour. The largest meaningful value is 30.

**Comment by ChristopherRush** [comment]
Documented under - https://github.com/PiSupply/PiJuice/tree/master/Software#wakeup-alarm-menu
