### ISSUE TITLE
Is Wake on IO/pin change supported

### ISSUE THREAD

**Issue by RickMcConney** [PiSupply/PiJuice#224]
Hi is it possible to have the pijuice monitor one of its IO pins and wake on a change on the pin.

**Comment by tvoverbeek** [comment]
Short answer: Not currently
The two IO pins were not used by the PiJuice firmware and therefore made available to be used by the RPi.
What you request needs a firmware change. Somebody from the PiJuice team should say if this can ve placed on the wishlist for a future version of the firmware.

**Comment by ChristopherRush** [comment]
Added in Firmware v1.3 software v1.5 - f571b4384aea02c75073204db5213538a9c02fbf Documented under - https://github.com/PiSupply/PiJuice/tree/master/Software#pijuice-hat-config-io-menu
