### ISSUE TITLE
Battery test (Cut off input power)

### ISSUE THREAD

**Issue by owarek** [PiSupply/PiJuice#226]
I would like to test the "health" of inserted battery. Is there any way to cut off input power? The RPi will then act as a power load and I would measure charge level over time (let's say for 30 minutes). If the level would not drop under some border the battery should be OK. So my question is: Is there any way to cut of input power (I mean any different way than relay on input cable)?

**Comment by tvoverbeek** [comment]
Yes, in the gui/cli uncheck the 'charging enabled'. Of course there should be no power connected to the RPi usb power input.

**Comment by owarek** [comment]
Yes, I know there is the charging enabled feature. I can even change it with a python script. But if charging is disabled RPi is still powered through input cable from PiJuice. I would like to fire this test automatically once a month or so with no user interacting (ie unplugging the power cable.

**Comment by tvoverbeek** [comment]
Huh? You wanted the RPi as a power load. How else would you achieve that?
If you want to check with RPi not drawing power, shut it off and disable the 5V to the Pi (can be done in Python) and before shut down schedule a wakeup for 30 minutes later. Measurement of charge level/voltage you will then have to do externally.

**Comment by owarek** [comment]
No (I am sorry, my English is maybe not too good to explain my intention). I want to once a month execute the test. In the test there should be RPi as a power load. In my setup there is power cable connected to the PiJuice. But even if I disable the charging the RPi is still powered through the power cable, not from the battery. Am I right? So the battery still have no power load.

**Comment by tvoverbeek** [comment]
No, with charging disabled the RPi is powered by the PiJuice Battery via the 5V converter on the PiJuice board.

**Comment by owarek** [comment]
Oh, I see. Thank you very much for theese answers, have a nice day!

**Comment by owarek** [comment]
I am sorry to reopen this, but even when I disabled charging (and left the power cable inserted in the PiJuice) the RPi was drawing about 300 mA according to status for 1 hour in this state the charge level have not changed (it was still 95-96%). When I do the same with disconnected cable the charge level drops down somwhere to 75 %.

**Comment by owarek** [comment]
I do not know if it help but I have RPi Zero W with DietPi and the pogopin on PiJuice installed to the TP2.
