### ISSUE TITLE
pijuice with headless raspberry pi zero

### ISSUE THREAD

**Issue by satishgunjal** [PiSupply/PiJuice#227]
Ca i use pijuice with raspberry pi zero W in headless configuration. 
To make assembly thinner can i place pijuice at side of raspberry pi instead on top of it. In that  case which gpio pins do i have to solder . Please share the required gpio pins.

**Comment by ChristopherRush** [comment]
Checkout PiJuice Zero - https://uk.pi-supply.com/products/pijuice-zero
