### ISSUE TITLE
pyjuice.status question

### ISSUE THREAD

**Issue by neil-nn11** [PiSupply/PiJuice#229]
Hi, Can I please ask why the output of pyjuice.status toggles the order of 'error:' and 'data:' each time it is run. See screenshot of output. And can I stop it?
Kind regards

`#---tern-pi---------------------------
from pijuice import PiJuice
from datetime import datetime

pj = PiJuice(1, 0x14)
timestamp = datetime.utcnow()
BattVolts = pj.status.GetBatteryVoltage()
ChargeLevel = pj.status.GetChargeLevel()

print('------------------------------------------')
print(timestamp)
print(BattVolts)
print(ChargeLevel)
print('------------------------------------------')`

![image](https://user-images.githubusercontent.com/44431962/47422883-9d037980-d77b-11e8-9412-4e27e7363f08.png)

**Comment by ChristopherRush** [comment]
Does this work:
BattVolts = pj.status.GetBatteryVoltage()[data]
ChargeLevel = pj.status.GetChargeLevel()[data]

**Comment by neil-nn11** [comment]
Unfortunately not, I get NameError: name 'data' is not defined

**Comment by ChristopherRush** [comment]
Sorry it should have been:
 ```ChargeLevel = pj.status.GetChargeLevel()["data"]```

**Comment by neil-nn11** [comment]
That works perfectly thank you.
