### ISSUE TITLE
PiJuice update

### ISSUE THREAD

**Issue by klint-k** [PiSupply/PiJuice#23]
Hello,
This should be a simple question, I hope.  I have a RPi2 that hase been wating for the PiJuice, it has pijuce software installed on it. 
Will the software update with apt-get? (How would we know?)

Klint-K

**Comment by shawaj** [comment]
you would need to do apt-get update and then apt-get upgrade to install any updates. There are not any currently available though but when there are they will come through apt yes.

In the future we might have a beta / bleeding edge update program that you will be able to use if you want the latest (but untested) features. We are not entirely sure of the details of how that will work yet though.
