### ISSUE TITLE
Fixing pijuice-gui and firmware remote update

### ISSUE THREAD

**Issue by mougz** [PiSupply/PiJuice#237]
Hi,

* Is it possible to fix a version of pijuice-gui ?
* Is it possible to update the firmware of the PiJuice remotely ?

Thanks

**Comment by ilyastrodubtsev** [comment]
Hi, here you can find instructions for updating the firmware via the graphical interface in the paragraph "PiJuice HAT Config Firmware Menu" https://github.com/PiSupply/PiJuice/blob/master/Software/README.md

It can also be done using a terminal and pijuiceboot.
instruction here: https://github.com/PiSupply/PiJuice/blob/master/Firmware/README.md
