### ISSUE TITLE
The GUI settings aren't saved

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PiJuice#24]
The JSON file that stores the settings from the GUI is found here

`/var/lib/pijuice/pijuice_config.JSON`

If it doesn't exist create an empty one with the following contents
```
{
  "system_task": {}
}
```

**Comment by shawaj** [comment]
@tvoverbeek has experienced the same issue just FYI

**Comment by francesco-vannini** [comment]
This is now sorted
