### ISSUE TITLE
A955/A855 battery support

### ISSUE THREAD

**Issue by STrRedWolf** [PiSupply/PiJuice#241]
Is there any news on the A955/A855 3500 mAh battery that was listed on the Kickstarter's update 85?  Here's the link to refresh:

https://www.kickstarter.com/projects/pijuice/pijuice-a-portable-project-platform-for-every-rasp/posts/2191174 Scroll down.  It was in Update #85 on the Kickstarter.

**Comment by ChristopherRush** [comment]
We now stock a large range of LiPo batteries here - https://uk.pi-supply.com/search?type=product&q=pijuice+battery
