### ISSUE TITLE
Adding push button to IO1 (or IO2)

### ISSUE THREAD

**Issue by Thosty** [PiSupply/PiJuice#244]
Hi

I would like to add a push button to IO1.  IO1 has DIGITAL_IN and PULLUP as configuration. Do I need to add external resistors or are the internal resistors strong enough? I ask this because the internal resistors of the raspberry gpio pins are quite weak and I had some problems in the past adding push buttons to these pins without using external resistors.

**Comment by tvoverbeek** [comment]
For more details see the datasheet for the MCU (https://github.com/PiSupply/PiJuice/blob/master/Hardware/Datasheets/STM32F030CCT6.pdf).
In Table 46 on page 61 you will find the values for the weak internal pull-up and pull-down resistors.
Probably adding an external resistor is needed.

**Comment by Thosty** [comment]
Thank you
