### ISSUE TITLE
PiJuice dead after updating firmware?

### ISSUE THREAD

**Issue by sakura-lain** [PiSupply/PiJuice#246]
Hi,

I tried to update the PiJuice firmware through the GUI, it told me the operation was successfull but since then I cannot get my PiJuice running. I tried the solutions described here in case of COMMUNICATION_ERROR : https://github.com/PiSupply/PiJuice/issues/108 but with no success.

I think my PiJuice is somewhat detected since i2cdetect sometimes indicates 41. Anyway, the leds don't work anymore (except curiously if I touch the circuit just below them), nor the buttons. Spent several hours on this problem. Any idea?

Many thanks!

**Comment by shawaj** [comment]
It is unlikely to be totally dead. It seems like probably the firmware flashing failed.

Could you confirm the troubleshooting steps you have already taken?

**Comment by sakura-lain** [comment]
Hi!
I mainly followed the steps given [here](https://github.com/PiSupply/PiJuice/issues/105) and [there](https://github.com/PiSupply/PiJuice/issues/108) including changing dtoverlay, on 2 SD-cards with 2 different Raspbian, but with no result at all. As the buttons and leds do not work, I couldn't reproduce the reset steps with SW1 and SW3. Also read [this discussion](https://github.com/PiSupply/PiJuice/issues/175) but it didn't help.

**Comment by ilyastrodubtsev** [comment]
@sakura-lain Have you tried to update the firmware not through a gui?

**Comment by sakura-lain** [comment]
Hi again and sorry for not answering earlier, but I had much work those last months. I tried again to solve this problem these last days, but even through command line or ssh there's nothing to do, the Rasp cannot see my PiJuice anymore. Any news concerning similar problems ?

Thanks again!

**Comment by ChristopherRush** [comment]
I would suggest to follow the guidelines in the FAQ section here - https://github.com/PiSupply/PiJuice/tree/master/Firmware#faq

**Comment by sakura-lain** [comment]
Hi !

Yes ! The FAQ solution worked. Thank you !
Unfortunately my previous problem about the Pi refusing to boot or shutting down as soon as it is unplugged has come back. :-(
Anyway this issue is solved, I'll open another one for this shut down problem.
