### ISSUE TITLE
Command line stats

### ISSUE THREAD

**Issue by GaryStout** [PiSupply/PiJuice#248]
I had a question regarding command line features of the PiJuice. I was wondering if there was a way to tell from a logfile or something when the mains power went off and for how long? I recently installed the PiJuice  and it works great. This past week, while I was away from home, we had a power outage and I wanted to see exactly how long it was off so I could get an idea how long it was running entirely from the PiJuice. Thank you, Gary

**Comment by tvoverbeek** [comment]
For an idea how to do this see Frederick Vandenbosch power monitor:
http://frederickvandenbosch.be/?p=2876
You could strip all the PaPiRus stuff and only keep the logging part.

**Comment by GaryStout** [comment]
@tvoverbeek for your reply....this is very helpful and can be modified to do exactly what I need.
