### ISSUE TITLE
Raspberry Pi A+, to Pogo Pin or not to Pogo Pin?

### ISSUE THREAD

**Issue by robcee** [PiSupply/PiJuice#257]
Since the PI A+ is relatively new, I think the PiJuice documentation is out of date.

Looking at the A+ board, it looks like there is a RUN pad similar to the 3B that should line up with TP1 on the PiJuice. I haven't tested it yet because I wanted to verify this was the correct placement before going ahead with it.

**Comment by shawaj** [comment]
@ChristopherRush @tvoverbeek @mmilann have you tried this?

From pictures it looks like it's in a different place to all existing pi models but hard to tell without them in front of me

**Comment by robcee** [comment]
I will take some pictures and report back!

**Comment by shawaj** [comment]
I'll be in the office tomorrow too so will have a play

**Comment by shawaj** [comment]
@robcee the cable option would also work but makes it harder to take off in a hurry

**Comment by robcee** [comment]
@shawaj thanks for the update. I'll stay tuned for progress on the pin shorting solution as that sounds like a good solution.
I was considering adding a connector to any leads I soldered on, but obviously that's still not ideal.

**Comment by shawaj** [comment]
@robcee see the updated firmware with this functionality attached here 
[V1.3_2019_01_15-20190115T155652Z-001.zip](https://github.com/PiSupply/PiJuice/files/2760365/V1.3_2019_01_15-20190115T155652Z-001.zip)

Could you try it out?

**Comment by robcee** [comment]
> Could you try it out?

I sure can! I’ll report back.

**Comment by shawaj** [comment]
@robcee great! On the GUI, just leave the option for the pogo pin as uninstalled, and it will default to this new behaviour.

Now we can support both.

**Comment by tvoverbeek** [comment]
Running a first test with the V1.3_2019_01_15 firmware. Power connected to RPi USB.
Run pin at not installed.
After shutting down the RPi a single SW1 press wakes it up again.
So the SCL wakeup works.

**Comment by robcee** [comment]
Also confirmed. I've been using this for a couple of days now and everything seems stable.

Long press sends a SHUTDOWN_HALT to the pi and it shutsdown gracefully (still receiving power). Single press boots it back up.

Thanks for this!

**Comment by shawaj** [comment]
Great, thanks @robcee thanks for the update. Will close this now but feel free to reply back if you notice anything weird

**Comment by shawaj** [comment]
@ChristopherRush could you document this at some point?

**Comment by robcee** [comment]
@shawaj thanks Aaron. that works for me.

One question, does this mean pin 5 is unavailable with this in place?

**Comment by shawaj** [comment]
@robcee nope. Because we use pin 5 for i2c for the PiJuice to communicate with the Pi. When the PiJuice / Pi is on they are used for that

**Comment by ChristopherRush** [comment]
@shawaj @tvoverbeek Does this method also work for WakeupAlarm?

**Comment by shawaj** [comment]
It should do yes. I haven't tested it though

**Comment by tvoverbeek** [comment]
@ChristopherRush @shawaj 
Just tested it. Power connected to RPi. It works.
Note you need the 1.3 beta firmware from Jan 15, 2019:
https://github.com/PiSupply/PiJuice/blob/develop/Firmware/Beta/PiJuice-V1.3_2019_01_15.elf.binary
