### ISSUE TITLE
What is the maximum current allowed when using pijuice micro usb (without battery)?

### ISSUE THREAD

**Issue by Thosty** [PiSupply/PiJuice#259]
Hi

my Raspberry PI together with the official touchscreen and a usb device needs around 2.2A. When powering from the PI's micro usb, everthing works fine. But when I use the PiJuice's micro USB, the PI restarts sometimes. I suppose the reason for this is that the PI does not get enough power.  I had assumed that the maximum current from the PiJuice is 2.5A. So what is the maximum current allowed?

**Comment by ChristopherRush** [comment]
Theoretically 3A is the max current but more stable at 2.5A. More testing needs to be done around this.

**Comment by ChristopherRush** [comment]
2.5A as per - https://www.onsemi.com/pub/Collateral/FAN48623-D.PDF
