### ISSUE TITLE
Voltage feedback on J4 Terminals

### ISSUE THREAD

**Issue by drv2e30** [PiSupply/PiJuice#262]
So I attempted to use the J4 terminal to power the unit via a spliced USB cable. It appeared to work fine for a short while before the Windows machine or a USB bus states that a USB power surge is occurring on the bus and it then shuts the ports and the bus off. Has anyone experienced this?

**Comment by shawaj** [comment]
@drv2e30 are you saying that you are trying to do this from a USB port on another machine? i.e. you are using the USB port on a windows PC to try and charge pijuice?

**Comment by drv2e30** [comment]
Yes, I'm using a USB cable with a USB A connector attached to a windows PC with the other end of the cable cut off and a positive and negative connection attached to the pins on J4.

**Comment by shawaj** [comment]
@drv2e30 and you are getting the error on the windows PC about the power surge?

**Comment by drv2e30** [comment]
I get this error on the Windows pc. Ive also tried to use a usb bus that would shut the port off once I connected the pi juice.

**Comment by ChristopherRush** [comment]
I'm guessing the solution here is not to use power from a PC/Laptop. I'm would assume there might be a current limit too 500mA?. Open if you disagree.
