### ISSUE TITLE
PiJuice Firmware Image

### ISSUE THREAD

**Issue by tresoft** [PiSupply/PiJuice#266]
Hello,

According to the appropriate instructions, the source code of the master branch was compiled and an image file was created in binary format. However, the size of the image does not match any of the different variants of the firmware of V1.0, V1.1 or V1.2.

From which version of the firmware is the source code in the master branch? 

Greetings
Stephan

![pijuice-image-sizes](https://user-images.githubusercontent.com/10061072/50932366-a55b7e80-1465-11e9-87ce-d91f37768872.PNG)

**Comment by shawaj** [comment]
@tresoft there are 3 different v1.0s and two different v1.2s. Did you check them all?

And what method did you follow to make the binary?

**Comment by tresoft** [comment]
@shawaj allV1.0 version images are smaller than the custom image and all other V1.1 and v1.2 images are greater. 

I used the latest TrueStudio from Atollic to build with the enabled speed optimization and binary output . All in release mode. The project skeleton I have created with STM32CubeMX and than the source files with PiJuice sources overidden…

**Comment by shawaj** [comment]
Did you do it in the same way as the reader suggests?

**Comment by tresoft** [comment]
Yes. Do other tweaks need to be activated?

**Comment by shawaj** [comment]
Let me check with @mmilann our engineer and get back to you.

Is there a particular reason you want to build it in this way?

**Comment by tresoft** [comment]
I would like to make a few minor adjustments so I can better integrate PiJuice into my projects. If all this fits, I can also use this hardware commercially ...

**Comment by shawaj** [comment]
Ok sure thing, no problem at all

**Comment by tresoft** [comment]
Here are some screenshots with the settings in Atollics TrueStudio for assembler, compiler, linker and others: 

![pijuice-atollic-settings-1-as](https://user-images.githubusercontent.com/10061072/50995814-7b1ac700-1520-11e9-9e59-2458b03ce9cf.PNG)

![pijuice-atollic-settings-2-cc](https://user-images.githubusercontent.com/10061072/50995842-97b6ff00-1520-11e9-958f-3b5ad7872c2a.PNG)

![pijuice-atollic-settings-3-cl](https://user-images.githubusercontent.com/10061072/50995850-9be31c80-1520-11e9-98c5-f3ca8773e0a4.PNG)

![pijuice-atollic-settings-3-ot](https://user-images.githubusercontent.com/10061072/50995856-a0a7d080-1520-11e9-9358-eb8262d961db.PNG)

**Comment by shawaj** [comment]
@tresoft have you tried the sources and binaries from the beta v1.3 firmwares here? https://github.com/PiSupply/PiJuice/tree/master/Firmware/Beta

**Comment by shawaj** [comment]
[Change log.txt](https://github.com/PiSupply/PiJuice/files/2760493/Change.log.txt)
CHange log for newest firmware
