### ISSUE TITLE
Develop branch: Milan's changes for the new Firmware 1.3 features disappeared

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#272]
@shawaj Aaron, your commit https://github.com/PiSupply/PiJuice/commit/ed473770f5813ea0cb1b685a288803f9649de9e6 overwrote @mmilann  changes to pijuice.py and pijuice_gui.py for the new 1.3 Firmware features.
I'll try to restore them before I can test the new features (wakeup via IO2, chemistry and temperature info in gui, etc.)

**Comment by shawaj** [comment]
Maybe @ilyastrodubtsev can help with this as well
