### ISSUE TITLE
Question about System Events|No Power

### ISSUE THREAD

**Issue by richardquint** [PiSupply/PiJuice#273]
The System Events|No Power is triggered when power to the MicroUSB connected on the PiJuice is removed, but when power is being supplied directly to the Pi and is cut the event is not triggered.  I currently have my PiJuice updated with the 1.2 firmware and am using version 1.4 of the software.

**Comment by richardquint** [comment]
I've been experimenting with settings and I'm afraid I may be having a problem with intermittent errors with the RTC on the PiJuice.  Whenever I boot the Pi, shut it down or have power cut off I have simple scripts to record the time according to both the system clock and the RTC.  My obervation may be related to the fact that sometimes the RTC clock can be accessed using`sudo hwclock -r` and other times the command fails.

**Comment by shawaj** [comment]
The RTC is an emulated RTC that's inside the ST Micro processor.

What Pi are you using? Have you definitely got a good connection?

**Comment by richardquint** [comment]
It's a Pi3B. AFIK the connection between the PiJuice and the Pi is solid.  I have an Adafruit PiTFT on top of the PiJuice and it's working with no problems.

**Comment by klint-k** [comment]
i was having problems with the reboot #270 
sudo hwclock -r not working also.

**Comment by shawaj** [comment]
Does the display use i2c?

Perhaps it's interfering with the RTC

**Comment by richardquint** [comment]
I had that problem a while back.  I have switched the ID EEPROM address to 52 and I have had no problems until now.  Could it be related to having just upgraded to version 1.4 of the software?  I still have an SD with the unupdated system with the old 1.3 on it.

**Comment by richardquint** [comment]
I'm still experimenting.  It's not certain, but if I start or reboot the Pi with power to the PiJuice's micoUSB then reading the RTC works---sometimes if I boot with power only from the PiJuice's battery  reading the RTC fails.

**Comment by klint-k** [comment]
sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by richardquint** [comment]
Yes, this is part of the problem.  When the RTC is accessible 
`pi@Mrs-Lovett:~ $ sudo i2cdetect -y 1`
     `      0 1 2 3 4 5 6 7 8 9 a b c d e f`
`00: -- -- -- -- -- -- -- -- -- -- -- -- --`
`10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- --`
`20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --`
`70: -- -- -- -- -- -- -- --`
`pi@Mrs-Lovett:~ $ sudo hwclock -r`
`2019-01-17 19:43:55.965158-0800`
and when it isn't
`pi@Mrs-Lovett:~ $ sudo i2cdetect -y 1`
     `      0 1 2 3 4 5 6 7 8 9 a b c d e f`
`00: -- -- -- -- -- -- -- -- -- -- -- -- --`
`10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- --`
`20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --`
`60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --`
`70: -- -- -- -- -- -- -- --`
`pi@Mrs-Lovett:~ $ sudo hwclock -r`
`hwclock: Cannot access the Hardware Clock via any known method.`
`hwclock: Use the --debug option to see the details of our search for an access method.`

**Comment by tvoverbeek** [comment]
When you have the PiJuice eeprom address at 0x52, the ds1339 RTC os module will not be loaded.
Hence the '68' instead of 'UU' in the i2cdetect output.
With no driver loaded the hwclock command does not work.
If you want to set the PiJuice RTC from the system clock there are 2 solutions:
1) Set the RTC using the PiJuice API. Here is an example function:
```
def SetRTCTime():
        t = datetime.datetime.utcnow()
        pijuice.rtcAlarm.SetTime({'second':t.second, 'minute':t.minute, 'hour':t.hour, 'weekday':(t.weekday()+1) % 7 + 1,
                                  'day':t.day, 'month':t.month, 'year':t.year, 'subsecond':t.microsecond//1000000})
```
2) Load the ds1307 driver at boot:
In /boot/config.txt add the line `dtoverlay=i2c-rtc,ds1307`.
The ds1307 has the same commands w.r.t. time as the ds1339, however it does not have an alarm function. Therefore no risk of resetting the wakeup-enabled flag by the os.
After a reboot the i2cdetect output should show 'UU' again in position 68.
You can then use the hwclock command again.

**Comment by richardquint** [comment]
Thanks @tvoverbeek.  My problem is inconsistent behaviour of the RTC. Back when you helped me with issue #191 I added the line `dtoverlay=i2c-rtc,ds1339` to my config.txt and everything worked.  Now after upgrading to version 1.4 of the software (but that may just be a coincidence) I have the situation that sometimes the RTC is accessible and sometimes it is not.  It seems to be dependent on the power in arrangement when the the Pi is booted.  There are multiple possibilities, among them are: 

1) the Pi is off, power is being applied to the MicroUSB port on the PiJuice and I start the Pi using a button on the PiJuice,

2) the Pi is off, power is not being applied and I start the Pi using a button on the PiJuice,

3) the Pi is on, power is being applied to the MicroUSB port on the PiJuice and I reboot the Pi,

4) the Pi is on, power is not being applied and I reboot the Pi,

5) the Pi is off and power is applied to the MicroUSB port,

6) the Pi is on, power is being applied to the MicroUSB port on the Pi and I reboot the Pi.

I'm still working through all the permuations and trying them repeatedly, but it seems in cases 1) and 3) I usually get the RTC working.  In 2) and 4), no access to the RTC.  The other two seem inconsistent.  I'll also try your suggestion to load `ds1307` instead of `ds1339`.

It's a Pi3B using a power source that provides 2.5A at 5V. The only attachment other than the PiTFT is a USB dongle for a wireless keyboard w/ touchscreen.  Wireless is on, bluetooth is turned off.

**Comment by richardquint** [comment]
I've just changed my SD card to one that has version 1.3.3 of the PiJuice software and I still have the problem. It's inconsistent whether I have access or not to the RTC.  I have had both behaviours on trying case 2).

**Comment by richardquint** [comment]
Worth a try.  I'll try just each case a few times with different wait times.  It will probably take a while to get through all of them between other chores.

**Comment by tvoverbeek** [comment]
@richardquint Maybe a stupid question. Is there a battery in the PiJuice?
Remember the PiJuice RTC is simulated, without a battery and no power it cannot hold the time.
Also eeprom address 0x50 or 0x52?

**Comment by richardquint** [comment]
Yes, the original battery supplied with the PiJuice.  included in my test cases is cold booting and rebooting with no external power applied.  As @tvoverbeek recommended, I had changed the address to 0x52 last summer.

**Comment by tvoverbeek** [comment]
@richardquint With the line `dtoverlay=i2c-rtc,ds1339` in /boot/config.txt you get the same behavior as with the eeprom address at 0x50.
With the eeprom at 0x52 it is better to use `dtoverlay=i2c-rtc,ds1307`. This gives the same behavior as with the ds1339 w.r.t. time (e.g. hardwareclock read/write), but it does not have an alarm. Hence any syncing of the RTC from the system clock by timesyncd/ntp does not rest the wakeup flag.
What exactly is the inconsistent RTC behavior?
Does it lose the time, or problems with waking up, or ... ?
Could you provide some more details? That may give me a hint about the cause of the problem.

**Comment by tvoverbeek** [comment]
The startup script is run from cron (@reboot entry)?
These cron jobs are executed very early mostly before the i2c driver is loaded.
Since the PiJuice RTC is accessed via i2c 'hwclock -r' fails.
In your startup script you could check for the existence of `/dev/rtc` and then run hwclock -r.

It is known there is a discrepancy between the charge level indication between charging and using the battery. When on battery the charge level indicated can be significantly lower than when charging.
Also a Pi3B+ is a relatively heavy load for the BP7X which exaggerates the difference in charge level between charging and using the battery.

Are you sure your power supply is OK? In your log file there is an instance of powerInput: BAD.

**Comment by richardquint** [comment]
Still playing---ran a TotalShutdown with no external power applied, then restarted and this time it worked.  Before powering off I checked
`pi@Mrs-Lovett:~ $ lsmod | grep i2c`
`i2c_bcm2835            16384  3`
`i2c_dev                16384  6`
`pi@Mrs-Lovett:~ $ ls /dev | grep i2c`
`i2c-1`
which is the same as I get when the RTC is accessible.

**Comment by tvoverbeek** [comment]
Just to get some more infor. In your wait part could you add similar code to wait for /dev/i2c-1 before waiting for /dev/rtc?
Then we know if the i2c module did not get loaded causing the rtv not to show up.
Right now I do not have any more suggestions.
By the way systemd starts rc.local after the network target is reached.

**Comment by richardquint** [comment]
I've added tests for `/dev/i2c-1` and `/dev/rtc` to my `/etc/rc.local` (attached) to run before the Python script for reporting the status of the battery and power inputs. After 2019 January 21 10:20 am I added the sleep command to see if that might give enough time for the rtc module to be loaded. 

I'm also attaching the latest entries in OnAndOff. When I have power applied, everything works as expected, when only using the PiJuice power, sometimes the rtc module isn't loaded and sometimes it is.  I've also had booting just hang (when no power is applied, but I can't see a pattern as to how much juice is left in the battery).

I think the powerInPut: BAD occurs when the input from the mains is cut off and the Pi is reporting that it has been cut off; so in fact it should be saying NOT_PRESENT.

[OnAndOff.txt](https://github.com/PiSupply/PiJuice/files/2780171/OnAndOff.txt)
[rc.local.txt](https://github.com/PiSupply/PiJuice/files/2780172/rc.local.txt)

**Comment by tvoverbeek** [comment]
It seems most occurences of the rtc not working are with battery levels under about 50% with no power connected. Maybe it is a power problem with the battery at lower charge levels.
Do you have an other battery to test with?

**Comment by richardquint** [comment]
It's a theory, but look at the latest results.  I'll rummage around and see if I have one.  I can always get one quickly using Amazon.
[Recent_OnAndOff.txt](https://github.com/PiSupply/PiJuice/files/2780365/Recent_OnAndOff.txt)

**Comment by richardquint** [comment]
Just to see if there was something I had installed that might be causing a conflict, I flashed a SD card with the latest version of Raspbian Stretch.  Did a `sudo apt update`, installed `pijuice-base` and `pijuice-gui`, both version 1.4, and then ran the latest version of the Adafruit PiTFT install script.  This is the minimum of what I want installed.  As before, when external power is applied when I boot the simulated RTC works correctly, however here's an example of what happens when there is no external power applied.


After a reboot, no external power applied

`pi@Babette:~ $ sudo hwclock -r`
`2019-01-24 13:13:33.248254-0800`
`pi@Babette:~ $ ls /dev | grep rtc`
`rtc`
`rtc0`
`pi@Babette:~ $ ls /dev | grep i2c`
`i2c-1`
`pi@Babette:~ $ lsmod | grep rtc`
`rtc_ds1307             24576  0`
`hwmon                  16384  1 rtc_ds1307`
`pi@Babette:~ $ lsmod | grep i2c`
`i2c_bcm2835            16384  2`
`i2c_dev                16384  4`

A few minutes later after another reboot

`pi@Babette:~ $ sudo hwclock -r`
`hwclock: Cannot access the Hardware Clock via any known method.`
`hwclock: Use the --debug option to see the details of our search for an access method.`
`pi@Babette:~ $ ls /dev | grep rtc`
`pi@Babette:~ $ ls /dev | grep i2c`
`i2c-1`
`pi@Babette:~ $ lsmod | grep rtc`
`rtc_ds1307             24576  0`
`hwmon                  16384  1 rtc_ds1307`
`pi@Babette:~ $ lsmod | grep i2c`
`i2c_bcm2835            16384  2`
`i2c_dev                16384  4`
`pi@Babette:~ $ date`
`Thu Jan 24 13:21:57 PST 2019`
`pi@Babette:~ $` 

I used `date` to show the time since the Pi's system clock is updated over my internet connection.  I intend to use the Pi with PiJuice and PiTFT is situations without access to mains power and no internet connection.

**Comment by shawaj** [comment]
I wonder if maybe the firmware has somehow become corrupted.

Can you update to the latest v1.3 firmware?

**Comment by richardquint** [comment]
I'm assuming you mean `PiJuice-V1.3_beta_2018_09_13.elf.binary` using `pijuiceboot`.  If that's right, I'll give it a go.

**Comment by shawaj** [comment]
This is the latest one - https://github.com/PiSupply/PiJuice/blob/develop/Firmware/Beta/PiJuice-V1.3_2019_01_15.elf.binary

You should be able to download it and update using the GUI. But you can also use the pijuiceboot method here https://github.com/PiSupply/PiJuice/blob/develop/Firmware/README.md

**Comment by richardquint** [comment]
![screenshot of babette 0 at 2019-01-24 17 48 05](https://user-images.githubusercontent.com/39503532/51720269-c5607580-2001-11e9-87f9-8082b77e26b7.png)
![screenshot of babette 0 at 2019-01-24 17 47 15](https://user-images.githubusercontent.com/39503532/51720271-c5607580-2001-11e9-85dd-aa2b3f957122.png)

Updating the firmware went smoothly. I'm attaching screenshots of PiJuice HAT Configuration|General and PiJuice HAT Configuration|Firmware.  However I still get the same behaviour when I boot with no externally applied power.


`pi@Babette:~ $ sudo hwclock -r`
`hwclock: Cannot access the Hardware Clock via any known method.`
`hwclock: Use the --debug option to see the details of our search for an access method.`
`pi@Babette:~ $ lsmod | grep rtc`
`rtc_ds1307             24576  0`
`hwmon                  16384  1 rtc_ds1307`
`pi@Babette:~ $ lsmod | grep i2c`
`i2c_bcm2835            16384  2`
`i2c_dev                16384  4`
`pi@Babette:~ $ ls /dev | grep rtc`
`pi@Babette:~ $ ls /dev | grep i2c`
`i2c-1`

And if I have power applied to the PiJuice's microUSB port I get

``pi@Babette:~ $ sudo hwclock -r`
`2019-01-24 17:53:35.879887-0800`
`pi@Babette:~ $ lsmod | grep rtc`
`rtc_ds1307             24576  0`
`hwmon                  16384  1 rtc_ds1307`
`pi@Babette:~ $ lsmod | grep i2c`
`i2c_bcm2835            16384  2`
`i2c_dev                16384  4`
`pi@Babette:~ $ ls /dev | grep rtc`
`rtc`
`rtc0` 
`pi@Babette:~ $ ls /dev | grep i2c`
`i2c-1`
`pi@Babette:~ $`

For some reason `/dev/rtc` and `/dev/rtc0` are not created (sometimes) when there is no external power.

**Comment by tvoverbeek** [comment]
@richardquint Issue #270 is probably different since it is not using raspbian but a retropie image.

I tried to reproduce your problem since I have an Adafruit 2.8" capacitive touch PiTFT.
I put it on top of the PiJuice and installed the Adafruit software using their easy install script .
I started with a full battery and then disconnected external power. I stressed the system by displaying the 5 minute Bugs Bunny movie which uses mplayer and displays on the TFT via fbcp.
Doing a sequence of reboots alternating with full shutdown/power up from SW1.
Every time after boot until the RPi went dead because of low power the RTC was showing the correct time with `sudo hwclock -r`.
SInce I used the Adafruit HAT I put the PiJuice eeprom address on 0x52 (not to interfere with the eeprom on the TFT hat) and added the line `dtoverlay-i2c-rtc,ds1339` to /boot/config.txt
All the same as you.
Noticed my Pi 3b+ current consumption varied between 1 and 1.5A.

Which TFT are you using? As far as I know the ones with a resistive touchscreen also use I2C for the touch screen.
Mayne also the dmesg output could give some clues when the rtc doesnot seem to be available after boot.

**Comment by tvoverbeek** [comment]
@richardquint Your TFT does not use I2C. Also the touch controller uses SPI. However I am assuming since it is a higher resolution than mine it will use more power.

The `Unsupported ohm value 0 in dt` you can ignore, I get the same when everything works.
The `rtc-ds1307: probe of 1-0068 failed with error -121` means the rtc-ds1307 module cannot initialise the clock. error -121 = remote i/o error.
Then 12 sec later you get a timeout on an i2c transfer, probably to the RTC.
With the second failure it obviously succeeded in probing the RTC, but you get the same i2c transfer timeout at about the same time (probably timesyncd trying to sync the time to the RTC).

The I2C bus uses pull-up resistors to have the bus high. The devices have to drive the bus to 0.
I am just wondering if (when battery is low) there is only marginal power to pull the bus down, resulting in transfer failures.

Can you run your tests without the TFT?
Just to know if the extra power load has anything to do with this.

I am assuming you supply 5V power to the PiJuice USB.
You could also try to connect the power to the RPi USB. With the beta 1.3 firmware wakeup also works when power is connected to the RPi. No pogo pin needed.

**Comment by richardquint** [comment]
I'll continue to experiment.  I'm loath to pull the PiTFT off because it is very easy to break part of the flimsy connector (I've already lost the use of the touch capability on another identical screen doing that), but I will try it with the backlight turned off, using `ssh` to log in and record the behaviour. My first post with the outputs from `dmesg` was when I had fully charged the battery, turned off the external source, and started running reboots---and that is when I had both a successfull boot and a failure.  The next post was after running the Pi for two hours with the battery down to 24%.  Applying power to the Pi directly isn't really relevant since my need is to be able to boot and reboot the Pi when external power and an internet connection aren't avaiiable.

**Comment by richardquint** [comment]
Following up on the seemingly random behaviour of my PiJuice, I've tried a few experiments. I've used the ideas in `pijuicetest.py` to log some of the values reported by the PiJuice whenever I boot or shutdown to see what might be different when the RTC is recognized or not (indicated by the entry in dmesg of either `rtc-ds1307 1-0068: registered as rtc0` or `rtc-ds1307: probe of 1-0068 failed with error -121`). Looking at the attached file 
[OnAndOff.txt](https://github.com/PiSupply/PiJuice/files/2818397/OnAndOff.txt)
 from 2019 January 29, generated by running the Pi with a nearly full battery with no external power applied and using a cron job that rebooted the Pi every 5 minutes.  The Pi had been running for a while, so the battery temperature was already at 45°C, and I ran it for a period of one hour.  I can't see any pattern, but half the time the RTC is recognized and half the time it isn't.

Have I missed any thing I can test for?  Is a value of slightly under 4V normal for the BP7X provided with the PiJuice? Another question, what is Battery Current measuring?

**Comment by tvoverbeek** [comment]
@richardquint Are you by any chance using a 'cron @reboot' job to get the data after boot?
These jobs run very early in the boot sequence even before the i2c driver is loaded.
Same might be true for scripts run from /etc/rc.local
Since systemd executes jobs in parallel you could have a race condition between your job and the i2c driver and device loading. Since your PiJuice data reporting comes later there the i2c communication is working.
If so, could you add  a delay to your script to see if this improves the situation.
You could also look at the (copious) output of journalctl after boot to see when what was started.

**Comment by richardquint** [comment]
My cron job calls a script when the Pi is running to record the data and then its final line is simply `sudo reboot`.  Whenever the Pi starts up I have added just the one line 
`su - pi -c /home/pi/.local/bin/RecordBoot &` d to `rc.local` where `RecordBoot` is a script to generate the entries in `OnAndOff` (just like the first part of my shutdown script).  I've added a `sleep 15s` to `rc.local` before it calls my script. However, looking at the output from `dmesg`, the events associated with `i2c` and `rtc` all occur at about the same time (early in the boot)  whether or not there is success or failure, but now I'm getting COMMUNICATION_ERROR reports from the PiJuice on boot. After reported COMMUNICATION_ERROR, in the time for me to run pijuice_cli, it opens with no errors reported.

After the reboot at 12:45 the Pi hung during the reboot, I applied external power to the PiJuice's microUSB port and started the Pi with a button press.  Now as before, with external power applied at 12:50 everything works smoothly.  After removing the external power at 13:53 , back to having problems. Problems only occur when running solely on battery power.  What should the normal value for battery voltage be? If that's the problem I'll order a replacement battery and see what happens.

Now for something different---slightly stranger behaviour at 14:05, the RTC is recognized and then `dmesg` shows some read errors from the RTC.
[OnAndOff.txt](https://github.com/PiSupply/PiJuice/files/2819230/OnAndOff.txt)

**Comment by tvoverbeek** [comment]
@richardquint I am out of ideas now.
Something is obviously wrong with the i2c communication when on battery power.
Could be either the PiJuice board itself or the battery.
Suggest you contact PiSupply (or your supplier) for a replacement PiJuice. Refer to this issue.

**Comment by shawaj** [comment]
If you ordered from us (Pi Supply) then just let me know your order number and I'll sort the rest

**Comment by shawaj** [comment]
And thanks to you both for the extensive testing

**Comment by richardquint** [comment]
Thanks @shawaj. My order number was PS-65290-UK, but before you do anything let me try swapping in a replacement battery I bought on Amazon.  I've been reluctant to pull off the PiTFT because its connectors are so fragile, but since I'd have to pull it to replace the PiJuice, I might as well try the new battery first.  I may be a couple days before I get to it so wait until I report on my efforts.  Is it safe to swap batteries while the PiJuice is still sitting on the Pi?

**Comment by shawaj** [comment]
Yeah that's fine to do that. Best not to do it when it's on but still shouldn't cause any major issues.

**Comment by bleauge** [comment]
Hello,
How to read RTCTime of PiJuice Hat, for example:
pijuice.rtcTime.GetTime

**Comment by tvoverbeek** [comment]
Here an example:
```
pi@rpi-pijuice:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pijuice import PiJuice
>>> pj=PiJuice(1,0x14)
>>> pj.rtcAlarm.GetTime()
{'error': 'NO_ERROR', 'data': {'minute': 30, 'hour': 13, 'day': 16, 'second': 19, 'storeoperation': False, 'weekday': 3, 'subsecond': 0, 'daylightsaving': 'NONE', 'month': 4, 'year': 2019}}
>>> 
pi@rpi-pijuice:~ $
```
RTC time is in UTC. Here Tuesday April 16, 2019 13:30:19

**Comment by bleauge** [comment]
Thank you

**Comment by ChristopherRush** [comment]
I believe this to be resolved, if not then reopen.
