### ISSUE TITLE
How to work with pijuice API in python2 ?

### ISSUE THREAD

**Issue by mougz** [PiSupply/PiJuice#274]
Hi,

Our pijuice-gui and pijuice-base packages were updated to 1.4. However, we were using the pijuice API features in python2 script. 

I have understood that v1.4 is python3 only.  I try to downgrade pijuice-gui to 1.3.3 but it did not work.
(`sudo apt-get install pijuice-gui=1.3.3`). We need to work on pyhton2 because our scripts use modules that run on python2 only (and the pijuice module is the only one to run exclusively on python3)

Can you make the 1.3.3 version available on apt-get ? Or there is another solution ?

Thanks

**Comment by shawaj** [comment]
V1.3.3 Deb is here https://github.com/PiSupply/PiJuice/tree/master/Software/Install

**Comment by mougz** [comment]
Oh thanks @tvoverbeek  I just saw your comment. Will try that :)
