### ISSUE TITLE
PiJuice light version on headless(Raspbian Strech Lite) error

### ISSUE THREAD

**Issue by satishgunjal** [PiSupply/PiJuice#275]
received following error while installing the PiJuice light version on RPI 3B+ with Raspbian Strech Lite OS.

> Creating user pijuice
Adding user pijuice to group i2c
Adding user pi to group pijuice
settings file created
Setting ownership and permissions
Enabling I2C
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.14.50-v7+/modules.dep.bin'
modprobe: FATAL: Module i2c-dev not found in directory /lib/modules/4.14.50-v7+

**Comment by tvoverbeek** [comment]
@satishgunjal Something is wrong with your raspbian install.
First it seems you are using kernel 4.14.50. Current one is 4.14.79
What does 'uname -a' say?
If you are actually using 4.14.50 then the file modules.dep.bin should exist in /lib/modules/4.14.50-v7+
Anyway without the i2c-dev module you cannot communicate with the PiJuice and nothing will work.
Suggest to start with a fresh install of raspbian. Run 'sudo apt-get update' followed by 'sudo apt-get upgrade' to be sure you are up-to-date, then install pijuice-base.
