### ISSUE TITLE
Cannot open pijuice_cli

### ISSUE THREAD

**Issue by udimu** [PiSupply/PiJuice#279]
Hi.
If I try to start _pijuice_cli_ I get an error:

```
No PiJuice found or Failed to use I2C bus. Check if I2C is enabled.
```

![pijuice_cli_error](https://user-images.githubusercontent.com/30128180/52163685-c2424500-26e5-11e9-9906-2160fe0584c3.png)

I run it as a root (with sudo) and as normal user and always get the same error.

```
ls -la /dev/i2c-1 
crw-rw---- 1 root i2c 89, 1 lut  1 23:12 /dev/i2c-1
```

```
sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```
How should I set permissions to make everything work properly ?

BTW. When I start _pijuice_cli.py_ with command:
```
sudo python3 pijuice_cli.py
```
everything works fine.

**Comment by tvoverbeek** [comment]
Starting with package version 1.4 do not start pijuice_cli.py directly. Start the cli with pijuice_cli (no extension). This starts the python3 interpreter as user pijuice to run the pijuice_cli script.
Apologies for the confusion. The doc has not been updated yet to reflect this.

**Comment by udimu** [comment]
But when I start pijuice_cli I get following error:
```
No PiJuice found or Failed to use I2C bus. Check if I2C is enabled.
```

should I add pijuice user to i2c group?

**Comment by tvoverbeek** [comment]
@udimu If the pijuice-base 1.4 package is properly installed, the user pijuice is created (if it does not exist) and added to the i2c group.
But it is worth to check /etc/group if pijuice belongs to group i2c.
Could you run the following in a terminal (or via ssh):
- start the python3 interpreter
- then the following commands:
```
    from pijuice import Pijuice
    pj=PiJuice(1,0x14)
```
and see if this reports any errors.
pijuice_cli.py does this at the start and if it does not succeed you get the error message you are seeing.
First run as normal user (pi). if that works also try the same with
`sudo -u pijuice python3`

**Comment by udimu** [comment]
1. pijuice user exists and belongs to i2c group

```
cat /etc/group | grep pijuice
i2c:x:112:pijuice,osmc,root
pijuice:x:1001:osmc
```
2. I able to execute following command (as user osmc) without any errors.

```
from pijuice import PiJuice
pj=PiJuice(1,0x14)
```
3. When I run last command I get following error:

```
sudo -u pijuice python3
[sudo] password for osmc: 
Sorry, user osmc is not allowed to execute '/usr/bin/python3' as pijuice on osmc
```
I solve this problem by adding following line to */etc/sudoers* file

```
osmc ALL=(pijuice) ALL
```

Now I able to start pijuice_cli as normal user.

BTW:
I have [osmc](https://osmc.tv) installed on my raspberry pi.

**Comment by tvoverbeek** [comment]
@udimu Yes, the setup procedure in the pijuice-base package assumes the default user (normally pi on Raspbian) has the privilege to sudo to another user (here pijuice).
On Raspbian the 'pi' user has this privilege by default.
@ChristopherRush Should we document this for osmc/kodi installations?

**Comment by ChristopherRush** [comment]
@tvoverbeek Yes, will document then close.

**Comment by ChristopherRush** [comment]
936e7c1bd307fd86aa74eac10abfe4d0d6004e1d
