### ISSUE TITLE
settings on "system task" menu dont save

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#28]
On / off settings for the items on this menu save, but the expire period, trigger level, and two threshold figures do not save in the JSON?

See [here](https://github.com/PiSupply/PiJuice/tree/master/Software#system-task-menu) for the menu pictures.

**Comment by shawaj** [comment]
@francesco-vannini @DenisKhrutsky think this issue is fixed now, based on recent updates. Guessing we can close?

**Comment by francesco-vannini** [comment]
Yes, correct
