### ISSUE TITLE
pijuice_cli - battery status oscillates a lot

### ISSUE THREAD

**Issue by cjdcordeiro** [PiSupply/PiJuice#280]
Hi,

I'm testing my new pijuice hat with a pijuice solar panel (12W), on a RPi 3B+ with Raspbian Stretch lite installed. I'm measuring the battery status through the CLI and for some reason, **the percentage value jumps all over**. I've seen it going from 28% to 75% within seconds for example...I'm not sure how trustworthy this is and I wonder whether I'm misreading these values or the hardware is faulty.

Any hints?
Thanks

**Comment by shawaj** [comment]
This is a known issue with the battery fuel gauge chip.

But later versions of the firmware for PiJuice (discussed here https://github.com/PiSupply/PiJuice/issues/249) have made improvements to this?

Thanks

**Comment by cjdcordeiro** [comment]
thanks I'll follow that thread
