### ISSUE TITLE
complete poweroff after shutdown

### ISSUE THREAD

**Issue by satishgunjal** [PiSupply/PiJuice#282]
if i shutdown the RPI by pressing SW1 switch. RPI shutdowns but RPI and pijuice 'RED' leds will remain on.  Ideally both the led's should be off as per below configuration.

![1](https://user-images.githubusercontent.com/16061972/52338513-a1088e00-2a30-11e9-82e7-b846f133e3f3.JPG)

![2](https://user-images.githubusercontent.com/16061972/52338744-43287600-2a31-11e9-98ea-ea9107208de1.JPG)

**Comment by tvoverbeek** [comment]
@satishgunjal On the system events page you can set a function which runs **after** the event has triggered.
If you want to trigger SYS_FUNC_HALT_POW_OFF from e.g. SW1 you have to specify it on the Buttons page.
