### ISSUE TITLE
how do pijuice calculate the battery percentage

### ISSUE THREAD

**Issue by satishgunjal** [PiSupply/PiJuice#284]
how is it possible to have 4% battery with 3.6V. Normal safe cutoff voltage for lipo is 3.3V.
Is it do with BP7X battery??
![3](https://user-images.githubusercontent.com/16061972/52490206-34d18a00-2bea-11e9-9f5a-0014ea634f27.JPG)

I have configured the pijuice to shutdown RPI when battery is at 5%.  Pijuice do shutdown the rpi at 5% but when I reconnect the power it shows battery 99 to 100% ... how is it possible??
![4](https://user-images.githubusercontent.com/16061972/52490853-b8d84180-2beb-11e9-9a2d-ec868667b718.JPG)

**Comment by ChristopherRush** [comment]
@satishgunjal This issue has been fixed here #249
