### ISSUE TITLE
Setting RTC clock date time question

### ISSUE THREAD

**Issue by WillBaldwin** [PiSupply/PiJuice#303]
### Question
  
I am attempting to set the RTC time from my own C# library for Win10 IOT Core but I can't seem to get the RTC time to set.  I don't have any issues acquiring RTC time just setting RTC Time.  Please look at my code below.  I have prepared the byte[] following pyjuice.py:SetTime() code and the checksum code came from pyjuice.py:_GetChecksum.  I am reasonably sure that I have built the data[] correctly although I am ignoring the daylight savings 'storeoperation'.  I added the checksum byte to the array because pyjuice.py:Write() seems to add a checksum byte to outbound data.  Thank you in advance for looking at this for me.
  
### Code
                public void SetRtcDateTimeOffset(DateTimeOffset value)
                {
                     bool isDaylight = TimeZoneInfo.Local.IsDaylightSavingTime(value);
                     byte[] data = new byte[9] { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
                     data[0] = ByteToBcd(value.Second); //second
                     data[1] = ByteToBcd(value.Minute); //minute
                     data[2] = ByteToBcd(value.Hour); //hour
                     data[3] = ByteToBcd((int) value.DayOfWeek); //weekday
                     data[4] = ByteToBcd(value.Day); //day
                     data[5] = ByteToBcd(value.Month); //month
                     data[6] = ByteToBcd(value.Year - 2000); //year
                     data[7] = ByteToBcd(value.Millisecond * 256 / 1000); //subsecond
                     data[8] = isDaylight ? (byte) 0x02 : (byte) 0x01; //daylightsaving in effect?
  
                     byte[] checksum = new byte[1] { GetChecksum(data) };
                     byte[] command = { (byte) PiJuiceCommands.RTC_TIME_CMD };
                     byte[] dataWithChecksum = data.Concat(checksum).ToArray();
  
                     // RESULT
                     // DateTimeOffset.Now: 3/26/2019 10:17:57 AM -05:00
                     //                    =>data[]: 57-17-10-02-26-03-19-A9-02
                     //                    =>data[]: 57-17-10-02-26-03-19-A9-02-3A including the checksum

                     _i2cPiJuice.Write(command);
                     _i2cPiJuice.Write(dataWithChecksum);

                     // PROBLEM RESULT The RTC Time is not set...
                     // GetRtcDateTimeOffset(): 1/8/2000 11:13:22 PM -05:00
                }

**Comment by tvoverbeek** [comment]
@WillBaldwin I do not know C#.
Two things:
The RTC expects values 1..7 for weekday. 1=Sunday, 7=Saturday.
I believe C# uses 0..6.
You use 2 i2cPiJuice.write() commands.
The rtc expects the cmd and dataWithChecksum as a single sequence.
I do not know your Write implementation, but you might want to try to concatenate cmd and dataWithChecksum and send it with a single transaction.
Your checksum calculation is OK.
