### ISSUE TITLE
Possible software defect in pyjuice.py:SetTime()

### ISSUE THREAD

**Issue by WillBaldwin** [PiSupply/PiJuice#304]
### Possible software defect in pyjuice.py:SetTime() 
 
I believe I discovered a software defect in **pyjuice.py:SetTime()** at **line 632** where both the if and the elseif are compared to the same exact value to determine if d[8] could contain 0x02 or 0x01.

Code:
                if 'daylightsaving' in dt:
                if dt['daylightsaving'] == _**'SUB1H'**_:
                d[8] |= 2
                elif dt['daylightsaving'] == **_'SUB1H'_**:
                d[8] |= 1

If (dt['daylightsaving'] == _**'SUB1H'**_) the code above appears to always assign d[8] equal to 0x03 as
0x02 |= 0x01 will always result in 0x03 regardless of the original value in d[8].

**Comment by tvoverbeek** [comment]
You have an old version of pijuice.py.
Current version has the following code:
```
        if 'daylightsaving' in dt:
            if dt['daylightsaving'] == 'SUB1H':
                d[8] |= 2
            elif dt['daylightsaving'] == 'SUB1H':
                d[8] |= 1
```
Moreover in the old code it will assign 0x02 since the else if (elif) will not be executed.

**Comment by tvoverbeek** [comment]
@WillBaldwin Yes this is wrong. It is already fixed on the develop branch.
There the code is:
```
        if 'daylightsaving' in dt:
            if dt['daylightsaving'] == 'SUB1H':
                d[8] |= 2
            elif dt['daylightsaving'] == 'ADD1H':
                d[8] |= 1
```
When using Raspbian/Linux this is not a problem since the RTC is always kept in UTC which does not have daylight saving time.
I do not know what the convention is in Windows IOT.
