### ISSUE TITLE
Request info

### ISSUE THREAD

**Issue by halfajobj** [PiSupply/PiJuice#332]
Hi there i am thinking of getting a pijuice but wanted to known the following. 

If I were to purchase two 12000mah batteries and wire them up in parallelle would the pi juice board allow, charge and use of this configuration. If so could this be added as a request.

**Comment by tvoverbeek** [comment]
PiJuice charging circuitry only supports single cell batteries.
With 2 batteries in parallel you have effectively a 2-cell battery.
So your proposed configuration will not work in a safe manner.
Closing the issue. If you do not agree please reopen it.
