### ISSUE TITLE
nadhat on a pi zero and pijuice ?

### ISSUE THREAD

**Issue by patgg** [PiSupply/PiJuice#340]
is someone tryied to put a nadhat ( https://www.framboise314.fr/carte-nadhat-pour-envoyer-et-recevoir-des-sms-avec-le-raspberry-pi/ ) on a pijuice/pi zero w ?
can there be problem for voltage with second nadhat card ?
is it the same GPIO to power pi zero and others hat ?

**Comment by tvoverbeek** [comment]
Looking at the nadhaat description and pinout (https://pinout.xyz/pinout/nadhat_v1) it only uses the UART pins and GPIO26 (pin 37) whic do not conflict with the PiJuice.
When on PiJuice battery only it should be able to both supply the Pi zero w and the nadhat.
Both are then supplied via the 5V pins

**Comment by patgg** [comment]
indeed, it is functionnal. Good :)
