### ISSUE TITLE
Is possible to customize HARD_FUNC_POWER_ON function?

### ISSUE THREAD

**Issue by simar88** [PiSupply/PiJuice#341]
Hi everyone, thanks for your product...is amazing!
I would like to know if is possible to customize the HARD_FUNC_POWER_ON function in order to add some custom stuff.
In your opinion is better to copy and edit the default code or create some othe scripts and run them separately on boot?
In the first where i can find the code used for the HARD_FUNC_POWER_ON function?
Thanks in advance,
Simone

**Comment by tvoverbeek** [comment]
The HARD_FUNC_POWER_ON is completely done in the MCU on the PiJuice board. The Pi is not involved at all for obvious reasons (it is off). No way to customize it unless you change the firmware.
