### ISSUE TITLE
software is full of COMMUNICATION_ERROR errors.  Is there an update or updated settings?

### ISSUE THREAD

**Issue by pettefar** [PiSupply/PiJuice#342]
software is full of COMMUNICATION_ERROR errors.  Is there an update or updated settings?

**Comment by pettefar** [comment]
Raspberry Pi 4B Latest Raspbian.

**Comment by tvoverbeek** [comment]
Known problem on the 4B.
See my comment (https://github.com/PiSupply/PiJuice/issues/327#issuecomment-510053636) in issue #327
