### ISSUE TITLE
how to set a remote sw1/power switch?

### ISSUE THREAD

**Issue by Tahkis** [PiSupply/PiJuice#344]
Hi, 
Is it possible to wire the piJuice power switch outside the pi/pijuice package?

wbr,
-tatu

**Comment by shawaj** [comment]
Yes, you can solder wires or a header onto J5 and use an off board switch.

See here https://github.com/PiSupply/PiJuice/blob/master/Hardware/README.md#buttons

**Comment by Tahkis** [comment]
Thanks for the tip! great :-)
