### ISSUE TITLE
Is there a lower than Short piJuice case available?

### ISSUE THREAD

**Issue by Tahkis** [PiSupply/PiJuice#346]
Has anyone encountered a piJuice case that would be thinner than the readily available Short case is? In particular, I would need a case that is max 3 cm thick (bottom to top) to house pi 3B+ and piJuice board+BP7X battery. 

3D printable cad file would also do just fine!

wbr,
-tatu

**Comment by ChristopherRush** [comment]
Maybe this would be better suited in your scenario - https://uk.pi-supply.com/products/pijuice-zero?_pos=6&_sid=f686c000c&_ss=r
