### ISSUE TITLE
Battery Profile

### ISSUE THREAD

**Issue by LuvSachdevaRFID** [PiSupply/PiJuice#351]

**Comment by LuvSachdevaRFID** [comment]
Hi All,
I am using 5000mAh of battery. I am trying to configure it from command Line Interface but as soon as click on Apply setting after i have made changes. It gives me a list of error.
Also, I try to configure through GUI but In PiHAT config. I am not able to see Battery options on top.

**Comment by tvoverbeek** [comment]
Closing thia one, Continuation in #352
