### ISSUE TITLE
Redirect LED1 outside of PiJuice board

### ISSUE THREAD

**Issue by Tahkis** [PiSupply/PiJuice#359]
Hi,
what would be the  easiest way to redirect LED1/charging indication to an external LED?
I am planning to have a separate box located further away from PiJuice with a J5 switch and LED1 replica.

wbr,
-tatu

**Comment by tvoverbeek** [comment]
As far as I can tell there is no easy way to redirect LED1. LED1 (like LED2) is a 3-color led, in fact 3 leds (B, G, R) and there are no connections on the board (like J5 for SW1).
What you could do is run a small program on the RPi which polls the charge/no charge and the charge level and use that info to control your external LED via the GPIO of the RPi.
