### ISSUE TITLE
PiJuice info displayed on a OLED

### ISSUE THREAD

**Issue by emosbek** [PiSupply/PiJuice#363]
Hello.
Wanted to know if there are any resources or even possible to display stuff like charge level and other battery related info on a I2C OLED module?

**Comment by shawaj** [comment]
Yes it is very much possible but we don't have any resources available or
examples

**Comment by tvoverbeek** [comment]
As @shawaj wrote, there are no direct resources available.
The easiest is to use the lowest level python functions from the Pijuice module.
They are (partly) documented af the end of the github software README.
Best reference is the source (https://github.com/PiSupply/PiJuice/blob/master/Software/Source/pijuice.py)
If you can drive your OLED display also from python it should not be too difficult.

For something similar see http://frederickvandenbosch.be/?p=2876
This monitors the presence of power input and displays it on an e-paper display.

**Comment by shawaj** [comment]
@emosbek did you manage to get this working?

**Comment by shawaj** [comment]
No reply in over a month so closing now.

@emosbek feel free to reopen if you don't agree
