### ISSUE TITLE
Adding System functions to headless PiJuice

### ISSUE THREAD

**Issue by sensemonster** [PiSupply/PiJuice#364]
Where is the best source of information on how to add system functions using just CLI please.  I am trying to add afunction to be run when there is power interruption to the USB power feed.
I know this is straightforward when using the Desktop interface but I can't easily do that in my project as the board is buried in a case.

**Comment by tvoverbeek** [comment]
What version of the software are you running?
The pijuice_cli in the current pijuice-base package has the same functionality as the
desktop interface.
On the initial pijuice_cli screen
<img width="477" alt="Screenshot 2019-08-22 at 15 14 34" src="https://user-images.githubusercontent.com/1197294/63518807-20077480-c4f2-11e9-8627-b6af78240081.png">
select System Events
<img width="480" alt="Screenshot 2019-08-22 at 15 14 55" src="https://user-images.githubusercontent.com/1197294/63518858-39a8bc00-c4f2-11e9-82ef-a8e9932fe32d.png">
and connect a user function to the no power event.
The user function can be specified on the User Scripts page.
<img width="485" alt="Screenshot 2019-08-22 at 15 15 16" src="https://user-images.githubusercontent.com/1197294/63518965-64931000-c4f2-11e9-87c2-cff8b1648854.png">

**Comment by sensemonster** [comment]
I have the latest version of the software.  I will try your suggestion and thank you.  I was assuming there would be a directory into which I could write the script :-)

**Comment by sensemonster** [comment]
Further to my last message I have set things up so that I get a power OFF notification if power is lost.   Is there a hook/event or something similar that I could use to detect the moment the power is restored please?

At the moment my best idea is to use the power OF system event to execute a cron job every n minutes to check when the USB supply status changes and then disable the cron entry.

**Comment by tvoverbeek** [comment]
Seems the best solution for relatively short power interruptions (as long as the PiJuice battery can keep the system going).
As a safety net you might want to enable the low charge event and connect it to SYS_FUNC_HALT_POW_OFF as in the earlier screenshot In addition enable the 'wakeup on charge' on the system task screen with a trigger level of 0 (When using pijuice_cli the lowest possible trigger level is 1 due to a bug in the code).
This ensures the RPi will be properly shut down when the battery is almost empty and start up again when the external power returns.

**Comment by sensemonster** [comment]
Thanks and yes indeed I already have the low charge and wake up on charge at a certain level.  So that takes care of the things as you have described.   Basically my project is to record how long there has been a power outage.  Therefore, yes, as you have commented, my noob idea depends on battery power keeping the pi running during short power outages.  However the "perfectionist" part of my brain is thinking if there is a GPIO based event that could trigger mu "powerBackON" script :-)

**Comment by tvoverbeek** [comment]
Closing thread
