### ISSUE TITLE
PiJuice MCU

### ISSUE THREAD

**Issue by fencer** [PiSupply/PiJuice#367]
Is it possible to use the PI juice MCU to execute custom code (Display some loading text on an ssd1306) while the pi is booting?

**Comment by tvoverbeek** [comment]
No, as far as I know.
How would you connect the SSD1306 to the MCU?
The MCU has both an I2C master (for internal sensors) and slave (for communication with the RPi).
All MCU outputs are taken.
Maybe you could control the SSD1306 with an other small MCU (tiny arduino or similar)

**Comment by fencer** [comment]
That would by my second option. but wanted to check if I can use the MCU on the PiJuice before going ahead with that.
