### ISSUE TITLE
SYS_FUNC_REBOOT Permission error

### ISSUE THREAD

**Issue by ChristopherRush** [PiSupply/PiJuice#368]
PI 3B
Buster
SYS_FUNC_REBOOT set to SW2 in button configuration.

<img width="1138" alt="Screen Shot 2019-08-27 at 10 46 36" src="https://user-images.githubusercontent.com/1878314/63760937-2e6ddb80-c8b8-11e9-8c9b-f903b8c81e45.png">

**Comment by tvoverbeek** [comment]
@ChristopherRush Good catch. I obviously never tested SYS_FUNC_REBOOT.
FIx is easy. Add /sbin/reboot to the allowed commands for user pijuice in /etc/sudoers.d/020_pijuice-nopasswd.
See commit https://github.com/PiSupply/PiJuice/commit/a6498258de24108b66e09dd5c2397f373c9ff2a5

**Comment by ChristopherRush** [comment]
@tvoverbeek Thanks, tested confirmed working.
