### ISSUE TITLE
Report changeing status and battery level via ACPI

### ISSUE THREAD

**Issue by the-louie** [PiSupply/PiJuice#377]
Is it possible to configure pijuice to report status via ACPI?

I use an application that's normally is run on laptops and exposes battery status but it's not useful now since it's always "Plugged in".

**Comment by tvoverbeek** [comment]
Short answer: No
ACPI support in Raspbian is rudimentary to non-existent.

**Comment by the-louie** [comment]
Ah, too bad, but thanks for the reply.

**Comment by shawaj** [comment]
This is an interesting project https://www.cnx-software.com/2020/02/18/raspberry-pi-4-uefiacpi-firmware-aims-to-make-the-board-sbbr-compliant/

But unless it makes it into the main firmware we likely won't make any updates.

So closing for now.
