### ISSUE TITLE
Battery Sticker P3 Description reversed

### ISSUE THREAD

**Issue by Cielquan** [PiSupply/PiJuice#381]
Hi all,
While reading the hardware readme I noticed that the battery sticker has a reversed order for the P3 pinout. At the start of the readme its shown correctly like the label on the board.

**Comment by ChristopherRush** [comment]
Yes, you are correct. I will get the graphics team to amend this sticker/label. Will close once done. Thanks for the spot.

**Comment by ChristopherRush** [comment]
Fixed bf79fd4b135ea0c4aebfcb47c32ed18d88d235b7
