### ISSUE TITLE
Battery level not shown in htop

### ISSUE THREAD

**Issue by rene54321** [PiSupply/PiJuice#384]
Hi,

the task manager tool htop has the possibility to show the battery status. But for the pi it shows N/A is it possible for you to implement an sw change to be able to show the battery level also in this tool?

best regards René

**Comment by tvoverbeek** [comment]
htop uses the information from /sys/class/power_supply and/or from /proc/acpi.
Both are empty directories in Raspbian. Since the PiJuice is an additional external battery (not a built-in battery as in laptops) there is no support in the OS.

**Comment by rene54321** [comment]
Ok understood. 

thanks for clarification. 

Best regards René
