### ISSUE TITLE
Add battery connector info to hardware section

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#395]
Connector on PiJuice Zero - https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/292253-3/A98575-ND/1855245

Connector for battery - https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/2-179694-3/2-179694-3-ND/2259036

**Comment by ChristopherRush** [comment]
b55baa1569c55e519ca48b45e66627e45a4b0fff
