### ISSUE TITLE
Need RP4 to safe shutdown when power lost (with delay) and auto-start when power applied

### ISSUE THREAD

**Issue by BigEpidemic** [PiSupply/PiJuice#403]
I can't get the user_func1.py solution you propose to even fire. No log is ever generated in the folder. I've set permissions on the file to execute. When I pull power from either the USBC or the micro-usb the script never seems to execute. I'm pretty new to Linux so maybe I'm doing something wrong.

Is what I'm trying to do possible?

**Comment by ChristopherRush** [comment]
Just tested this and the log file was created when I removed power from the Raspberry Pi. What OS are you running? I did `sudo chmod +x` on the script before hand.

**Comment by tvoverbeek** [comment]
As @ChristopherRush wrote the script needs to be executable.
Moreover the owner of the script (normally pi) has to be a member of the pijuice group.
The default user (pi) is already a member of the pijuice group.
Assuming you are using the GUI:
On the 'System Events' tab you have to enable 'No power:' and link it to USER_FUNC1.
On the 'User Scripts' tab you have to specify the path for 'USER FUNC1:' e.g. '/home/pi/user_func1.py'.
Most likely you already did this, but did not make the script executable.
The sample script will run under both python2 and python3.
If you later add pijuice commands to the script you have to use python3.
Suggest to change the first line of the script to `#!/usr/bin/python3`

**Comment by ChristopherRush** [comment]
@BigEpidemic Do you still need help with this?

**Comment by BigEpidemic** [comment]
No. Thank you for your attention to this. I've switched to another product.
