### ISSUE TITLE
Turn on Vsys from the API

### ISSUE THREAD

**Issue by trondsen** [PiSupply/PiJuice#414]
Hello,

Is it possible to turn on the Vsys output from the API?
As far I understand this output resets when power is disconnected (battery and gpio)
I would be nice be able to turn on this output as soon as the Python scripts starts.

Thank you

Jonas

**Comment by ChristopherRush** [comment]
Try: `pijuice.power.SetSystemPowerSwitch(500)` Where 500 is the current limited. 500 or 1200 can be selected.

**Comment by shawaj** [comment]
Closing this issue. Please reopen if you disagree
