### ISSUE TITLE
battery is not charging

### ISSUE THREAD

**Issue by JVTEAM** [PiSupply/PiJuice#419]
The battery suddenly stopped getting a charge.  The LED light just stays red and the charge stays at 1%.

I even disconnected from the pi.  no change.

**Comment by ChristopherRush** [comment]
Is charging enabled? Is the temperature stable? Is the battery detected? Any signs of battery bulging? Any errors in the PiJuice Software? Have you tried to re-seat the battery by removing it? Any other devices connected?

**Comment by JVTEAM** [comment]
huh.  somehow the tick in charging was unticked.  thanks!
