### ISSUE TITLE
AstroPi GPIO compatibility broken by PiJuice

### ISSUE THREAD

**Issue by enriqueescobar-askida** [PiSupply/PiJuice#420]
I have being using the Rpi 3 B+ for a coule of years,
I use it as a weather station with AstroPI.
Yesterday I received my fancy PiJuice.
I installed the PiJuice software.
I removed AstroPi from GPIO.
I put PiJuice on the RPi GPIO pins.
I turned on the Rpi,
PiJuice works perfectly.
I stopped RPi to put AstroPi on top of the GPIO pins from PiJuice.
Rpi cannot longer recognize the AstroPi :( :'( :$
Can anyone explain to me the proper configuration?

Thanks

**Comment by ChristopherRush** [comment]
There is already a solved issue here #126 You need to change the ID EEPROM address to 52. Make sure that `ID EEPROM Write unprotect` is checked before changing the address to 52.
