### ISSUE TITLE
Need for changing / bypassing the SW1 switch.

### ISSUE THREAD

**Issue by jnfrncs** [PiSupply/PiJuice#430]
Hi, 

I would like to install my pizero in an waterproof enclosure. Since it's complicated to open it if the PiJuice board shutdown the pizero when the battery is empty, I'll would like to install a small magnetic switch to operate it from outside the box.

The board is quite dense, what is the best way to solder an additional pair of cables to bypass the SW1 switch ? Any chance to avoid removing SW1 ? 

Thanks for your advice,

**Comment by shawaj** [comment]
Take a look at J5 here - https://github.com/PiSupply/PiJuice/blob/master/Hardware/README.md#zero

You can use this instead of SW1
