### ISSUE TITLE
Errors when installing on headless Pi 3b+

### ISSUE THREAD

**Issue by marthazimet** [PiSupply/PiJuice#440]
I purchased PiJuice HAT to evaluate for my production solar devices in the field. Obviously, they are all headless. 

Following the instructions for install without GUI, when I invoke pijuice_cli
 there is an error. Screen dump attached. 

![Screenshot from 2020-01-06 11-28-57](https://user-images.githubusercontent.com/33074642/71843041-dde16880-3077-11ea-9ce5-19f96c91d445.png)

**Comment by tvoverbeek** [comment]
@marthazimet  Looks like you are runing as root.
You have to run pijuice_cli and pijuice_gui as a non privileged user.

**Comment by marthazimet** [comment]
Thanks... I was following the online docs and didn't see that mentioned. 

I have solar devices deployed in the field and I am looking for a replacement for WittyPi boards which have been failing after about six months. 

This is my device which is deployed in remote sites in the US, Canada, and recently in NZ: https://manray.com/electronic-game-bird-recall

PiJuice looks promising.
