### ISSUE TITLE
Make and model of connector P1

### ISSUE THREAD

**Issue by Nostredame81** [PiSupply/PiJuice#444]
Hi, does anybody know make and model of connector P1? Thanks, kind regards, Mathis

**Comment by tvoverbeek** [comment]
P1 is a 'normal' RPi GPIO connector.
There are some 3d pictures on the last pages of https://github.com/PiSupply/PiJuice/blob/master/Documentation/PiJuice_Schematic.PDF

**Comment by shawaj** [comment]
It is a 4uconn 03173 - see attached datasheet

[03173.pdf](https://github.com/PiSupply/PiJuice/files/4086689/03173.pdf)
