### ISSUE TITLE
PiJuce Zero Firmware 1.4 ETA?

### ISSUE THREAD

**Issue by fictionalname** [PiSupply/PiJuice#448]
Hello,

Can you please let me know the ETA for firmware 1.4 for the PiJuice Zero?

Thanks.

**Comment by tvoverbeek** [comment]
@fictionalname I cannot give you a fixed date.
Still testing to iron out the last problems especially on the Pi4.
Certainly not before February. I will be on travel next week and cannot work
on the new release (as a volunteer, I am not employed by Pi-Supply).

**Comment by fictionalname** [comment]
Thank you for the update - I am looking forward to the new release as my device is showing the invalid battery temperature issue which is impacting on charging.
