### ISSUE TITLE
can the Pijuice power a pi4 and the Official screen

### ISSUE THREAD

**Issue by Calgar77** [PiSupply/PiJuice#452]
im plannign to get a pijuice for the raspberry pi 4 for portable emulation and wanted to know if it would power the pi4 and its screen (plus peripherals) either with the default or a bigger battery

**Comment by shawaj** [comment]
@Calgar77 yes it should work, as long as you use the 12000mAh battery to give maximum output

**Comment by Calgar77** [comment]
ok thank you

**Comment by shawaj** [comment]
Did you manage to get this working @Calgar77 ?

**Comment by Calgar77** [comment]
unfortunatly i have been unable to test it due to the battery not fitting into the case i'm using, so am currently looking into custom modding the case to fit it .

**Comment by Arno-GitHub** [comment]
At the moment i'm using the Official 7" touchscreen and the BP7X battery.
The Pijuice can then only be used as an UPS.

I'm using the BP7X because of the size of the case (SmartiPi Touch 2).
After ~30 minutes the battery is drained.

**Comment by shawaj** [comment]
@Calgar77 did you test this now?

@adevoss is that with the pi 4 and official display? It works ok and doesn't give low voltage warning with the BP7X?

**Comment by adevoss** [comment]
@shawaj Yes it is the official display. It does not work ok. I got help of a Pijuice developer. He said the display draws too much from the battery.

I couldn't get it to work so I removed the Pijuice and now using my Pi with a power supply.
With that power supply I get low voltage warnings from time to time.

**Comment by shawaj** [comment]
@adevoss you could always try the 12000mAh battery but that won't fit so nicely in the case.

**Comment by adevoss** [comment]
@shawaj Does not fit indeed. I want to use it on the move (satnav in the car). Haven't found a solution that works for me.
When I use the cigarette lighter there are so many cables.
At shutdown the touchscreen goes off immediately but the OS is not shutdown yet. Also not helps.

So I shelved that project a while ago.
Use the Pi now as my desktop pc. Until the Intel NUC 11 will be released. Then the Pi will be available for a next project.
Thinking about Kodi or satnav (navi) again if other solutions are available.

**Comment by shawaj** [comment]
@adevoss something like this might be useful https://www.amazon.co.uk/dp/B07P87KXNY/

**Comment by adevoss** [comment]
@shawaj Thanks. Those wires without a connector always scare me a bit. I don't want to be fried by my car battery. But I will look into it again.

**Comment by shawaj** [comment]
@adevoss you could use some connectors like this to hook them up to the battery https://www.amazon.co.uk/dp/B0787B99KB/

You could add an inline fuse if you want too https://www.amazon.co.uk/dp/B076CFS2M6/

A 1.5A or 2A fuse should be good.

The 12 volts of the car battery won't necessarily give you a shock, unless your hands are very wet, as the resistance of human skin doesn't allow much current to flow at 12v. So you don't need to be too worried when working on a12v system.

**Comment by shawaj** [comment]
@adevoss  can we close this issue now or do you need any further assistance?

**Comment by adevoss** [comment]
I did not start this issue so I can't say. I have no further questions.

**Comment by shawaj** [comment]
Closing this issue for now. Please reply back if you disagree or have any further issues.
