### ISSUE TITLE
Unable to disable charge via API

### ISSUE THREAD

**Issue by etsach** [PiSupply/PiJuice#456]
Hi,

With pijuice_cli, I can enable and disable battery charging without issues.
I want to write a script for controlling the battery charge and keep it between 60% and 70%, in order to preserve battery life as I use it always powered (UPS use)

I run in a python script with user pijuice (via sudo -u pijuice python3 test.py):
```
print("Disabling charge") 
pijuice.config.SetChargingConfig(False, True) 
print(pijuice.config.GetChargingConfig())

```
And I get:

> Disabling charge
> {'data': {'charging_enabled': True}, 'error': 'NO_ERROR', 'non_volatile': False}

And charge continues.

**Comment by galinette2000** [comment]
I found the problem, now the command to enable charging is:
`pijuice.config.SetChargingConfig({'charging_enabled':True}, True) `

Instead of what is written in the documentation:
`pijuice.config.SetChargingConfig(True, True) `

**Comment by tvoverbeek** [comment]
@galinette2000 Thanks a lot for catching this.
The `pijuice.config.SetChargingConfig({'charging_enabled':True}, True)` syntax is used by pijuice_cli and pijuice_gui.
When writing user scripts the syntax `pijuice.config.SetChargingConfig(False, True)` is more natural.
Will try to modify pijuice.py to accept both forms (so we do not have to modify the documentation ;-)).

**Comment by tvoverbeek** [comment]
Done. Closing Issue.
