### ISSUE TITLE
P3 Pinouts Specs

### ISSUE THREAD

**Issue by LuvSachdevaRFID** [PiSupply/PiJuice#461]
Hi, 
Can anyone tell me which header pins specs which will fit in P3 Socket on the pijuice.
Thanks

**Comment by tvoverbeek** [comment]
P3 is a 'normal' 0.1  inch female header.

**Comment by shawaj** [comment]
The exact part number is 00527 from 4uconn -6 pins, female, P2.54mm, H8.5mm, DIP3mm. TH HEADER 1X6 - 15,84 x 2,5 x 8,5 mm

Datasheet here:
[00527.pdf](https://github.com/PiSupply/PiJuice/files/4175143/00527.pdf)

**Comment by shawaj** [comment]
A header like this would work nicely https://uk.rs-online.com/mobile/p/pcb-headers/6812994/

**Comment by shawaj** [comment]
[0900766b80da602d.pdf](https://github.com/PiSupply/PiJuice/files/4238389/0900766b80da602d.pdf)
