### ISSUE TITLE
Properly charge cycling a new battery

### ISSUE THREAD

**Issue by jbmorris289** [PiSupply/PiJuice#462]
Hi again, I'm back here..
This is a continuation of my previous issue: #458.

My new battery was delivered, I unpacked it, and mounted it on the HAT. As I was doing this, I also read the label on the battery, which directed me to the instructions on the box the battery was in, and noticed something to do with charge/discharge cycles.

Now, I'm already aware of this kind of stuff. My current problem, however is... how would I go about doing this properly? Do I let the battery charge up while the Pi is running, or turned off? Should I let my Pi run to 0% (while having the minimum charge at 0%... if that works)? etc.

**Comment by shawaj** [comment]
@jbmorris289 there's no specific way to do this. I would suggest when receiving a new battery to fully charge it to before use, with the PiJuice not attached to the Pi. And from then just use as normal.

However if you didn't do that it's not the the of the world.
