### ISSUE TITLE
Has anyone used the PiJuice with a PiBorg Reverse board?

### ISSUE THREAD

**Issue by wingers999** [PiSupply/PiJuice#466]
Has anyone used the PiJuice with a PicoBorg Reverse board?  

If so did you manage to get enough power via VSYS or P3 to power PiBorg Reverse board and motors? or if not how did you get round it?

Thanks

**Comment by shawaj** [comment]
@wingers999 do you mean the PicoBorg reverse? https://www.piborg.org/motor-control-1135/picoborgrev

**Comment by wingers999** [comment]
I did - sorry now corrected

**Comment by shawaj** [comment]
It looks like that board needs 6 to 10 volts and, depending on what motors you are using, up to 5A per channel (total 10A).

PiJuice probably not suitable for this purpose.

With a large battery like the 12000mAh, you might get away with powering some smallish motors but don't know the exact spec of the motor driver chips and whether they'll work with only 5v

**Comment by wingers999** [comment]
Okay thanks, I did wonder that.  So better off using PiJuice just for powering my Pi, and then having a separate battery pack directly connected to the PicBorg to power it and the motors

**Comment by shawaj** [comment]
Yes that will work perfectly. 

Alternatively, you could use their Thunderborg motor controller which can power the Pi also from the same batteries https://www.piborg.org/motor-control-1135/thunderborg

**Comment by wingers999** [comment]
Yes I had seen that, and I also have their BattBorg which would do same with PicoBorg, but then would defeat the point of having the PiJuice which I love!

**Comment by shawaj** [comment]
True, I definitely won't stop you using PiJuice 😛

Did you have any other questions at all? If not I'll go ahead and close this issue.

**Comment by wingers999** [comment]
:) 

No that is all thanks, I will get back to building my robot now :)

![image](https://user-images.githubusercontent.com/10872799/75095497-323f9980-558d-11ea-9f01-2e33769c7237.png)

**Comment by shawaj** [comment]
Cool! Enjoy the build. 

And send us pictures on Twitter / Facebook when you're done 👌
