### ISSUE TITLE
nice but why one source

### ISSUE THREAD

**Issue by 0xtrzy** [PiSupply/PiJuice#468]
Nice project.

Is possible to put more sources? Every accumulator after 2-3 years not working good.
If I would like to use more than one accumulator (with different size) I have trouble.
Why not using AA accumulator? or 18650 ? or 12V auto accumulator in this same time.
I can buy 18650, AA everywhere and always (after 20 years too) 
Simple router with script for turn off wifi, more solar power (light) long time working ,,less power less working time etc.

**Comment by shawaj** [comment]
This is specifically designed to charge single cell lipo or lithium ion batteries.
