### ISSUE TITLE
Which battery profile for 2300mAh battery (PIS-0786)?

### ISSUE THREAD

**Issue by knutsiem** [PiSupply/PiJuice#478]
I just bought the [2300mAh battery compatible with PiJuice (PIS-0786)](https://uk.pi-supply.com/products/2300-mah-battery-compatible-with-pijuice) but I'm not sure if I should change my battery profile from BP7X_1820. The sticker on my new battery says the following:

    Model No.: CS-MOA855XL
    Part No. : BP7X, SNN5875A
    Rating   : 3.7V 2300mAh
               8.5Wh
    Lithium-ion Battery Pack

The profile SNN5843_2300 has "Capacity" 2300mAh, but as you can see the battery does not say "SNN5843". Looking more closely I see that the only additional differences are "Charge current" (925mA vs 1150mA) and "Termination current" (50mA vs 100mA).

Which profile should I use? Do need to create a new one, and if so, which values should I use?

For battery profile reference I used https://github.com/PiSupply/PiJuice/tree/master/Hardware#predefined-profiles .

**Comment by shawaj** [comment]
Yes you can use SNN5843_2300
