### ISSUE TITLE
Updates to Watchdog timeout, low charge level etc.

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PiJuice#48]
All stuff exclusively between pijuice_gui and the system task) does not update immediately when the system task is already enabled (although the JSON is updated immediately on 'Apply'.
Similarly when unchecking the system task enable checkbox the task is not disabled (changing from disabled to enabled does restart the service which will then pick up the configuration).

**Comment by DenisKhrutsky** [comment]
Took a different approach in [Commit #f9d768](https://github.com/PiSupply/PiJuice/commit/f9d7686e84160eed5d6b136d05f56f0ae8a2f85c)

**Comment by tvoverbeek** [comment]
Works fine now.
