### ISSUE TITLE
PiJuice sold out

### ISSUE THREAD

**Issue by Jonathan56** [PiSupply/PiJuice#483]
Hi,
I am just wondering if I can get the PiJuice somewhere? Most shops seem sold out.

**Comment by shawaj** [comment]
@Jonathan56 where are you based? Our next batch of boards has been delayed by Coronavirus but we should have many more soon

**Comment by Jonathan56** [comment]
France, good luck. I will keep an eye for it then :)

**Comment by shawaj** [comment]
@Jonathan56 these should be arriving with us in the next week. We have got about 100 for us and the remaining 1900 are going out to resellers. The good news is that 200 of those are going to KUBII in France.
