### ISSUE TITLE
cannot change i2c Address2

### ISSUE THREAD

**Issue by MaResailing** [PiSupply/PiJuice#484]
Hello
First of all, I'm a beginner in this business.
I build a navigation computer on a Raspi4 with openplotter and the Moitessier Hat and the PiJuice Hat.
As soon as I put the moitessier-hat on the PiJuice, I lose the connection to the PiJuice. The moitessier-hat continues to run. With my modest knowledge it looks like a conflict with the double i2c assignment:
only PiJuice:
pi@openplotter:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --      

only moitessier hat:
pi@openplotter:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- 77   

According to the documentation you should be able to change the value of the I2C Address2 (RTC) in the PiJuice settings under Configure HAT. But nothing happens, no matter what I enter in these fields.
Here is my Raspi environment:
pi@openplotter:~ $ hostnamectl
   Static hostname: openplotter
         Icon name: computer
        Machine ID: 90007509bb7e479ea929fda793e08c79
           Boot ID: 2e313ef7e76840bdab8051a6d394ea84
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.97-v7l+
      Architecture: arm

Thanks for the help!

**Comment by tvoverbeek** [comment]
I assume you have set the2  ID-EEPROM address of the PiJuice to 0x52.
Since there are 2 HATs each with their ID-EEPROM at 0x50 there are conflicts at boot.

I understand the moitessier hat uses I2C addresses 0x68 for the motion tracking sensor and 0x77 for the barometric pressure sensor. It seems you do not have the humidity and temperature sensor which uses address 0x40.

With only the PiJuice HAT connected select the ID-EEPROM address as 0x52 via the dropdown.
Set the I2C Address2 (RC) to something else, e.g. 69. If you are using the CLI  do not forget to <Apply settings>.
Then run `i2cdetect -y 1` again which should show only addresses 0x14 and 0x69.

**Comment by MaResailing** [comment]
Thank you for your answer. Yes, I set the EEPROM ID to 0x52. However, the value I entered in the CLI (e.g. 69) is not saved and I always have the same old values after a reboot. Is there any other way than changing the I2C address via the CLI?

**Comment by tvoverbeek** [comment]
After you change the RTC address to 69, go down to "Apply settings" and press Enter:
<img width="452" alt="Screenshot 2020-04-01 at 14 56 29" src="https://user-images.githubusercontent.com/1197294/78139690-3337d680-7429-11ea-9ea9-1a65660a5138.png">

You should get the "Settings successfullly updated" message:
<img width="453" alt="Screenshot 2020-04-01 at 14 59 46" src="https://user-images.githubusercontent.com/1197294/78139897-7a25cc00-7429-11ea-9ecc-08dacb529037.png">

After exiting the CLI `i2cdetect -y 1` should show addresses 14 and 69. At least it does for me.

Which version of the software are you running? Look at the output from `dpkg -l pijuice-base`.
Current version is 1.6.

**Comment by MaResailing** [comment]
I have the latest version: 
||/ Name           Version      Architecture Description
+++-==============-============-============-=========================================
ii  pijuice-base   1.6          all          Basic support for Pi-Supply's PiJuice HAT

ii  pijuice-base                         1.6                                 all          Basic support for Pi-Supply's PiJu
ii  pijuice-gui                          1.6                                 all          The desktop applications for the P

But I have a different CLI interface than in your screenshot:

![PiJuiceHat-Config1](https://user-images.githubusercontent.com/62906844/78144319-be1bcf80-742f-11ea-8f20-ec6d5e106300.png)

Under Configure HAT, according to the text in the lower right corner, changes should be applied immediately. The Apply button is only available on the CLI homepage

**Comment by tvoverbeek** [comment]
Your screenshot shows the address as 69.
Anyway, when you edit the address make sure you press Enter or mve thecursor to another field.
You should then get a popup. See below:
<img width="652" alt="Screenshot 2020-04-01 at 16 02 50" src="https://user-images.githubusercontent.com/1197294/78146490-7ea2b280-7432-11ea-9864-c29d9cb362c7.png">

**Comment by MaResailing** [comment]
My screenshot shows my desired input BEFORE I have closed the window. No, no popup is displayed...

**Comment by tvoverbeek** [comment]
What version of the software are you running? Look at the output from `dpkg -l pijuice-base`.
Current version is 1.6.
In the GUI can you check the version of the firmware? Current version is 1.4.

**Comment by MaResailing** [comment]
After rebuilding the whole system from scratch (including openplotter debain) the problem seems to be solved - the popup window appears after entering the value and the entered value is saved and there is no connection error. Thanks for all the help!  Stay healthy, everybody!

**Comment by tvoverbeek** [comment]
Glad you got it working. Good luck with your system.
