### ISSUE TITLE
PiJuice technical data

### ISSUE THREAD

**Issue by fsegb** [PiSupply/PiJuice#488]
Hello,
I'm designing a system that will be solar powered. I'm interested in this product but I need to know the following information:
1. Nominal voltage
2. Max power intensity
3. Short-circuit intensity
4. Functionality factor

I'm interested in the 40W model but I would appreciate receiving the information for every model.
Do you have a technical data sheet?

Thanks in advance.

**Comment by shawaj** [comment]
The PiJuice Solar panels have a regulated 5v output. The 40 watt panel also has a regulated 19 volt output via the DC jack.

Are you planning to use this panel in an implementation without the PiJuice HAT itself?

**Comment by shawaj** [comment]
@fsegb do you need anything else here or can I close the issue?

**Comment by fsegb** [comment]
You can close it, thank you very much
Francisco




De: Aaron Shaw<mailto:notifications@github.com>
Enviado: sábado, 24 de octubre de 2020 5:45
Para: PiSupply/PiJuice<mailto:PiJuice@noreply.github.com>
CC: fsegb<mailto:fran_sb88@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [PiSupply/PiJuice] PiJuice technical data (#488)


@fsegb<https://github.com/fsegb> do you need anything else here or can I close the issue?
