### ISSUE TITLE
Compatibility with other i2c peripherials

### ISSUE THREAD

**Issue by lg007** [PiSupply/PiJuice#491]
Hello,

I have a question for which I haven't found the answer in previous issues.

I am planning to use a BME280 connected to the i2c bus of the Pi (its default i2c address is 0x77) in parallel with the PiJuice board. Is this possible? Would there be any limitations on its use? Sshould I make any modification to the PiJuice software?

Thanks,

**Comment by tvoverbeek** [comment]
@lg007 Should be no problem. I2C is a serial bus and PiJuice only uses addresses 0x14 and 0x68.
So no conflicts with 0x77 and no modifications to the PiJuice software needed.

**Comment by lg007** [comment]
Thank you for the prompt reply. I will try it!
