### ISSUE TITLE
Build on Ubuntu 20.04 with Python 3.8 failed

### ISSUE THREAD

**Issue by MarkusLange** [PiSupply/PiJuice#498]
Hello,

I get serveral error Messages when I try to compile it on Ubuntu 20.04 with Python 3.8

> ubuntu@ubuntu:~/PiJuice/Software/Source$ cd Setuid-Wrapper
> ubuntu@ubuntu:~/PiJuice/Software/Source/Setuid-Wrapper$ sudo cp p* $HOME/PiJuice/Software/Source/bin
> ubuntu@ubuntu:~/PiJuice/Software/Source/Setuid-Wrapper$ cd ..
> ubuntu@ubuntu:~/PiJuice/Software/Source$ sudo ./pckg-pijuice.sh
> running bdist_deb
> running sdist_dsc
> running sdist
> running check
> warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)
> 
> warning: sdist: standard file not found: should have one of README, README.txt, README.rst
> 
> writing manifest file 'MANIFEST'
> creating pijuice-base-1.6
> creating pijuice-base-1.6/bin
> creating pijuice-base-1.6/data
> creating pijuice-base-1.6/data/firmware
> creating pijuice-base-1.6/src
> making hard links in pijuice-base-1.6...
> hard linking pijuice.py -> pijuice-base-1.6
> hard linking setup.py -> pijuice-base-1.6
> hard linking bin/pijuice_cli -> pijuice-base-1.6/bin
> hard linking bin/pijuiceboot -> pijuice-base-1.6/bin
> hard linking data/020_pijuice-nopasswd -> pijuice-base-1.6/data
> hard linking data/firmware/PiJuice-V1.4_2020_01_17.elf.binary -> pijuice-base-1.6/data/firmware
> hard linking src/pijuice_cli.py -> pijuice-base-1.6/src
> hard linking src/pijuice_sys.py -> pijuice-base-1.6/src
> Creating tar archive
> removing 'pijuice-base-1.6' (and everything under it)
> dpkg-buildpackage: info: source package pijuice-base
> dpkg-buildpackage: info: source version 1.6-1
> dpkg-buildpackage: info: source distribution unstable
> dpkg-buildpackage: info: source changed by Ton van Overbeek <tvoverbeek@gmail.com>
>  dpkg-source --before-build .
> dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
> dpkg-buildpackage: warning: (Use -d flag to override.)
> Traceback (most recent call last):
>   File "setup.py", line 55, in <module>
>     setup(
>   File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/command/bdist_deb.py", line 33, in run
>     self.run_command('sdist_dsc')
>   File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/command/sdist_dsc.py", line 136, in run
>     build_dsc(debinfo,
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 1501, in build_dsc
>     dpkg_buildpackage('-S','-sa',*args,cwd=fullpath_repackaged_dirname)
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 562, in dpkg_buildpackage
>     process_command(args, cwd=cwd)
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 184, in process_command
>     check_call(args, cwd=cwd)
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 38, in check_call
>     raise CalledProcessError(retcode)
> stdeb3.util.CalledProcessError: 3
> dpkg-buildpackage: warning: using a gain-root-command while being root
> dpkg-buildpackage: info: source package pijuice-base
> dpkg-buildpackage: info: source version 1.6
> dpkg-buildpackage: info: source distribution unstable
> dpkg-buildpackage: info: source changed by Ton van Overbeek <tvoverbeek@gmail.com>
> dpkg-buildpackage: info: host architecture arm64
>  dpkg-source --before-build .
>  fakeroot debian/rules clean
> dh clean --with python3 --with systemd --buildsystem=pybuild
> dh: error: unable to load addon python3: Can't locate Debian/Debhelper/Sequence/python3.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python3 module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/aarch64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at (eval 11) line 1.
> BEGIN failed--compilation aborted at (eval 11) line 1.
> 
> make: *** [debian/rules:5: clean] Error 255
> dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
> running bdist_deb
> running sdist_dsc
> running sdist
> running check
> warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)
> 
> warning: sdist: standard file not found: should have one of README, README.txt, README.rst
> 
> writing manifest file 'MANIFEST'
> creating pijuice-gui-1.6
> creating pijuice-gui-1.6/bin
> creating pijuice-gui-1.6/data
> creating pijuice-gui-1.6/data/images
> creating pijuice-gui-1.6/src
> making hard links in pijuice-gui-1.6...
> hard linking setup.py -> pijuice-gui-1.6
> hard linking bin/pijuice_gui -> pijuice-gui-1.6/bin
> hard linking data/36x11-pijuice_xhost -> pijuice-gui-1.6/data
> hard linking data/pijuice-gui.desktop -> pijuice-gui-1.6/data
> hard linking data/pijuice-tray.desktop -> pijuice-gui-1.6/data
> hard linking data/images/bat-0.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-10.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-100.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-20.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-30.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-40.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-50.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-60.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-70.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-80.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-90.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-0.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-10.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-100.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-20.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-30.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-40.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-50.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-60.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-70.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-80.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-in-90.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-0.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-10.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-100.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-20.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-30.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-40.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-50.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-60.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-70.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-80.png -> pijuice-gui-1.6/data/images
> hard linking data/images/bat-rpi-90.png -> pijuice-gui-1.6/data/images
> hard linking data/images/connection-error.png -> pijuice-gui-1.6/data/images
> hard linking data/images/no-bat-in-0.png -> pijuice-gui-1.6/data/images
> hard linking data/images/no-bat-rpi-0.png -> pijuice-gui-1.6/data/images
> hard linking data/images/pijuice.png -> pijuice-gui-1.6/data/images
> hard linking src/pijuice_gui.py -> pijuice-gui-1.6/src
> hard linking src/pijuice_tray.py -> pijuice-gui-1.6/src
> Creating tar archive
> removing 'pijuice-gui-1.6' (and everything under it)
> dpkg-buildpackage: info: source package pijuice-gui
> dpkg-buildpackage: info: source version 1.6-1
> dpkg-buildpackage: info: source distribution unstable
> dpkg-buildpackage: info: source changed by Ton van Overbeek <tvoverbeek@gmail.com>
>  dpkg-source --before-build .
> dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
> dpkg-buildpackage: warning: (Use -d flag to override.)
> Traceback (most recent call last):
>   File "setup.py", line 55, in <module>
>     setup(
>   File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/command/bdist_deb.py", line 33, in run
>     self.run_command('sdist_dsc')
>   File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/command/sdist_dsc.py", line 136, in run
>     build_dsc(debinfo,
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 1501, in build_dsc
>     dpkg_buildpackage('-S','-sa',*args,cwd=fullpath_repackaged_dirname)
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 562, in dpkg_buildpackage
>     process_command(args, cwd=cwd)
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 184, in process_command
>     check_call(args, cwd=cwd)
>   File "/usr/local/lib/python3.8/dist-packages/stdeb3/util.py", line 38, in check_call
>     raise CalledProcessError(retcode)
> stdeb3.util.CalledProcessError: 3
> dpkg-buildpackage: warning: using a gain-root-command while being root
> dpkg-buildpackage: info: source package pijuice-gui
> dpkg-buildpackage: info: source version 1.6
> dpkg-buildpackage: info: source distribution unstable
> dpkg-buildpackage: info: source changed by Ton van Overbeek <tvoverbeek@gmail.com>
> dpkg-buildpackage: info: host architecture arm64
>  dpkg-source --before-build .
>  fakeroot debian/rules clean
> dh clean --with python3 --buildsystem=pybuild
> dh: error: unable to load addon python3: Can't locate Debian/Debhelper/Sequence/python3.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python3 module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/aarch64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at (eval 11) line 1.
> BEGIN failed--compilation aborted at (eval 11) line 1.
> 
> make: *** [debian/rules:4: clean] Error 255
> dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
 

Using this skript:
```
#!/bin/bash

sudo apt update
sudo apt install -y python3-smbus python3-pip python3-stdeb dh-systemd debhelper fakeroot python3-all
sudo pip3 install stem stdeb3

sudo git clone https://github.com/PiSupply/PiJuice.git

cd $HOME/PiJuice/Software/Source/Setuid-Wrapper
sudo ./build-setuid-progs.sh
sudo cp p* $HOME/PiJuice/Software/Source/bin

cd $HOME/PiJuice/Software/Source/
sudo ./pckg-pijuice.sh

sudo cp $HOME/PiJuice/Software/Source/deb_dist_base/pi*.deb $HOME
sudo cp $HOME/PiJuice/Software/Source/deb_dist_gui/pi*.deb $HOME

sudo rm -rf PiJuice

sudo apt install -y python3-urwid lua5.3
```
Need help

**Comment by MarkusLange** [comment]
Can correct myself dh-python was missing:
`sudo apt install dh-python`
solv it
but in line 116 from pijuice_cli.py is since Python 3.8 an Syntax error

> /usr/bin/pijuice_cli.py:116: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if default is not None and default is not "":

it's gone if you change the 2nd **is not** to **!=** so that you have this line

`116:             if default is not None and default != "":`

after this all runs as smooth as usual

**Comment by tvoverbeek** [comment]
@MarkusLange Thanks for the syntax correction for Python 3.8. Updated pijuice_cli.py: commit 
https://github.com/PiSupply/PiJuice/commit/87fe15ad0793f0cb2b3a720e4c0752b98672025c
