### ISSUE TITLE
add firmware source code

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#5]
add firmware source code

**Comment by shawaj** [comment]
Now have got the firmware source code from @mmilann but awaiting the build instructions for this. Should have soon

**Comment by jophut** [comment]
Any news on the firmware source code? When will it be released?

**Comment by shawaj** [comment]
not sure yet. not really a priority to be honest but will get it done as soon as possible

**Comment by shawaj** [comment]
https://github.com/PiSupply/PiJuice/tree/master/Firmware/Source

**Comment by shawaj** [comment]
already had it sorted actually just forgot to upload!
