### ISSUE TITLE
Negative GPIO power input / current

### ISSUE THREAD

**Issue by jophut** [PiSupply/PiJuice#500]
I noticed sometimes, the status screen from the pijuice_cli gives a negative current:

I don't understand this because the system is running on battery only.

![image](https://user-images.githubusercontent.com/3954707/81949670-61512e80-9603-11ea-9fde-8824f0b4555b.png)

Currently it doesn't bother me, but I just wanted to let you know.
Maybe you have a explanation for this situation?
Could it simple be a faulty AD-conversion?

Edit:
I'm using:
Firmware version 1.4
Pijuice-base version 1.6
Also I noticed that while charging via the micro USB connected to the PiJuice the "Battery:" line in the pijuice_cli frequently switches between "NORMAL" and "CHARGING_FROM_IN"
I'm using an "official Raspberry Pi power supply" with an output of 2.5A @ 5.1V

**Comment by tvoverbeek** [comment]
@jophut There is no AD conversion. The current is estimated by an algorithm in the PiJuice firmware. I do not know the details, but I've seen this switching regularly on my own PiJuice.
So nothing to worry about,

**Comment by shawaj** [comment]
Does it go to positive when you plug in power to the RasPi microUSB?

I guess this means it is drawing 1.206A of power from the PiJuice, rather than a positive number which would mean it is supplying power from the GPIO to the PiJuice.

Just a thought - I am not sure this is the case.

**Comment by shawaj** [comment]
@tvoverbeek do you think it's worth documenting this algorithm? Could ask Milan if so

**Comment by tvoverbeek** [comment]
Added clarification about GPIO current sign to both GUI and CLI sections of the README. (https://github.com/PiSupply/PiJuice/commit/d3c193c9f40ffc2f45cdb9304cd7c59ee46952b2).
Closing the issue.
