### ISSUE TITLE
Pijuice zero input voltage range

### ISSUE THREAD

**Issue by armandoamore** [PiSupply/PiJuice#520]
Hi. I’ve seen that the pijuice hat allows 4.2v to 10v as voltage input. What about the pijuice zero? What are the input voltage range over Micro USB. I’m planning to power it by usb solar panel which maximum voltage output is about 7.5V. Is it ok?

**Comment by tvoverbeek** [comment]
The PiJuice Zero has the same circuitry so the allowed input is also 4.2 - 10V
