### ISSUE TITLE
Fastest way to charge the 12,000 mAh battery

### ISSUE THREAD

**Issue by zt4** [PiSupply/PiJuice#529]
I was wondering how I should charge the external 12,000 mAh battery the fastest?

Does charging via the J4 connector with a higher voltage than the 5V that USB uses, allow faster charging? Does 6V or 9V on the J4 connector help? Or are there other limitation to the power actually going into the battery?

From the datasheet, it looks like it probably won't help with higher input voltage, but does the J4 connector allow 2.5A max and the USB connector only allow 1.5A max?

I don't have the 12,000mAh battery yet, but with the BP7X battery, I've only ever recorded approx 1.5A input, but that could also be a limitation of that battery size.

Thanks!

**Comment by tvoverbeek** [comment]
The J4 and PiJuice USB connectors are in parallel. Only the power lines of the PiJuice USB connector are used and thus can also take up to 2.5A. Input voltage on the PiJuice USB or J4 is 4.5-10V.
The charge controller chip (BQ24160) can deliver up to max 2.5A charging current.
Typical charge current for a LiPo is 0.5C. For the BP7X (1820mAh) this would be 910mA.
For the 12000mAh t could be 6A, but the charge controller can only deliver 2.5A. The 2.5A charging current is also what is specified in the battery profile for the 12000mAh.
More details in the hardware README and the BQ24160 datasheet (https://github.com/PiSupply/PiJuice/blob/master/Hardware/Datasheets/BQ24160RGET.pdf)
