### ISSUE TITLE
Using IO2 (button) as both a wakeup pin as well as a digitalinput in python

### ISSUE THREAD

**Issue by lanewinfield** [PiSupply/PiJuice#535]
Hiya,

Curious to know how best to do this. Would love to have a button that has two functions:

1. To boot the PiJuice/Pi up from off
2. To be used as a DigitalInput inside of a python script

I've successfully hooked it up to do both, but I find that pressing/holding the button triggers a shutdown/restart sequence when the Pi is already on. When it's on, I only want it to react as per my scripting in python.

Any thoughts on **how to disable IO2's "wakeup" feature when the PiJuice/Pi are already on**?

**Comment by shawaj** [comment]
@lanewinfield closing this now as haven't heard from you in a while so assuming you're all sorted now. Reply back if not
