### ISSUE TITLE
Use of IO pins on P3

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#54]
Nice that you can configure the IO pins in the GUI.
These are 2 unused GPIOs on the STM32.
It is not documented how to get input and output from these STM32 GPIOS.

**Comment by shawaj** [comment]
@mmilann any ideas about this?

**Comment by mmilann** [comment]
There are api python functions implemented in pijuice.py for dynamic IO access. Here are usage examples:
print pijuice.status.GetIoAnalogInput(1) # Get analog input value from IO1 in milivolts,
print pijuice.status.GetIoDigitalInput(2) # Get digital input value from IO2
pijuice.status.SetIoDigitalOutput(1, 1) # Set digital output value 1 to IO1
pijuice.status.SetIoPWM(2, 35.6) # Set pwm duty circle to 35.6% for IO2
print pijuice.status.GetIoPWM(1) # Get current pwm duty circle at IO1

**Comment by tvoverbeek** [comment]
Only added last week.
We still need to document the accessible user functions in pijuice.py (API document???)

**Comment by shawaj** [comment]
@ChristopherRush could you take a look at this, when you have a moment?

**Comment by ChristopherRush** [comment]
b55baa1569c55e519ca48b45e66627e45a4b0fff
