### ISSUE TITLE
Communication_error while using pijuice zero

### ISSUE THREAD

**Issue by JoshYang1977** [PiSupply/PiJuice#540]
Hello,

I have a communication_error while using pijuice zero.
I used  i2cdetect -y 1 and found nothing.
Already used all other methods mentioned in other posts.

Any suggestion? I use Pi Zero to install the pijuice zero
thank you very much.

Josh

**Comment by JoshYang1977** [comment]
I just found an error occurs

i2c-dev not found in dictionary /lib/modules/4.19.97+

any suggestion? thanks.

**Comment by JoshYang1977** [comment]
now I refresh os and i2c-dev not found in dictionary /lib/modules/4.19.97+ does not occur.
However, i2cdetect -y 1  still finds nothing. Below are pictures to show the current status.

thanks

![IMG_0414](https://user-images.githubusercontent.com/43284414/91987362-88716e80-ed60-11ea-893a-5c5f27038525.PNG)
![IMG_0415](https://user-images.githubusercontent.com/43284414/91987380-8d362280-ed60-11ea-8d96-a46c93148e7b.JPG)
![IMG_0416](https://user-images.githubusercontent.com/43284414/91987394-932c0380-ed60-11ea-985d-66740f6fee7c.JPG)

**Comment by ChristopherRush** [comment]
How have you physically connected the board? Do you have a photo?

**Comment by JoshYang1977** [comment]
Chris,

Thank you very much for your response. I uploaded the pictures in my previous comment.
Finally, I figured that out and make it works. Basically, the pi zero is something broken and I have it installed in a new one. Now it is working. Thank you very much.

Josh
