### ISSUE TITLE
PiJuice 2500mAh battery missing in battery profile

### ISSUE THREAD

**Issue by hostingnuggets** [PiSupply/PiJuice#541]
Hello,

I just got a PiJuice 2500mAh battery (PIS-0379) for my Raspberry Pi 0W and noticed that in the PiJuice CLI this battery profile is missing.

Could you please add it? and in the mean time let me know the exact specifications so that I can at least a a custom profile where I manually enter all parameters?

Many thanks in advance.

**Comment by tvoverbeek** [comment]
Suggest to use the 2300mAh profile.

**Comment by hostingnuggets** [comment]
@tvoverbeek you mean the SNN5843_2300 one?

**Comment by tvoverbeek** [comment]
Yes

**Comment by hostingnuggets** [comment]
Thank you for confirming.
