### ISSUE TITLE
power thru the raspi USB

### ISSUE THREAD

**Issue by pescadorj** [PiSupply/PiJuice#550]

**Comment by pescadorj** [comment]
When the power is supplied thru the raspi USB port the battery is not charged no blue led flashing. Is it possible that the supplied voltage is lower then the voltage supplied to the GPIO pins? What should the  the voltage be at a minimum?
Raspberry pi 3B pijuice firmware 1.4. Should work without a pogo pin, right?

**Comment by tvoverbeek** [comment]
I guess he found the 'GPIO input enabled' setting

**Comment by shawaj** [comment]
@pescadorj closing as it seems you resolved. If not please let us know

**Comment by pescadorj** [comment]
More or less. If de power supply voltage on the raspi usb is lower then 5.2v the pijuice can not charge the battery, led is not flashing blue.Regards Jan VisserVerzonden vanaf Samsung-tablet.
-------- Oorspronkelijk bericht --------Van: Aaron Shaw <notifications@github.com> Datum: 24-10-20  02:37  (GMT+01:00) Aan: PiSupply/PiJuice <PiJuice@noreply.github.com> Cc: pescadorj <jt.visser@hccnet.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [PiSupply/PiJuice] power thru the raspi USB (#550) 
@pescadorj closing as it seems you resolved. If not please let us know

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PiSupply/PiJuice/issues/550#issuecomment-715644182",
"url": "https://github.com/PiSupply/PiJuice/issues/550#issuecomment-715644182",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
