### ISSUE TITLE
J5 Momentary Switch wiring

### ISSUE THREAD

**Issue by DazFahy** [PiSupply/PiJuice#560]
I have connected a [momemtary button](https://www.adafruit.com/product/559) to J5 via the buttons NC1 and C1 connectors. Does it matter which way round the wires connect to J5?

It is not turning the Pi on/off but SW1 is.

**Comment by ChristopherRush** [comment]
How have you wired up the button as it can be done as Normally Open or Normally Closed looking at the link you sent.

**Comment by DazFahy** [comment]
I have tried Normally Closed NC1 and C1, I also tried Normally Open NO1 and C1

**Comment by DazFahy** [comment]
It is working, I had just got my wiring circuit wrong.
