### ISSUE TITLE
GetWakeUpOnCharge Bug

### ISSUE THREAD

**Issue by DazFahy** [PiSupply/PiJuice#561]
During my conversion to C# I have noticed that even though the GetWakeUpOnCharge is disabled my code is saying disabled is false even though the percentage is set to 127 (0x7F).

When I have had a look at the code in pijuice.py the SetWakeUpOnCharge sets the value to 0x7F if disabled, however the GetWakeUpOnCharge is checking the value 0xFF to check for disabled.

Should'nt the GetWakeUpOnCharge be checking for 0x7F

```
    def SetWakeUpOnCharge(self, arg):
        try:
            if arg == 'DISABLED':
                d = 0x7F
            elif int(arg) >= 0 and int(arg) <= 100:
                d = int(arg)
        except:
            return {'error': 'BAD_ARGUMENT'}
        return self.interface.WriteDataVerify(self.WAKEUP_ON_CHARGE_CMD, [d])

    def GetWakeUpOnCharge(self):
        ret = self.interface.ReadData(self.WAKEUP_ON_CHARGE_CMD, 1)
        if ret['error'] != 'NO_ERROR':
            return ret
        else:
            d = ret['data'][0]
            if d == 0xFF:
                return {'data': 'DISABLED', 'error': 'NO_ERROR'}
            else:
                return {'data': d, 'error': 'NO_ERROR'}
```

**Comment by tvoverbeek** [comment]
Yes, thanks for catching this.
Fixed in Github commit https://github.com/PiSupply/PiJuice/commit/c34316570036a896c9aae1d1e95ad395d7d6a7b0
Closing the issue.
