### ISSUE TITLE
Update where to buy list

### ISSUE THREAD

**Issue by devicenull** [PiSupply/PiJuice#566]
A bunch of the links for US-based vendors in the where to buy list are dead.  For example, Newark no longer offers it for sale, and a bunch of the other vendors list 'coming soon'.

**Comment by shawaj** [comment]
@devicenull thanks very much.

@tvoverbeek @ryanteck @ChristopherRush  maybe best to remove them altogether what do you think?

**Comment by ChristopherRush** [comment]
I think we can update it based on the distrubters list on our website. We
don't necessarily need to link directly to the product page itself.

**Comment by tvoverbeek** [comment]
@devicenull means the distribution list on the main github page which has not been updated for 2 years.
Also not all distributors on https://uk.pi-supply.com/pages/distributors are selling PiJuice and PiJuice related products.
I suppose you (=Pi Supply) know the distributors to whom you shipped the PiJuice, 
So either update it or delete it altogether.
My 5 cents.

**Comment by shawaj** [comment]
Possibly easier to just Google at this point. We made the list originally to help people out when we had just started shipping. Probably served it's purpose now.

Will see what @JohnWhiting thinks and update. Will leave this issue open for now
