### ISSUE TITLE
intelligent on/off switch

### ISSUE THREAD

**Issue by mrglobetrotter0088** [PiSupply/PiJuice#568]
In the README file I read something about an intelligent on/off switch, which allows to have control on when the Raspberry Pi will be switched on or off without having to plug or unplug the PSU as you would normally have to do. I'm interested in scheduling the RPi's "get-ON" and "get-OFF" times during the day. How is this possible? How can I set this? Thanks for help.

**Comment by shawaj** [comment]
So you would like to turn the pi on and off automatically throughout the day?

For the wake up you can use the wake-up alarm functionality https://github.com/PiSupply/PiJuice/tree/master/Software#wakeup-alarm-menu

And then you can just create a script to shut down the pi as and when you want to.

Hope that helps

**Comment by mrglobetrotter0088** [comment]
Ok, thank you. I‘ll give it a try.

**Comment by shawaj** [comment]
@mrglobetrotter0088 ok let us know how you get on

**Comment by shawaj** [comment]
Closing this as no reply in quite a while. Let us know if you need any other assistance.
