### ISSUE TITLE
Change install instructions for PiJuice

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#57]
See comments here - https://github.com/PiSupply/PiJuice/commit/5973388aeff995fb44223399d4bde38d1de684d6#commitcomment-27064695

Need to get the new packages into the Raspbian repo then update the install instructions to speak about the base and GUI options.

Also need to update the manual install instructions for the same

**Comment by francesco-vannini** [comment]
Sorted in 7a6ba5824087bd8a2a50cc3d287cd96f28eefd56
