### ISSUE TITLE
Running PiJuice Python3 project in virualenv

### ISSUE THREAD

**Issue by Passiday** [PiSupply/PiJuice#571]
I have PiJuice software running on Pi Zero. Communications with PiJuice from Python3 work fine. But the main Python program of this project is running under virualenv.

When the Python complained with `No module named 'pijuice'`, I manually copied `/usr/lib/python3/dist-packages/pijuice.py` to my project root directory. But then it complained with `No module named 'smbus'`, and `pip install smbus` doesn't resolve nicely, runs into compilation errors, things get hairy.

Is there some recommended way in getting PiJuice Python module to work under virtualenv?

**Comment by shawaj** [comment]
@Passiday does virtualenv not have a way to inherit system packages?

Like this https://raspberrypi.stackexchange.com/q/9246/6025

**Comment by Passiday** [comment]
Yes, thanks, that did the trick!

**Comment by shawaj** [comment]
Awesome glad to hear it!
