### ISSUE TITLE
Documentation of cli utility

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#575]
Documentation of utility added here #518

**Comment by shawaj** [comment]
@tvoverbeek I'm thinking to document this in the main software readme. Unless you think it's better somewhere else?

**Comment by tvoverbeek** [comment]
Yes main software README is a good place to start.
Could be an introduction with more details in a README in the Utilities directory.

**Comment by shawaj** [comment]
Ok sounds good, I'll put something together

**Comment by shawaj** [comment]
@tvoverbeek @tilghman do you think this is sufficient for now?

https://github.com/PiSupply/PiJuice/blob/master/Software/Source/Utilities/README.md

**Comment by tvoverbeek** [comment]
@shawaj Looks sufficient to me.

**Comment by shawaj** [comment]
Thanks for reviewing @tvoverbeek

**Comment by tilghman** [comment]
@shawaj Looks fine to me, as well.
