### ISSUE TITLE
PIN numbers shown on the PiJuice_Zero_Schematic.PDF

### ISSUE THREAD

**Issue by ADBeasley** [PiSupply/PiJuice#576]
I'm a little concerned that the PIN numbers shown on the connection on the PiJuice Top Schematic in PiJuice_Zero_Schematic.PDF do not match the 'normal' numbering on the actual Pi board.

For example, 5v is shown on pins 1 and 3 in the diagram but 2 and 4 are normally used on the Pi.

**Comment by shawaj** [comment]
@ADBeasley it's just a quirk of the way the Pi header is set up in the PCB design software. Nothing to be concerned about
