### ISSUE TITLE
PiJuice Zero UPS hat, battery discharging, general wired behavior

### ISSUE THREAD

**Issue by kaulex99** [PiSupply/PiJuice#577]
Hardware Setup:

- Raspberry Pi Zero W
- Pijuice Zero UPS hat
- 6W Pijuice Solar Panel
- 5000mAh LIPO with NTC

What I did:

1. Put the hat on the pi
2. booted & installed pi juice software with gui then rebooted
3. set battery to 5000mAh
Battery: 
![sc2](https://user-images.githubusercontent.com/19715246/98442666-3a813a00-2106-11eb-80c4-07518f3ecdee.PNG)
Current status:
![unknown](https://user-images.githubusercontent.com/19715246/98442538-7e277400-2105-11eb-9845-e67f002bda01.png)
4. Then I plugged in the battery and the solar panel
Current status: 
![sc3](https://user-images.githubusercontent.com/19715246/98442574-ab742200-2105-11eb-9f38-d06d6e710aa3.PNG)
Status after a view **seconds**
![sc4](https://user-images.githubusercontent.com/19715246/98442588-b8911100-2105-11eb-8c90-2ca3ca650016.PNG)

As you can see the battery is discharging. I really don't know why. Solar Panel is outside on the window. (also getting a little bit hot in the sun) 
Nevertheless, the temperature of the battery is not as hot as the stats say. In reallife battery has a temp of 25-30°, stats say 91°.

Also the % of the battery is jumping fast. After a reboot the temp. is correct for a short time but then it jumps to 91°, really don't know why.

If you need further information, don't hesitate to ask.

**Comment by tvoverbeek** [comment]
A few things:
- Both GPIO power input and USB Micro power input show PRESENT. This is strange.
  In your setup I would expect only the USB power input to be present (assuming the solar array output is connected to the 
  usb micro of the PiJuice Zero 
- The varying temperatures was a known issue in the previous version of the firmware. Which firmware version are you
  running? See the firmware tab in pijuice_cli. Current version is 1.4.
- Also from the status screens it is clear the battery is not charging (battery state NORMAL, not CHARGING FROM ...)

Could you provide a picture of your setup, especially the connection between the battery and the PiJuice Zero?
Which version of Raspbian/Raspbery Pi OS are you running.
What version of pijuice-base package? (Use `apt policy pijuice-base` to find out).

**Comment by kaulex99** [comment]
@tvoverbeek 

- I forgot to say: I had connected it via a normal power supply too otherwise the pi immediately shutdown. Therefore, the GPIO is present.

- Firmware is up to date with 1.4

- yeah

`pi@raspberrypi:~ $ sudo apt policy pijuice-base
pijuice-base:
  Installiert:           1.6
  Installationskandidat: 1.6
  Versionstabelle:
 *** 1.6 500
        500 http://archive.raspberrypi.org/debian buster/main armhf Packages
        100 /var/lib/dpkg/status
`

2020-08-20-raspios-buster-armhf

For sure: 
![setup](https://user-images.githubusercontent.com/19715246/98445092-1168a580-2116-11eb-8824-0b0d442cd279.jpg)

**Comment by shawaj** [comment]
@kaulex99 which battery are you using? Is it one you bought separately or one of ours?

Is the battery connector pushed on as far as it can go? It looks like there's a bit of a gap?

Could you share a picture of the battery also?

**Comment by kaulex99** [comment]
No i bought that one extra but is was also named PiJuice 5000mAh battery 

![PXL_20201107_160622592.jpg](https://user-images.githubusercontent.com/19715246/98446097-a15d1e00-211b-11eb-90c3-664cc275f435.jpg)

**Comment by tvoverbeek** [comment]
This all looks fine.
In pijuice_cli can you check on the General tab the status of 'Charging enabled' and 'GPIO input enable'.
I suspect that charging is not enabled.
From the battery parameters you can see the charging current in the constant current charging phase is 2.5A
Your solar panel can only deliver max 1A at 5V at its usb output. So charging will take longer.
If you use your normal power adapter (connected to the Pi zero as in your picture) and disconnect the solar array see if you can charge the battery that way. That would at least confirm charging works.

**Comment by kaulex99** [comment]
I will try that, but this don't explain why the temperature sensor is measuring such a high value.

**Comment by kaulex99** [comment]
Not charging with a 1A power adapter over GPIO
![grafik](https://user-images.githubusercontent.com/19715246/98462529-4546d800-21b5-11eb-902b-835409a0d1e7.png)
I have also added another power adapter on the Pi hat, not charging either.
![grafik](https://user-images.githubusercontent.com/19715246/98462566-7aebc100-21b5-11eb-8292-2b39f40bfb45.png)

**Comment by kaulex99** [comment]
Interesting thing happened just now. I disconnected the battery and connected it again. Suddenly it is charging, 1...2...%, also temp is ok with 25°.

After 3s it jumps to 91° not charging anymore. 

I did that once again battery now 99% charged wich is obviously not possible. 
![grafik](https://user-images.githubusercontent.com/19715246/98463309-9c9b7700-21ba-11eb-820c-cc9b947955a4.png)

After a view more seconds 
![grafik](https://user-images.githubusercontent.com/19715246/98463326-c48ada80-21ba-11eb-8909-190b1c1e57bb.png)

**Comment by shawaj** [comment]
@kaulex99 a 1A power adapter is probably not sufficient to power the Pi and charge the battery. You should ideally be using a 2.5A or 3A power supply.

What you've described sounds like possibly a loose connection somewhere. Does moving the battery around cause any similar changes? I wonder if there is a loose cable.

Do you have another battery you can test with also?

**Comment by kaulex99** [comment]
@shawaj Sadly, I don't have another battery. I could order one in case we don't have another solution.

Moving the battery around does not help too.

I thought the Pi Zero is not consuming that much energy, anyway, I tried a 3A one and it didn't work too 😢 I am running out of ideas maybe the battery is faulty as you mentioned.

**Comment by tvoverbeek** [comment]
If the firmware believes the high temperature it will stop charging the battery.
Go to the Battery Profile tab in pijuice_cli and scroll all the way down.
Change the "Temperature sense" to NOT_USED.
The firmware then will see a fixed temperature of 25 deg.
Then with the larger power supply uou should see charging.
You definitely seem to have a problem with the NTC battery temperature measurement.

**Comment by shawaj** [comment]
@kaulex99 where did you buy the battery from? I think it would be best to organise a replacement but depending on where you got it from changes the best way to do that

**Comment by kaulex99** [comment]
Bought it from [Distrelec](https://www.distrelec.com). (Austria)

**Comment by shawaj** [comment]
Can you send an email to sales@pi-supply.com with your address and a link to this issue and you purchase receipt. I'll get a new one shipped out to you.

**Comment by kaulex99** [comment]
Thank you. I have already sent the email.

**Comment by shawaj** [comment]
Just replied with tracking @kaulex99 you should receive it Tuesday or Wednesday I think.

Hopefully it might fix the issue. Let us know either way :-)

**Comment by kaulex99** [comment]
Received new battery today. Sadly, it is not working either :(((( now tmp is about 250°
![grafik](https://user-images.githubusercontent.com/19715246/98815987-47fd3380-2428-11eb-9498-c80f17766241.png)

**Comment by kaulex99** [comment]
and it is discharging too.

**Comment by kaulex99** [comment]
I have recorded it too
Starting with battery connected -> then disconnect -> then connect again
![ezgif-5-867e38947a26](https://user-images.githubusercontent.com/19715246/98817450-66642e80-242a-11eb-87b5-4fce7dd58d3c.gif)

**Comment by shawaj** [comment]
@tvoverbeek what do you think? Maybe the PiJuice Zero itself is the issue?

**Comment by tvoverbeek** [comment]
I would still like to know what happens if @kaulex99 puts the "Temperature sense" to NOT_USED.
See my comment above (https://github.com/PiSupply/PiJuice/issues/577#issuecomment-723582039).
Something is wrong with the temperature measurement.

**Comment by kaulex99** [comment]
Oh sorry, I forgot that.

**Comment by kaulex99** [comment]
@tvoverbeek charging as it should (disabled ntc), I will try it tomorrow with the solar panel too. Nevertheless, I use a 3A power supply now and it still weak sometimes, don't know why. Any ideas? 

Furthermore, I checked the battery connector on the board with my multi. All seems connected fine. 
![grafik](https://user-images.githubusercontent.com/19715246/98831915-771da000-243c-11eb-9d2b-d977fa9b83e6.png)

**Comment by tvoverbeek** [comment]
Note that the charge current for the 5000mAh is 2A. Then there is the overhead of the power conversions on the PiJuice Zero and with a RPi consumption of 1A it could be marginal from the batteries point of view.
A bit suspicious is the GPIO power input voltage. It is below 5V. Now it is charging it shows only 4.84V. When not charging it shows 4.96V. Smells like the 5V leads of your power supply have a too high resistance for the current asked.
Here is my screen (for the default BP7X 1820mAh):
<img width="451" alt="Screenshot 2020-11-11 at 18 38 40" src="https://user-images.githubusercontent.com/1197294/98845128-8d802780-244d-11eb-8acb-ad6fa4fa9778.png">

Anyway there is something wrong with measuring the temperature with the internal NTC of the battery.
Since you have the same problem with 2 different batteries it is probably a bad contact or a pcb trace on the PiJuice Zero.
@shawaj Maybe time to offer @kaulex99 a replacement PiJuice Zero???

**Comment by shawaj** [comment]
@kaulex99 can you let me know the support ticket number from previous email you sent?

**Comment by kaulex99** [comment]
@shawaj Sure: 119939

**Comment by kaulex99** [comment]
@tvoverbeek looks like the voltage is ok currently.
![grafik](https://user-images.githubusercontent.com/19715246/98846412-4bf07c00-244f-11eb-9b5e-9ddb29c3b836.png)

**Comment by tvoverbeek** [comment]
This is with the solar panel? Looks ok. 0.158A is the current (not an actual measurement, but an estimate) going to the Pi.
Note the voltage 5.09V which is the output from the 5V converter on the PiJuice Zero.

**Comment by kaulex99** [comment]
No, I will try the solar panel tomorrow. Currently it is night in Austria so I don't have a good lighting situation :D

**Comment by tvoverbeek** [comment]
@kaulex99 I can confirm it is dark here. I am living in Fieberbrunn, Tirol.

**Comment by kaulex99** [comment]
@shawaj Shall I get in touch with you via email?

**Comment by shawaj** [comment]
@kaulex99 have emailed you. Replacement PiJuice Zero shipping out tomorrow.

**Comment by kaulex99** [comment]
@tvoverbeek out of question:  Do you think it is possible to run a pi zero with 5000mAh battery and a 22W solar panel 24/7 in austria or do I need a larger panel? 

@shawaj Thank you!

**Comment by tvoverbeek** [comment]
Depends on what your pi zero (not zero w??) is doing 24/7. Makes a huge difference if it is on only a few minutes per hour or continuously. A full 5000 mAh battery will not last 24 hours when the pi zero is on continuously.
When it is off for a considerable time then the solar panel has a chance to charge the battery.
Have you seen the battery discharge calculator https://learn.pi-supply.com/battery-levels/?
Anyway you definitely need a larger solar panel to get a charging current of > 2A for the periods when the pi zero is off.

**Comment by kaulex99** [comment]
@tvoverbeek overbeek zero w yeah, forgot the W sorry.
The site says 23.13 hours. With a solar panel which produces enough power, this should work. 

What do you mean with off? It should never be off. It should run 24/7.

**Comment by tvoverbeek** [comment]
You wrote;
```
What do you mean with off? It should never be off. It should run 24/7.
```
A scenario like this: a few measurements every 5 minutes. Most of the time the Pi Zero will be idle then. Using repeated wakeup you could shut down the Pi after the measurements are done (and stored or sent somewhere). During the off time the solar panel can charge the battery much more eggectively.

Your solar panel calculations do not take into account the conversion losses to get to the 5V output. As usual solar array capacity is the raw output from the panel, not the regulated output. Moreover there are also conversions on the PiJuice so you might lose 20 to 30%.

**Comment by kaulex99** [comment]
@tvoverbeek @shawaj  new pi hat 😢 still 248°
![grafik](https://user-images.githubusercontent.com/19715246/99383710-8edaa580-28ce-11eb-99a0-390e07fe6174.png)

**Comment by shawaj** [comment]
Hmm very strange. Do you have another Pi, SD card and power supply you could try?

**Comment by kaulex99** [comment]
Yes I will replace everything and check it again. Really strange

**Comment by shawaj** [comment]
@kaulex99 thanks very much keep us posted

**Comment by kaulex99** [comment]
Update: New SD Card with fresh raspian os and newest version of pijuice-base 
![grafik](https://user-images.githubusercontent.com/19715246/99814344-264b2d00-2b49-11eb-8917-0aa2e6c88fc7.png)

**Comment by kaulex99** [comment]
@shawaj finally, everthing is working - I checked the pi hat with another power supply and another pi (PI 2B+) and it is working like a charme. Today I'll get a new raspberry pi zero w too. Then I can check if the problem is generally with the pi zero.
![grafik](https://user-images.githubusercontent.com/19715246/100214497-40518a80-2f10-11eb-8a2c-44c23b007998.png)

**Comment by kaulex99** [comment]
@shawaj had to delete my previous comment. It is not working with another pi and another power supply of 3A. (PI 2B+)
still 240°.

**Comment by kaulex99** [comment]
To close this issue: Firmware Version 1.5 solved the issue with the temperature.

Thank you for you help.
