### ISSUE TITLE
Using both charging sources. 

### ISSUE THREAD

**Issue by fharryx** [PiSupply/PiJuice#582]
What would happen if both charging sources would supply power?

**Comment by shawaj** [comment]
You mean using a power supply in both the Pi micro USB and the PiJuice micro USB?

Or something else?

**Comment by fharryx** [comment]
Yes, that is exactly what I mean!

**Comment by tvoverbeek** [comment]
The strongest one wins. See this part of the schematic:
<img width="134" alt="Screenshot 2020-11-14 at 17 42 15" src="https://user-images.githubusercontent.com/1197294/99152240-d24fcc80-26a0-11eb-970a-89a530e48e34.png">
The CS1 and CS2 go to the microcontroller.

**Comment by shawaj** [comment]
@fharryx as Ton has said.

It's ok to plug into both at the same time.

Some people plug one into mains and one into a solar panel for example.

Do you have any other questions or can we close the issue?

**Comment by fharryx** [comment]
Thank you very much! My question is answered.

**Comment by shawaj** [comment]
Perfect thanks very much 🤠
