### ISSUE TITLE
Minor issue wit the author line in changelogs

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#59]
The build procedure complains about the author line in the changelogs.
This is because there is no indent before the '--'
Adding a 2 space indent before the '--' will include the line in the package changelogs.

**Comment by DenisKhrutsky** [comment]
Saw that warning and couldn't figure what was the reason. Tried different options with tabs/spaces but for some reason missed the obvious. Consider this fixed.
