### ISSUE TITLE
postinst in pijuice-base does not restart service if previous version was running

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#60]
The logic in postinst to (re)start the service only takes care of the case when the service is not running yet.
If it is already running it will not be restarted.
This logic only works because updating to the next version will stop the service in postrm.
However pijuice-1.0 does not stop it when it is removed.
Suggest to always run the unmask, enable, restart steps.
Does not harm when already unmasked and enabled.

**Comment by DenisKhrutsky** [comment]
Resolved in [#13c1fb](https://github.com/PiSupply/PiJuice/commit/13c1fb8cab22937051675f54e915f7c0e1680f78)
