### ISSUE TITLE
PiJuice  3D models

### ISSUE THREAD

**Issue by kubiaj** [PiSupply/PiJuice#602]
Hi HW developers,
could you release a 3D models for PiJuice + PiJuice Zero or release some documentation with dimensions? As you are probably already using Altium designer it should be very easy to generate a 3D model in STEP format. 

It would be very helpful to have this as Im trying to do custom modification  of some case and without the dimensions I don't know where to create holes for LEDs and etc.

**Comment by shawaj** [comment]
See here https://github.com/PiSupply/PiJuice/tree/master/Hardware/3D

**Comment by hugokernel** [comment]
All PDF files in the hardware/3D section are empty.

**Comment by shawaj** [comment]
> All PDF files in the hardware/3D section are empty.

You need to download them and view them in Adobe reader or Adobe acrobat.

They don't work on GitHub viewer as they are 3d pdf files
