### ISSUE TITLE
Service complains about configData when started

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#61]
When pijuice_sys.py is started `systemctl status pijuice.service` reports:
```
Jan 24 19:20:31 rpi-stretch-full systemd[1]: Started PiJuice status service.
Jan 24 19:20:31 rpi-stretch-full pijuice_sys.py[2441]: /usr/bin/pijuice_sys.py:163: SyntaxWarning: name 'configData' is used prior to global declaration
Jan 24 19:20:31 rpi-stretch-full pijuice_sys.py[2441]:   global configData
```
Move global configData (or all global declarations in main()) up before line 158

**Comment by DenisKhrutsky** [comment]
Resolved in [#1d7b90](https://github.com/PiSupply/PiJuice/commit/1d7b90ba5ca6410052da064416bf9525be0994d7)
