### ISSUE TITLE
Battery profiles in software section README?

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#62]
@francesco-vannini is it intentional that at the bottom of the software readme there is a section about battery profiles? https://github.com/PiSupply/PiJuice/blob/master/Software/README.md#battery-profiles

**Comment by shawaj** [comment]
Maybe that data could be moved elsewhere and would be more at home?

Also - on this part about the battery config menu - https://github.com/PiSupply/PiJuice/blob/master/Software/README.md#pijuice-hat-config-battery-menu

I think ideally we should provide more information about what all the settings are / where they come from...and crucially - which are optional and which are required?

**Comment by francesco-vannini** [comment]
Yes that bit needs sorting, as for the GUI tab I'll add a link to https://github.com/PiSupply/PiJuice/tree/master/Hardware#battery-profiles

**Comment by shawaj** [comment]
What do you mean about the GUI tab?

**Comment by francesco-vannini** [comment]
The one you pointed out https://github.com/PiSupply/PiJuice/blob/master/Software/README.md#pijuice-hat-config-battery-menu

**Comment by shawaj** [comment]
I'm confused about what you're suggesting but ok :-)

**Comment by francesco-vannini** [comment]
Sorted in 995216cccee26e668c34ac052f419e70541fa91c
