### ISSUE TITLE
battery discharging too fast

### ISSUE THREAD

**Issue by sevdh** [PiSupply/PiJuice#631]
I use a combination of the Pi 3B+ and the PiJuice. The Pi is powering up every hour and shuts down 2 minutes later. In these two minutes the battery voltage and charge is monitored and logged.
With a fully charged battery (the standard one coming with the PiJuice) the battery charge goes down about 15% every hour (although the Pi only runs for two minutes). I would expect the charge to go down much much slower.

What could be causing this fast discharge?

Just in case: there are no peripherals connected to the Pi during the tests.

Best regards! Edwin

**Comment by tvoverbeek** [comment]
How do you shut down the Pi at the end of your 2 minutes run?
If you do not explicitly remove the 5V power from the PiJuice to the Pi, the P 3B+ remains powered (red power led on Pi stays on).
In that case the battery keeps discharging during the whole hour.

**Comment by sevdh** [comment]
You are right, I’m using a sudo shutdown in the shell and the red led stays on.

Am I right to assume I should use the SYS_FUNC_HALT_POW_OFF script instead?

On 23 Jan 2021, at 13:38, Ton van Overbeek <notifications@github.com> wrote:

﻿
How do you shut down the Pi at the end of your 2 minutes run?
If you do not explicitly remove the 5V power from the PiJuice to the Pi, the P 3B+ remains powered (red power led on Pi stays on).
In that case the battery keeps discharging during the whole hour.

**Comment by tvoverbeek** [comment]
You cannot call SYS_FUNC_HALT_POW_OFF yourself, it is an event sent by the PiJuice and handled by the pijuice service (system task).
Instead on the System Task tab in the GUI or CLI enable 'Software Halt Power Off' and set a long enough delay to give the Pi enough time to complete the shutdown before the power disappears.
I usually specify 20 seconds. The service will then command the PiJuice to remove the 5V after e.g. 20 seconds when the shutdown (commanded externally) is already in progress.

Zou moeten werken in dit geval.

**Comment by sevdh** [comment]
I’m sorry not to have understood this function.

It works like a charm.

Thanks a lot.

Het werkt perfect!

On 23 Jan 2021, at 13:58, Ton van Overbeek <notifications@github.com> wrote:

﻿
You cannot call SYS_FUNC_HALT_POW_OFF yourself, it is an event sent by the PiJuice and handled by the pijuice service (system task).
Instead on the System Task tab in the GUI or CLI enable 'Software Halt Power Off' and set a long enough delay to give the Pi enough time to complete the shutdown before the power disappears.
I usually specify 20 seconds. The service will then command the PiJuice to remove the 5V after e.g. 20 seconds when the shutdown (commanded externally) is already in progress.

Zou moeten werken in dit geval.

**Comment by JolleJolles** [comment]
Happy to have found this threat as I had exactly the same issue. This is NOT clear from the documentation so should be clarified ideally. 

I was also wondering if this is possible to do via a USER_FUNC python script rather than using the PiJuice services. For example, I have a script that automatically turns off the Raspberry Pi. Could I then not add the following to do the same as the service as you describe above:

```
time.sleep(30)
pijuice.power.SetSystemPowerSwitch(0)
```

**Comment by shawaj** [comment]
@JolleJolles do you have any suggestions for how we could document this better? Open to ideas :-)
