### ISSUE TITLE
Pijuice 12000mAh battery Fault: charging temperature suspend, with firmware 1.4

### ISSUE THREAD

**Issue by salimness** [PiSupply/PiJuice#637]
Right out of the box I get this fault with temperatures over 200 degrees. Had this issue so far with 3 brand new 12000mAh batteries. The 1820 mAh battery works fine.  
I update first using this command and select the appropriate profile:
apt-get -y install pijuice-base pijuice-gui 

Do I just have a bad batch of batteries? 

<img width="555" alt="Screen Shot 2021-02-05 at 10 01 25 AM" src="https://user-images.githubusercontent.com/69279516/107050587-665d9b80-6799-11eb-8b58-16a2f7e41b35.png">
<img width="543" alt="Screen Shot 2021-02-05 at 10 01 48 AM" src="https://user-images.githubusercontent.com/69279516/107050588-665d9b80-6799-11eb-860f-48ba97320fda.png">
<img width="520" alt="Screen Shot 2021-02-05 at 10 02 05 AM" src="https://user-images.githubusercontent.com/69279516/107050589-665d9b80-6799-11eb-9c7c-c6dd8eadb8e3.png">

**Comment by BoelD** [comment]
This is a known issue. Search in the closed issues here, for extra details. For now, a workaround is to disable the NTC. You can choose to measure the onboard temperature, or measure no temperature at all.

**Comment by BoelD** [comment]
[https://github.com/PiSupply/PiJuice/issues/617](url)
[https://github.com/PiSupply/PiJuice/issues?q=is%3Aissue+temperature](url)

**Comment by salimness** [comment]
Thank you very much for the quick response.

**Comment by shawaj** [comment]
@salimness please change the battery NTC to NOT_USED in HAT battery menu

**Comment by shawaj** [comment]
Oh thanks @BoelD 👌
