### ISSUE TITLE
pijuicetest.py no longer contains examples of setting LED2

### ISSUE THREAD

**Issue by jealousofyou** [PiSupply/PiJuice#638]
The Hardware readme section on the LEDs suggests that pijuicetest.py shows examples of how LED2 can be configured.

New versions of the script have had the examples stripped out. Either the readme should be corrected or perhaps some documentation or examples of the relevant functions could be provided somewhere.

**Comment by tvoverbeek** [comment]
See https://github.com/PiSupply/PiJuice/tree/master/Software#pijuice-status the SetLedBlink function

**Comment by tvoverbeek** [comment]
See the description fo the SetLedBlink function in the Status section of the Software README (https://github.com/PiSupply/PiJuice/tree/master/Software#pijuice-status).
Also corrected in the hardware README.
