### ISSUE TITLE
PiJuice/Software/Test README?

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiJuice#64]
@francesco-vannini the README here - https://github.com/PiSupply/PiJuice/tree/master/Software/Test

Does not make a huge amount of sense as to what it is for etc.

Thoughts about refactoring that?

**Comment by francesco-vannini** [comment]
This is linked to #49 I'll move it there so that the discussion can be continued for all. The short answer is that I don't know why those files are there hence why I was asking
