### ISSUE TITLE
Latest firmware stable and downgrade

### ISSUE THREAD

**Issue by rascalos** [PiSupply/PiJuice#645]
Hello,
I Would like to know what is the lastest firmware stable version, please ?
Is it possible to downgrade a firmware version ? how to do for ?
Some PiJuice with V1.4 firmware seem have issue whereas not in V1.3.
In the first time, I would like upgrade with the latest firmware stable before to downgrade.
Thanks for help.

**Comment by tvoverbeek** [comment]
V1.4 is the last stable firmware.

**Comment by rascalos** [comment]
Should I use the firmware installation process to downgrade the firmware version as explained here https://github.com/PiSupply/PiJuice/tree/master/Firmware#update-pijuice-firmware ?
Thanks for your help.

**Comment by tvoverbeek** [comment]
Yes. With pijuiceboot you can install any version of the firmware.
I guess you are aware that they are available at https://github.com/PiSupply/PiJuice/tree/master/Firmware

**Comment by rascalos** [comment]
Thanks a lot.
Pascal
