### ISSUE TITLE
misaligned labels

### ISSUE THREAD

**Issue by mmilann** [PiSupply/PiJuice#65]
IO config should be split in 4 rows so there is place for parameter name label for IO config case with two additional parameters.
![io_tab_bug](https://user-images.githubusercontent.com/20090622/35400813-1f7be50a-01f8-11e8-893f-c8228928c8e8.jpg)

**Comment by DenisKhrutsky** [comment]
Fixed in [#c0c013](https://github.com/PiSupply/PiJuice/commit/c0c013826224a8642564de27fecd9ea460ee85db)
