### ISSUE TITLE
Question for hot swaping?

### ISSUE THREAD

**Issue by klint-k** [PiSupply/PiJuice#67]
if the power cable is on the Raspberrypi and a person tries to hot swap the battery on the PiJuice will there be a shutdown command sent through the pogo?

**Comment by shawaj** [comment]
Depends how you have it set up. There can be if you want

**Comment by klint-k** [comment]
Is the setup  software?
or: 
Do you have to have the power input going to  the PiJuice?

How is the setup?

**Comment by shawaj** [comment]
No idea what you mean?

You can set it up however you want from the software.
