### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by jglavrsen** [PiSupply/PiJuice#673]
There is an event you can set up if there is a power loss - but is there a similar one for when the power is back ??? What have I not seen in the manual?

**Comment by tvoverbeek** [comment]
There is no 'power back` event. But you can use 'wakeup-on-charge' as a replacement (kind of).
When power is back the battery charging will continue.

**Comment by jglavrsen** [comment]
Ok, I just want to see if it can meet the requirements we have for what we are going to use it for
Thanks for the quick reply
