### ISSUE TITLE
Is there a PiJuice for the Raspberry Pi 4

### ISSUE THREAD

**Issue by kn1gh7h4wk** [PiSupply/PiJuice#674]
Hello,

I was just wondering if there have been any new hats or firmware updates to allow the PiJuice to properly power the rPi4 to 3A+. I’ve had mine for a while hate that I can’t use it because of this issue. My pi handles disaster communications in the field and would benefit from a PiJuice that can put out the requirements of the rPi4. 

Thanks!

**Comment by shawaj** [comment]
The PiJuice HAT will work fine with a Pi 4 already. You may want to add a larger battery but other than that it already works.

3A isn't necessary for most applications, so the limit of 2.5A on the current hat is not really a major issue.

Also see #580 where we are working on updated hardware.
