### ISSUE TITLE
V1.5 Firmware source code not available

### ISSUE THREAD

**Issue by thesteg** [PiSupply/PiJuice#682]
Hey, is it possible that I have missed where it in the repo is or could it be made available? 

Steg.

**Comment by shawaj** [comment]
@mmilann can you provide it?

**Comment by shawaj** [comment]
@thesteg https://github.com/PiSupply/PiJuice/commit/7f5c39f1486213b9a3c5cf7ed0d15b675fdd443e

**Comment by thesteg** [comment]
Tiptop. Many thanks.

**Comment by tvoverbeek** [comment]
Renamed the Source directory to Sources-V1.5_2021_02_06 to be consistent with previous sources (zip files)

**Comment by thesteg** [comment]
@shawaj @tvoverbeek I've corrected some of the more serious compiler warnings and a couple of bugs, do you want me to create a pull request?

**Comment by tvoverbeek** [comment]
@thesteg Please submit them. @mmilann Can you take a look when they are submitted?
