### ISSUE TITLE
Is it possible to know the configuration of the DIP switches from a script?

### ISSUE THREAD

**Issue by rascalos** [PiSupply/PiJuice#688]
Hello,
When deploying machines, we noticed that the DIP switches were sometimes incorrectly configured. Is there a command to know the configuration of the DIP switches that we can put in a test script  ?
Thanks for help.

**Comment by tvoverbeek** [comment]
SHort answer: No.
The dip switches together with a resistor network determine a voltage read by the MCU A/D converter. The resulting voltage determines which profile is the default profile.
See e.g. the firmare source https://github.com/PiSupply/PiJuice/blob/master/Firmware/Sources-V1.5_2021_02_06/Src/config_switch_resistor.c and also https://github.com/PiSupply/PiJuice/blob/master/Hardware/Batteries/Pijuice_battery_config.xlsx, thhe Profile Selection and Charge Selection sheets.

Note: When you select a profile in the CLI/GUI the profile setting will be kept (stored in non-volatile memory).
