### ISSUE TITLE
pijuice_cli.py: Bug in usb_power status

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/PiJuice#69]
Line 76: `usb_power = status.get('power_input', 0)`
should be
              `usb_power = status.get('powerInput', 0)`.
Now it always displays '0'

**Comment by DenisKhrutsky** [comment]
Thank you. Fixed in [#0a44af](https://github.com/PiSupply/PiJuice/commit/0a44af257c7c4c18de9519aba391862e8d384f97)
