### ISSUE TITLE
PiJuice_cli - "Another instance of pijuice settings is already running" message

### ISSUE THREAD

**Issue by alpapak** [PiSupply/PiJuice#695]
I was using putty from another machine and checking PiJuice settings. By mistake, i disconnected from the network. Now i can load settings and getting this message "Another instance of pijuice settings is already running." How can i force to close the software?

**Comment by tvoverbeek** [comment]
I assume you can log in via ssh to the RPi with the PiJucice.

Kill the instance of pijuice_cli still running:
- Find the PID of pijuice_cli: `ps ax | grep pijuice_cli | grep -v grep` 
- The output will look something like: `10882 pts/0    S+     0:00 pijuice_cli /usr/bin/pijuice_cli.py`
- Kill the process with `sudo kill -9 10882`

Then you should be able to start pijuice_cli again.

**Comment by alpapak** [comment]
Thank you.
