### ISSUE TITLE
two PiJuice 12000mAh Battery together

### ISSUE THREAD

**Issue by salimness** [PiSupply/PiJuice#721]
Hi, is it possible to connect two PiJuice 12000mAh Battery together into a Pijuice Hat? If so, do I need to create a custom profile? Thank you.

**Comment by tvoverbeek** [comment]
How? In parallel could work, but the charge and termination current values double. The HAT will not be able to deliver the max charging current (too large). In series: No

**Comment by salimness** [comment]
Yes in parallel. Will using J4 input deliver the max charging current? Thank you

**Comment by tvoverbeek** [comment]
J4 is electrically parallel to the PiJuice micro-usb connector power contacts , so the same limits apply.

**Comment by salimness** [comment]
Thank you @tvoverbeek
