### ISSUE TITLE
Third party software projects: PiJuice to MQTT

### ISSUE THREAD

**Issue by dalehumby** [PiSupply/PiJuice#741]
I have written a Python script to get PiJuice information and send to MQTT, for use in Home Assistant and Node-RED automations. Full usage and installation instructions are in the readme.

https://github.com/dalehumby/PiJuice-MQTT

I have been looking for something like this for a while but didn't find anything suitable for my setup., so decided to write my own. Feedback, ideas, PR's welcome.

Feel free to add to the "Third party software libraries and projects" section of your page.

**Comment by tvoverbeek** [comment]
Nice. Added it to the 3rd party software section.
Closing the issue
