### ISSUE TITLE
Ubuntu 21.04 (Hirsute) the dh-systemd package has been completely removed, fails to compile there because of a missing dependency

### ISSUE THREAD

**Issue by goodelyfe** [PiSupply/PiJuice#743]
Ubuntu 21.04 (Hirsute) the dh-systemd package has been completely removed, fails to compile there because of a missing dependency

**Comment by goodelyfe** [comment]
@tvoverbeek

**Comment by goodelyfe** [comment]
> The two dh-systemd-* utilities used (dh-systemd-enable, dh-systemd-start) are now included in package debhelper in Ubuntu 21.04
> Before building the pijuice packages in the control file for pijuice-base (https://github.com/PiSupply/PiJuice/blob/master/Software/Source/debian-base/control) in the Build-depends line (line 5) remove the `dh-systemd (>= 1.5)` entry.
> Hopefully that allows you to build the packages.

how can one do that? the way i tried, it still is requiring dh-systemd

**Comment by OctaneInteractive** [comment]
Hi @goodelyfe, did you make any progress?

**Comment by goodelyfe** [comment]
> Hi @goodelyfe, did you make any progress?

greetings @OctaneInteractive 

I did. I blv on a fresh install, dependency dh-python is needed in addition to the others mentioned. **_Make sure_** that you change and remove build depends (line 5) removing the dh-systemd (>=1.5) **_ON BOTH_** in debian_base & debian_gui
