### ISSUE TITLE
Will the new pins interfere?

### ISSUE THREAD

**Issue by klint-k** [PiSupply/PiJuice#76]
Will the new pins on the Raspberry Pi 3 B+ interfere with the PiJuice?

**Comment by tvoverbeek** [comment]
No, there is about 2 mm clearance between the pins and the board
Checked on 3B+ with PiJuice mounted.

**Comment by shawaj** [comment]
The only issue identified is the spring/pogo pin location has moved which we will have to address with a hardware update in the future
