### ISSUE TITLE
Force to use battery

### ISSUE THREAD

**Issue by meal** [PiSupply/PiJuice#786]
Is it possible to set PiJuice to provide power from the battery and disable powering via USB?
What I'd like to achieve is to run on battery only during the night, even as I have it connected to a working USB source.

**Comment by tvoverbeek** [comment]
I assume you mean USB power connected to the PiJuice.
Then the answer is No.

If you want to run on battery during the night then I would use a switch in the USB lead which you control via the GPIO from the RPi. Then you can programmatically block the USB power to the PiJuice during the night.
However if the RPi is not active or only moderately active during the night I would not even bother to remove the USB power to the PiJuice. But I do not know your application.
Hope this helps a litlle bit.

**Comment by meal** [comment]
Thanks a lot, I'll try with the switch, that actually makes a lot of sense.
To give you a context:

My setup is like this: PV -> controller -> 12V GEL battery (28Ah)  -> power to devices connected to the relay switch (pumps, LEDs and sensors)
The charging controller has also a USB output that I use to power RPi which has PiJuice mounted on with a 12000mAh battery.

Devices connected to gel battery are running based on certain conditions, also during the night so I'd like to put as much power from that battery to pumps, etc while RPi running on PiJuice without drawing power from USB.
