### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PiJuice#8]
![pijuice](https://user-images.githubusercontent.com/16068311/30545031-58b8fec6-9c80-11e7-8b3a-5e1f3aefd86c.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by shawaj** [comment]
![battcon](https://user-images.githubusercontent.com/3359418/31778440-93eb5900-b4e8-11e7-99ba-b1dfbc0c313e.jpg)
![j6](https://user-images.githubusercontent.com/3359418/31778443-943191f4-b4e8-11e7-87d5-0d665272d2da.jpg)

**Comment by shawaj** [comment]
![hat config battery](https://user-images.githubusercontent.com/3359418/31796652-8cb55a7a-b522-11e7-8ba3-7fdfaf2faed1.PNG)
![hat config buttons](https://user-images.githubusercontent.com/3359418/31796653-8cdbddbc-b522-11e7-9687-94c37e62a411.PNG)
![hat config firmware](https://user-images.githubusercontent.com/3359418/31796654-8d00882e-b522-11e7-8411-26955656b9bd.PNG)
![hat config general](https://user-images.githubusercontent.com/3359418/31796655-8d1d7eac-b522-11e7-9b6d-5053789aeb3e.PNG)
![hat config leds](https://user-images.githubusercontent.com/3359418/31796656-8d3eed58-b522-11e7-8ae3-d3e41d70a398.PNG)
![hat menu with battery](https://user-images.githubusercontent.com/3359418/31796657-8d5c902e-b522-11e7-862a-d54eba1eb82b.PNG)
![hat menu](https://user-images.githubusercontent.com/3359418/31796659-8d7a4b64-b522-11e7-975c-132ba909a333.PNG)
![system task menu](https://user-images.githubusercontent.com/3359418/31796660-8d99b4cc-b522-11e7-8b1c-ffe5082c4644.PNG)
![system tray](https://user-images.githubusercontent.com/3359418/31796661-8dbaebce-b522-11e7-80a9-6079670aaf01.PNG)
![systemeventsmenu](https://user-images.githubusercontent.com/3359418/31796662-8df016fa-b522-11e7-9ec5-48c9e82a5625.PNG)
![systemmenu](https://user-images.githubusercontent.com/3359418/31796664-8e246f4a-b522-11e7-951d-d9a0338c4733.PNG)
![user scripts menu](https://user-images.githubusercontent.com/3359418/31796666-8e469174-b522-11e7-8c83-46f4570f53c6.PNG)
![wakeup alarm menu](https://user-images.githubusercontent.com/3359418/31796667-8e6dad0e-b522-11e7-841b-2c670e91560a.PNG)

**Comment by francesco-vannini** [comment]
![pijuice-hat-buttons-leds](https://user-images.githubusercontent.com/16068311/33768831-94db68b0-dc1f-11e7-99d4-a06cb65b0135.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-overview](https://user-images.githubusercontent.com/16068311/33768839-9c0f441c-dc1f-11e7-9445-1933ca0e6b08.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-bottom-highlighting](https://user-images.githubusercontent.com/16068311/33771346-9be5b8b4-dc28-11e7-9abf-97fae45aa7ba.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-overview](https://user-images.githubusercontent.com/16068311/33771356-a6bb8b06-dc28-11e7-8c2e-ef6363e5c883.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-overview](https://user-images.githubusercontent.com/16068311/33771575-55e9593c-dc29-11e7-9e2c-3a0c1810c4c8.png)

**Comment by francesco-vannini** [comment]
![gui-sw-location](https://user-images.githubusercontent.com/16068311/33845719-3eab8388-de9c-11e7-8499-149e52e66b71.png)

**Comment by francesco-vannini** [comment]
![gui-icon-tray](https://user-images.githubusercontent.com/16068311/33845725-43e1d0e6-de9c-11e7-921e-64c9cceb2c96.png)

**Comment by francesco-vannini** [comment]
![gui-sw-main-hat-tab](https://user-images.githubusercontent.com/16068311/33845730-46f3ef4e-de9c-11e7-8a79-8bf64380da6f.png)

**Comment by francesco-vannini** [comment]
![gui-sw-main-hat-nobat-tab](https://user-images.githubusercontent.com/16068311/33845737-4caea1ae-de9c-11e7-848f-56b58cea3f23.png)

**Comment by francesco-vannini** [comment]
![gui-sw-main-wakealarm-tab](https://user-images.githubusercontent.com/16068311/33845741-502a4252-de9c-11e7-9ec5-ddef3ec95d91.png)

**Comment by francesco-vannini** [comment]
![gui-sw-main-systemtask-tab](https://user-images.githubusercontent.com/16068311/33845745-53cb645e-de9c-11e7-836f-9601881a3fa9.png)

**Comment by francesco-vannini** [comment]
![gui-sw-main-systemevents-tab](https://user-images.githubusercontent.com/16068311/33845747-56fca07a-de9c-11e7-8026-8de2b847f330.png)

**Comment by francesco-vannini** [comment]
![gui-sw-main-userscripts-tab](https://user-images.githubusercontent.com/16068311/33845750-5a95cdf6-de9c-11e7-8840-b6dc7f079d35.png)

**Comment by francesco-vannini** [comment]
![gui-sw-conf-general-tab](https://user-images.githubusercontent.com/16068311/33845754-5eada1e8-de9c-11e7-8102-b933247a18ca.png)

**Comment by francesco-vannini** [comment]
![gui-sw-conf-buttons-tab](https://user-images.githubusercontent.com/16068311/33845760-620ac668-de9c-11e7-8b88-7d514f925068.png)

**Comment by francesco-vannini** [comment]
![gui-sw-conf-leds-tab](https://user-images.githubusercontent.com/16068311/33845764-650c1dee-de9c-11e7-9135-f489c402f59a.png)

**Comment by francesco-vannini** [comment]
![gui-sw-conf-battery-tab](https://user-images.githubusercontent.com/16068311/33845770-682d4354-de9c-11e7-8ad0-9149058f2266.png)

**Comment by francesco-vannini** [comment]
![gui-sw-conf-firmware-tab](https://user-images.githubusercontent.com/16068311/33845771-6b55373a-de9c-11e7-9475-09b8dc8086dc.png)

**Comment by francesco-vannini** [comment]
![gui-icons-samples](https://user-images.githubusercontent.com/16068311/33846583-5aecfa60-de9f-11e7-9ba9-a322d72b94f4.png)

**Comment by francesco-vannini** [comment]
![gui-icons-samples](https://user-images.githubusercontent.com/16068311/33846687-c6faab44-de9f-11e7-8901-2a805220ac9b.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-buttons-ics](https://user-images.githubusercontent.com/16068311/33900058-345d3218-df65-11e7-9335-7973c1a7a599.png)

**Comment by francesco-vannini** [comment]
![dip-switch](https://user-images.githubusercontent.com/16068311/34769251-25c7c3b6-f5f5-11e7-971f-e93f5d4d3cc0.jpg)

**Comment by francesco-vannini** [comment]
![gui-sw-main-wakealarm-tab-new](https://user-images.githubusercontent.com/16068311/35161225-7bd18140-fd37-11e7-8889-e6715023b334.png)
![gui-sw-conf-battery-tab-new](https://user-images.githubusercontent.com/16068311/35161226-7c026f30-fd37-11e7-897a-a470e06a4c8b.png)
![gui-sw-conf-buttons-tab-new](https://user-images.githubusercontent.com/16068311/35161227-7c2194be-fd37-11e7-90ee-521a7d65813f.png)
![gui-sw-conf-firmware-tab-new](https://user-images.githubusercontent.com/16068311/35161228-7c370f24-fd37-11e7-899a-aad82b827476.png)
![gui-sw-conf-general-tab-new](https://user-images.githubusercontent.com/16068311/35161230-7caa54d4-fd37-11e7-88cb-a76b2891af4d.png)
![gui-sw-conf-io-tab-new](https://user-images.githubusercontent.com/16068311/35161231-7cc2820c-fd37-11e7-875b-b80b18c3a6ab.png)
![gui-sw-conf-leds-tab-new](https://user-images.githubusercontent.com/16068311/35161232-7cdfe4aa-fd37-11e7-9249-f02f89ea2587.png)
![gui-sw-main-hat-nobat-tab-new](https://user-images.githubusercontent.com/16068311/35161233-7cfa5fce-fd37-11e7-83ec-72a8043ee0c0.png)
![gui-sw-main-hat-tab-new](https://user-images.githubusercontent.com/16068311/35161234-7d125174-fd37-11e7-9383-e2e80044258d.png)
![gui-sw-main-systemevents-tab-new](https://user-images.githubusercontent.com/16068311/35161235-7d31d544-fd37-11e7-92b4-dc0ccab55c56.png)
![gui-sw-main-systemtask-tab-new](https://user-images.githubusercontent.com/16068311/35161236-7d4e6f56-fd37-11e7-9209-7943e88a76d5.png)
![gui-sw-main-userscripts-tab-new](https://user-images.githubusercontent.com/16068311/35161237-7d653b8c-fd37-11e7-9a1e-be8b71e27a27.png)

**Comment by francesco-vannini** [comment]
![pijuice-software](https://user-images.githubusercontent.com/16068311/35162363-00d2e1a6-fd3b-11e7-8da3-b6d65e7d300e.png)

**Comment by shawaj** [comment]
Did you intend for this to go on JustBoom repo?

**Comment by shawaj** [comment]
Ignore me! For some reason my phone told me it was JustBoom repo. It is not!

**Comment by francesco-vannini** [comment]
![gui-sw-conf-firmware-tab-new](https://user-images.githubusercontent.com/16068311/35274166-0879d4a0-0033-11e8-8d49-628c27d727f8.png)

**Comment by francesco-vannini** [comment]
![gui-sw-location](https://user-images.githubusercontent.com/16068311/35343402-7a362126-0122-11e8-9961-0b7013453f3f.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-overview](https://user-images.githubusercontent.com/16068311/36384527-7d562e2c-1587-11e8-81d1-d78835ff8e67.png)

**Comment by shawaj** [comment]
![image](https://user-images.githubusercontent.com/3359418/37776742-e1fd155c-2ddd-11e8-85a7-460377883496.png)

**Comment by francesco-vannini** [comment]
![pijuice-hat-overview](https://user-images.githubusercontent.com/16068311/53577635-47e6d280-3b76-11e9-8b91-c8111b53da4c.png)

**Comment by francesco-vannini** [comment]
![NatureJuice-PIR-Mod](https://user-images.githubusercontent.com/16068311/54878254-63b65f00-4e2a-11e9-922e-37ad1f833c22.jpg)

**Comment by ChristopherRush** [comment]
<img width="518" alt="Screen Shot 2019-09-04 at 18 43 16" src="https://user-images.githubusercontent.com/1878314/64279139-47286200-cf46-11e9-877e-5062b60e8b44.png">

**Comment by ChristopherRush** [comment]
<img width="682" alt="Screen Shot 2019-09-04 at 19 17 35" src="https://user-images.githubusercontent.com/1878314/64280401-f23a1b00-cf48-11e9-9a3f-21e7211a72e1.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 21 21" src="https://user-images.githubusercontent.com/1878314/64280524-39281080-cf49-11e9-9779-e19f7499e241.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 22 24" src="https://user-images.githubusercontent.com/1878314/64280607-61177400-cf49-11e9-8969-41314e6694c4.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 23 37" src="https://user-images.githubusercontent.com/1878314/64280672-873d1400-cf49-11e9-9c42-4e93602be8b2.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 23 41" src="https://user-images.githubusercontent.com/1878314/64280721-9e7c0180-cf49-11e9-838c-db0d578a378b.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 26 53" src="https://user-images.githubusercontent.com/1878314/64280915-fd417b00-cf49-11e9-88e0-785af47a9fc0.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 27 49" src="https://user-images.githubusercontent.com/1878314/64281033-311ca080-cf4a-11e9-876d-4f2dc10336a7.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 27 59" src="https://user-images.githubusercontent.com/1878314/64281082-45609d80-cf4a-11e9-97c0-1d7ca7f19ff8.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 30 06" src="https://user-images.githubusercontent.com/1878314/64281190-80fb6780-cf4a-11e9-859e-c26cf1491755.png">
<img width="682" alt="Screen Shot 2019-09-04 at 19 32 12" src="https://user-images.githubusercontent.com/1878314/64281292-bb650480-cf4a-11e9-90ff-1ef684971fe8.png">
<img width="668" alt="Screen Shot 2019-09-04 at 19 33 44" src="https://user-images.githubusercontent.com/1878314/64281387-f1a28400-cf4a-11e9-8b59-2d013bdac583.png">
<img width="668" alt="Screen Shot 2019-09-04 at 19 35 12" src="https://user-images.githubusercontent.com/1878314/64281502-30383e80-cf4b-11e9-9889-2ce61fd3bd66.png">

**Comment by ChristopherRush** [comment]
<img width="668" alt="Screen Shot 2019-09-04 at 19 43 26" src="https://user-images.githubusercontent.com/1878314/64281975-498dba80-cf4c-11e9-8d1c-e7c4f6b3d115.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 35 23" src="https://user-images.githubusercontent.com/1878314/64285360-8b6e2f00-cf53-11e9-9020-805727918e69.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 37 26" src="https://user-images.githubusercontent.com/1878314/64285654-d720d880-cf53-11e9-8aa1-0e967d4d66fd.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 38 26" src="https://user-images.githubusercontent.com/1878314/64285704-fc154b80-cf53-11e9-9d8f-271ce1f4eb4b.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 39 29" src="https://user-images.githubusercontent.com/1878314/64285763-1e0ece00-cf54-11e9-910c-e00f8118d91c.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 46 37" src="https://user-images.githubusercontent.com/1878314/64286304-1ef42f80-cf55-11e9-9387-d3dbc271e253.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 47 21" src="https://user-images.githubusercontent.com/1878314/64286346-39c6a400-cf55-11e9-97f8-6ea280c434e2.png">

**Comment by ChristopherRush** [comment]
<img width="668" alt="Screen Shot 2019-09-04 at 20 54 43" src="https://user-images.githubusercontent.com/1878314/64286897-3f70b980-cf56-11e9-8ebf-b394df0668d9.png">
<img width="668" alt="Screen Shot 2019-09-04 at 20 59 31" src="https://user-images.githubusercontent.com/1878314/64287275-1ef52f00-cf57-11e9-965c-ade4f0dd6176.png">
<img width="668" alt="Screen Shot 2019-09-04 at 21 01 50" src="https://user-images.githubusercontent.com/1878314/64287319-3fbd8480-cf57-11e9-9454-011466c9a216.png">

**Comment by ChristopherRush** [comment]
<img width="584" alt="Screen Shot 2019-10-01 at 09 57 00" src="https://user-images.githubusercontent.com/1878314/65952218-7644cd00-e439-11e9-8c9a-381d5ce2d241.png">

**Comment by ChristopherRush** [comment]
![pijuice-github-banner](https://user-images.githubusercontent.com/1878314/73881793-e1c00080-4858-11ea-8ce8-e5bd4cc6f9b6.png)
