### ISSUE TITLE
Location of wake pin for Pi 3B+?

### ISSUE THREAD

**Issue by hoopsurfer** [PiSupply/PiJuice#80]
Looks like there is no way to use a pogo pin to configure wake for a Pi 3B+ device, what is the recommended workaround given the holes provided for TP1-TP3 are not big enough for a header?

TP1 may interfere with the new 4-pin POE header.

One alternative might be to drill out TP2 solder a single pin male header.  Then connect that connect that to a RUN/PEN header on the Pi 3B+.   Is it safe to drill out a very slightly larger hole in TP2? given the PC board design?

**Comment by shawaj** [comment]
It is not recommended to do so no. Using bare wire would be the safest option.

In the future we will revise the board, but for now you are on your own. If you damage the board by drilling it is your own responsibility, but you are welcome to give it a try.
