### ISSUE TITLE
Small error / typo in ReadMe.md

### ISSUE THREAD

**Issue by drewnj** [PiSupply/PiJuice#806]
I think the readme file still contains an error from a previous software version:
The published example of returned data for WakeUpOnCharge states: {'data': 127, 'error': 'NO_ERROR'}

The '127' I believe was a bug and the most recent software now returns {'data': 'DISABLED', 'error': 'NO_ERROR'} when WakeupOnCharge is disabled, all other possible returned data values being 0-100.

**Comment by tvoverbeek** [comment]
@drewnj Thanks for noticing this. Corrected now.
