### ISSUE TITLE
pijuice service status on boot on Raspberry?

### ISSUE THREAD

**Issue by OhSoGood** [PiSupply/PiJuice#821]
Hi,
On a fresh install of Raspberry Buster (official Lite image of January 2022) with Pijuice 1.7, I've noticed that after boot the pijuice service is in that state:
```
root@raspberrypi:~# systemctl status pijuice.service
● pijuice.service - PiJuice status service
   Loaded: loaded (/lib/systemd/system/pijuice.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

A `journalctl -u pijuice.service` shows an empty log.
If I manually launch the service, it then stays alive as expected.

Is that normal? Should I simply enable it? Is it supposed by design to always run, or to run at boot only, or... ? Any info would be appreciated, thanks!

**Comment by tvoverbeek** [comment]
Somehow the service is disabled.
`sudo systemctl enable pijuice.service`
`sudo systemctl start pijuice.service`
THn check if the pijuice service is running properly.
Reboot and check the service is running.

**Comment by OhSoGood** [comment]
Thank you
