### ISSUE TITLE
Stacking order

### ISSUE THREAD

**Issue by xstrex** [PiSupply/PiJuice#825]
Simple question, couldn't find the answer by searching, or in the docs; apologies if it's been answered already. 

Speaking of the PiJuice Zero, can it be placed on the bottom of the Pi, or should be be placed on top? Working on a project requiring a screen (which needs to be on top). 

So would this work?
PiJuice -> Pi Zero -> Screen

Or does it need to be..
Pi Zero -> PiJuice -> Screen

Thanks, love the PiJuice, awesome product!

**Comment by tvoverbeek** [comment]
Order does not matter as long as there are no I2c address conflicts between the screen and the PiJuice Zero.
You will probably need a stacking header e.g. https://www.adafruit.com/product/2223
