### ISSUE TITLE
Add tags/releases

### ISSUE THREAD

**Issue by cglewis** [PiSupply/PiJuice#826]
Great product - really enjoying it so far. One pain point is there are no tags or releases for the project so in order to get the debian package and firmware, cloning has to include whatever was committed most recently, which means caching a git clone isn't possible if/when updates are pushed to the repo. If tags were created when new versions are made then the repo could be cloned with the `-b <tag>` option which would ensure cache is preserved even as new changes are made to the repo.

**Comment by tvoverbeek** [comment]
Just added a tag (V1.8) to the current state of the main branch which corresponds to the just released 1.8 packages.
Will see what we can do about also including Releases

**Comment by cglewis** [comment]
Awesome, thank you!
