### ISSUE TITLE
Compatibility with other hardware (Orange Pi or Odroid) ?

### ISSUE THREAD

**Issue by OhSoGood** [PiSupply/PiJuice#831]
Hi,
Is there any info on the compatibility of the Pijuice with other hardware like Orange Pi (e.g. Orange Pi Pc) or Odroid (Odroid C4) ?
Thank you!

**Comment by tvoverbeek** [comment]
PiJuice only uses I2C and the power pins on the 40-pin header.
As long as the 40 pin header is compatible with RPi one you should be able to use it hardware wise.
Software is a different story. You probably need to adapt the RPi code to the respective OS and available python packages.

**Comment by pedrosk** [comment]
@OhSoGood I was wondering if you got it working on something else tha Raspi

**Comment by OhSoGood** [comment]
@pedrosk : no I haven't. Many SBC are not reliable enough to justify investing time into this subject, with the exception of the Odroid.

**Comment by pedrosk** [comment]
@OhSoGood : thanks for the info. I had a similar "reliability" concerns with some boards from my testings in the past as well
