### ISSUE TITLE
Size and/or reference of screw terminal for J5 connector ?

### ISSUE THREAD

**Issue by OhSoGood** [PiSupply/PiJuice#839]
Hi
I'm looking for mounting a screw terminal on J5, to allow to plug an external button easily (and 'removably', I don't want to solder the button's wire directly on the Pijuice). I don't know which keywords or characteristics to use to make a search on internet...

Does anybody has some references, preferably at Mouser or Digikey?

Would this item fit: https://www.amazon.com/dp/B095KJX8T6/ ?

Thank you!

**Comment by tvoverbeek** [comment]
J5 has the 'standard' 2.54mm (0.1inch) pitch, so your proposed item should fit.

**Comment by OhSoGood** [comment]
@tvoverbeek : Ton, as usual.... thank you very much for the help!
