### ISSUE TITLE
PiJuice with on/off switch

### ISSUE THREAD

**Issue by mroelandts** [PiSupply/PiJuice#848]
Hello,
I have bought a PiJuice Zero for a personal project.
I have a custom case and would like to use an external on/off switch. (toggle button or latching button)
From the documentation is appears only a momentary push-button is supported by J5. 
But I couldn't find any information about an on/off switch!
It there some kind of trick to control the raspberry with this kind of switch?

**Comment by tvoverbeek** [comment]
There is no on/off switch, but ...
You can connect a push button to J5. J5 is connected to SW2 on the PiJuice Zero.
Copy the settings from SW1 to SW2 (SHORT PRESS -> HARD_FUNC_POWER_ON and LONG PRESS1 -> SYS_FUNC_HALT_POW_OFF)
A short press will turn the Pi on and a long press will shutdown the Pi and turn the 5V from the PiJuice to the Pi off after 30 seconds.
When Pi is off and the PiJuice is running on battery it will be in low power mode and can run for several weeks (and keep the time in its RTC).
Hope this helps for your project.
