### ISSUE TITLE
PiJuice does not recognise GPIO power input

### ISSUE THREAD

**Issue by tvanpeer** [PiSupply/PiJuice#867]
I have a RPI4B with the USBC power connected. In the PiJuice Settings under HAT, the GPIO power input says:

**5.048V, 0.8A NOT_PRESENT**

At the same time the PiJuice is discharging, but if I remove the PiJuice, the PI runs normally on USBC power. 

I do have 'GPIO Input Enabled' switched on.

**Comment by tvoverbeek** [comment]
Is 'Charging enabled' also selected?

**Comment by tvanpeer** [comment]
> Is 'Charging enabled' also selected?

Yes

**Comment by tvanpeer** [comment]
Probably dust, all of a sudden it is charging again... Very odd.
