### ISSUE TITLE
reboot with Powercycle

### ISSUE THREAD

**Issue by leojrfs** [PiSupply/PiJuice#909]
Hello all,
Im trying to implement a reboot with powercycle, but im running into the following issue:

The `SetWakeUpOnCharge` is set to 10% (non_volatile=true).
Without removing the pijuice's micro-usb power, triggering `SetPowerOff(delay)` will power off the 5V.
After that, the pijuice wont turn the 5V on again unless the micro-usb power cable is replugged.

Is there a way I can force it to always wake up?

Is there a way to make the pijuice always turn on when its micro-usb power is ON, no matter what (independently of the previous state, or if battery is inserted, or if charging or not)?

**Comment by tvoverbeek** [comment]
If you leave external power connected to the PiJuice after the 5V has been removed then you can only restart the Pi by a button press or using an RTC alarm
