### ISSUE TITLE
Fix typo in EEPROM instructions, add UUID to settings.txt

### ISSUE THREAD

**Issue by ph818** [PiSupply/PiJuice#946]
I noticed a typo in the EEPROM instructions. `cd hat/eepromutils` should be `cd hats/eepromutils`

Also added instructions re: #622 about UUID

(Unfortunately, in my case /proc/device-tree/hat/ does not exist, but that is a different issue #945 )

Pull request #947 should close this. 
Correct typo `cd hat/eepromutils` > `cd hats/eepromutils`
Added walkthrough to add UUID to settings.txt

**Comment by tvoverbeek** [comment]
See commit https://github.com/PiSupply/PiJuice/commit/1dc136828e35143573257f22a9e3ab78d6a513d0.
Closing the issue.
