### ISSUE TITLE
Battery level not accurate when charging

### ISSUE THREAD

**Issue by jleval2** [PiSupply/PiJuice#99]
We noticed that the battery will say "64%" when it is plugged in and charging (under "settings" --> "HAT" --> "Battery"), but immediately drop to (what we believe) is the correct charge once unplugged (ex. 5% unplugged from 64% plugged).

We may be missing why this happens, but is there a more specific reason?

**Comment by sakura-lain** [comment]
Lol, we've reported the same problem almost at the same time! I've run a series of tests about that, would be happy to have an explanation too.

**Comment by ChristopherRush** [comment]
#100
