### ISSUE TITLE
it is possible to connect 2 solar panels serially?

### ISSUE THREAD

**Issue by jorgrde1** [PiSupply/PiJuice#991]
Hello there!
I have bought 4 solar panels of 22W, because there were no other in stock, so my question is if it is possible to connect 2 of thes pannels of 22W serially so I can get more power.

**Comment by tvoverbeek** [comment]
In principle yes. Of course the output voltage of the combined panels is two times the voltage of a single panel. The current will not be higher.
Read e.g. https://www.jackery.com/blogs/knowledge/solar-panel-series-vs-parallel
This deals with 'naked' solar panels, but most of it should be applicable to solar panels with built-in regulator (like the Pi-Supply ones)

**Comment by jorgrde1** [comment]
Ok, thank you I'll try.

**Comment by jorgrde1** [comment]
hey there, just to comment that it worked fine, I used two cables usb to usb [https://www.amazon.es/dp/B004Z9SJ64?psc=1&ref=ppx_yo2ov_dt_b_product_details](usb amazon) and one 2 usb fem to usb-c [https://www.amazon.es/dp/B0928M1D1P?psc=1&ref=ppx_yo2ov_dt_b_product_details](amazon link) i connected the usb-c to an usb-c to micro-usb adapter and directly to the pijuice battery and it worked fine

**Comment by tvoverbeek** [comment]
@jorgrde1 Your description above is 2 solar panels in a parallel configuration

**Comment by tvoverbeek** [comment]
Seems your problem is solved. Closing issue
